### ISSUE TITLE
cmplayer as a one stop audio/video management/library/playback

### ISSUE THREAD

**Issue by AcarBurak** [xylosper/bomi#116]
I know it's the opposite of the current cmplayer and you're not likely to take this seriously, but I can't help telling you:

mpv, in addition to its video capabilities, has those crucial audio capabilities as well: gapless playback and SPDIF output. So one does not need anything else AV-wise. Yet cmplayer's interface is too minimalistic for that. Such apps can only be used with the help of file managers and this is cumbersome, dysfunctional if you've got more than 50 albums/movies.

One needs a library management with covers: a minimalist one (like DeadBeef's) or a maximalist (but foolish) one (like Banshee's) or a minimalist/maximalist one (like the brilliant Qt-only/KDE mpd client, Cantata).

So if cmplayer has inherited those feauters of Cantata, i.e. has become the Cantata of both audio and video, it would take the world!

Cantata, being an mpd client, has the advantage of using mpc as global shortcuts and cmplayer might get this in its own way I guess. S/mplayer can be controlled globally by this, for instance: http://pbrisbin.com/posts/controlling_mplayer/

**Comment by kehugter** [comment]
++ to @Rabcor. An elegant, fast, versatile Linux video player with a proper GUI is a gap that bomi/CMPlayer is finally filling. Please don't bloat it.

**Comment by xylosper** [comment]
Obviously, lots of people want such big change.
Also, in my opinion, I prefer to use different player for musics and videos.
Although it's possible to add such management tool like VLC interface, if I thought VLC's good then I didn't make my player.
I'm sorry but I decided to do not implemnt this way.
Thank you for your thoughtful suggestions.
