### ISSUE TITLE
Exit and remember position for specific files only.

### ISSUE THREAD

**Issue by Rabcor** [xylosper/bomi#134]
A feature that I would love to have and I haven't seen anywhere else would be the ability to remember the position of only specific files when you close them.

Basically right now we only have an option in preferences to remember last position of all files, or none of the files. I would like to have a little button on the bottom of the Right-Click context menu labeled something like **Exit Remembering Position**

What this button would do is to save the position of the file for just one time, so the next time I open the file, it will open at the saved position, and then forget about the position as soon as it starts playing, so if I close the file again, it will start at the beginning (unless I clicked this button again that is)

This would be an nice compromise for users (like myself) who don't always want files to start playing at their last position, but still on occasion need to turn off files they haven't finished and would like to use it just for that one time. A best of both worlds thing :)

If you add this, a keybind idea for this feature would be **Ctrl+Shift+Q**, it makes sense next to Ctrl+Q for Quit.

**Comment by Rabcor** [comment]
I still think the best solution would be to add this button to the right click context menu whenever "Resume playback at last position" is disabled, then hide the button whenever the option is enabled (so the button would be hidden by default)

The alternative which is what I think you are aiming for is to have a button in the preferences menu next to the "Resume playback at last position"  that would be labeled "Enable exit remembering position button for saving playback position on a per file basis" (yeah it's long, I know, that's why I prefer just automating it)

Then when the button should be available, it will show up between "About" and "Exit" in the right click context menu (so it should be the second-lowest button) and it could have a keyboard shortcut like "Ctrl+Shift+Q" for convenience.

It's not really two different functionalities, the only difference is that on one hand you have "Remember playback position of all files" and on the other is "Remember playback position of files per user request" it's two implementations of the same function, one implementation is automated, the other is on-demand.

They should be named pretty much the same things (at least on the user interface's side, you can name it something else in the code) because they are pretty much the same thing.

Whenever the "Exit remembering position" button is enabled, the normal Exit button will cause bomi to "forget" the position of whichever file was played (if there was a remembered position)

**Comment by xylosper** [comment]
The most big problem of your request is that it's too difficult to define context and behavior.
You are obsessed by 'exit' action, but it's not then only case for a playback to be terminated.
If you stop the playback, then current playback is terminated.
If you open another file, then current playback is terminated.
Also, there are several ways to open new file, for instance drag&drop, open from filemanager, select in playlist, select in history, open by command line, open by JSON-RPC, and so on.
It's impossible to define such feature.

**Comment by Rabcor** [comment]
The feature needs to be explicit. I.e. most users that won't want the player to automatically remember the position of every file they play will probably only use this function a few times (some once per day, some once per month, and some maybe only 2 or 3 times a year, I'd be in the last category since I usually have time to finish what I start watching in one go)

I think an alternative exit action would be the most convenient way of doing this, since we need it to be explicit anyways, you don't have to worry about playback stopping or opening of another file, the only thing you'd have to define for these would be whether they will override (and make the player forget) the position of the file that was being played, or if they will not do it.

Ideally both of these functions should override (i.e. forget) the position as they normally do when playing without the automatically remembering option. (If the user is used to the behavior of most players, to forget the playback position as soon as a video is stopped, a new file is played or the player is terminated, then they will **expect** that behavior everytime they do not explicitly press a button to remember the position, like the "Exit remembering position" button I am suggesting these users would like to have. Me included of course.)

As for the many ways to open files; if you can make the player remember the position of every file that is opened, you must be able to make it remember the position of specific files when opened too; there's nothing impossible about it. I assume that after a file is opened, all files get routed to the same processing function which could be used to check things like this from an index file, just as your currently implemented "Resume playback at last position" option works in that kind of way, right?

**Comment by xylosper** [comment]
> I.e. most users that won't want the player to automatically remember the position of every file they play will probably only use this function a few time

Based on what? If you ask me, I'll tell you most users WANT to keep all history.
Please don't assume your case is general.and typical one.

> some once per day, some once per month, and some maybe only 2 or 3 times a year

If this is true, why do you care about it?
You had opened a file last year and opened it today again. 
This happens once for one year.
What makes you feel so inconvenient for an incident only few times for a year and which can be just solved by seeking to beginning?

>  if you can make the player remember the position of every file that is opened, you must be able to make it remember the position of specific files when opened too

It's about definition. Without definition, nothing can be implemented. It's not related with technical problem.
You only mentions about exit action, but why?
For instance, while a file is playing, you opened another file. If I follow your request as it is, previous file will be remembered because player is not exited. Is this what you expect?
If this is not what you expect, your definition is not enough.
If this is what you expect, I cannot help asking why.
What makes termination by openning new file different from termination by exiting?

**Comment by Rabcor** [comment]
>Based on what? If you ask me, I'll tell you most users WANT to keep all history.
Please don't assume your case is general.and typical one.

I said "most users that won't" not "most users won't", simple misunderstanding, I have no idea whether more users want to keep all history or not. I just belong to the ones that don't want to keep history of file positions for all video files I play; whether this is the majority or minority, I have no idea (although if you ask me I highly suspect it is the majority, since the most popular video player on all platforms; VLC doesn't come with this option enabled (if it even has it at all), and most people will want to stick with whatever they got used to first; which will most likely be VLC or Windows Media Player (which doesn't have this option either))

>If this is true, why do you care about it?
You had opened a file last year and opened it today again. 
This happens once for one year.
What makes you feel so inconvenient for an incident only few times for a year and which can be just solved by seeking to beginning?

By my once per day/month or 2-3 times a year example, I meant that the amount of times that it might happen that we'd want to save the history for a file, not that I'd save a file then open it a month or 2 years later (if that much time has passed I'd normally just watch the whole thing from the start again). More like once per month they have to stop in the middle of a movie and want to remember the position of it's playback the next time they open it, anywhere between 1 and 48 hours from then presumably. I'd say it'd happen to me 2 or 3 times per week, but not once a day. Seeking to the beginning wouldn't be a solution to any problem if all your files start at the beginning anyways as defined by your settings (you being a random user that has position history disabled)

>It's about definition. Without definition, nothing can be implemented. It's not related with technical problem.
You only mentions about exit action, but why?
For instance, suppose that you opened another file while playing a file.
If I follow your request as it is, previous file will be remembered because player is not exited. Is this what you expect?
If this is not what you expect, your definition is not enough.
If this is what you expect, I cannot help asking why.
What makes termination by openning new file different from termination by exiting?

I only mention an exit action because what I'm asking for is only required for an explicit action; and an exit action would just make the most sense in this context. (But if you think it would be better to create a "Save position" button, then by all means do that, I could live with that as well, but I still think an exit action makes the most sense which is why I keep pressing for it) In other words, what I mean is that **every** case where the exit remembering position button was not explicitly pressed by the user, the file position should just be forgotten as usual (when resuming all files is disabled in the preferences menu that is) most users that do disable the option for resume history; will expect file position to be forgotten whenever they exit a file no matter how they exited (unless there is an option like this that they can use to bypass it and save it for one specific file on demand; a button made just to do exactly this).

As for further definition, the exit action should only remember the file currently being played, when the file is re-opened after that exit action, it's position should be erased out of the index after it loads up (meaning forget it as soon as the file opens up) this solves the problem of still remembering the file if a new file is opened without exiting the player in any way.

In summary, it should work something like this:


* When "Resume playback at last position" option is disabled, an "Exit remembering position" action will appear in the context menu above the existing Exit action entry. (And whenever "Resume playback at last position" is enabled again this option should disappear)
* Exit Remembering Position has an index of some sort to remember the positions of files exited with this command. (Whatever you use for remembering files with the currently existing function is fine)
* When a file is opened this index is checked for a matching file and if found, it will open at the saved position and then the index entry for the file in question will be removed/forgotten, so that if the file is now exited normally (or not exited at all in some funky case of crash or whatever) it will open at the beginning the next time it will open unless the exit remembering position action was pressed again.
* Exit Remembering Position only adds the currently open file to the index when used and ignores any previously opened files.
* (Alternative to the below: When "Resume playback at last position" is enabled, the "Exit remembering position" index will just be ignored, might be easier to code)
* Whenever "Resume playback at last position" is re-enabled, the index used by "Exit remembering position" if it exists will be checked against the "Resume playback at last position" index for matching file entries, if both indexes have an entry for the same file, the one of the "Resume playback at last position" would be preferred (since the option is enabled; if the option is disabled only the "Exit remembering position" index will ever be checked to begin with).
* If "Resume playback at last position" is enabled, and a file entry is found in the "Exit remembering position" index but not the "Resume playback at last position" index, the file will be naturally opened as defined above for files on this index.

That sums it up pretty decently I think, the way I described it you have two options, one is to always check the index file of the "Exit remembering position" when a file is opened no matter if the current function "Resume playback at last position" is enabled or not, it's a bit more code, but I also think it's a bit cleaner from the user's side. The other way is to keep the new "Exit remembering position" action *sandboxed* away from the Resume playback at last position option by only checking the index of "Exit remembering position" when "Resume playback at last position" is disabled; and never when it is enabled (this way might be a bit safer, i.e. no added risk of crashes by the two functions conflicting with one another) but I will leave that sort of thing up to the more experienced programmer; you.

There is also a third option I guess. Make both files us the same index (e.g. "Exit remembering position" would save the file position to the same index/through the exact same function as "Resume playback at last position" does right now, but it would also have an additional index file where it just writes the filenames of files saved with this function, then on opening the files when "Resume playback at last position" is disabled, this second index will be checked for a matching filename, and if found the position will be fetched from the same index as we have in the existing function, and the filename will be erased from the second index. It might be a bit cleaner (code-wise) and less conflict prone to do it this way, but this way or the way I described above is all the same to me as an end user)

**Comment by xylosper** [comment]
I still couldn't get answer for the question: why termination by exiting is special?.
'Because exiting action is explicit' isn't good reason.
There's no hidden action which terminates current playback.
Everyone knows that open new file means to terminate current playback.
Everyone knows what 'stop' button means.
Without reasonable cause, I'll have to add, for instance, 'Play next with remembering position of current playback', 'Stop current playback with remembering position', 'Open file with remember position of current playback', and so on.

What I can offer from your description with my best is 'Seek to saved position' because bomi always keeps recording anyway.

**Comment by Rabcor** [comment]
Exiting action isn't explicit, pressing the actual button (or keybind for it) is an explicit action on the users behalf; the action of pressing a button is an explicit user action. I think you're just not completely understanding what I'm asking for; you would not have to change anything about the players actions for opening the next file, or all that other stuff you said. You would only have to add a new button and code in the file saving function for it then refer it to your existing exit function, and then add one or two small if/else statements to the existing file opening function; or that's how I envisioned it anyhow.

But anyways, if bomi always remembers the position of a file exited regardless of user settings then yeah, a seek to saved position button would be an acceptable solution if you would do that. It might be a bit tricky to label it though. "Seek to last known position" is the best I can think of, but even that is not an ideal label...

"Seek to position of the file before it was last closed" is a bit long and confusing after all; whereas "Seek to last known position" is rather vague (Last known position in what context?)

"Seek to position of last playback" might be closer, but still could easily be misunderstood.

"Seek to position from last playback" is closer,
"Seek to position from last playback of this file" would be good enough even if it's a bit long.

You decide what to label it :+1: I've suggested all I can think of in that regard.

**Comment by xylosper** [comment]
I think 'saved position' or 'recorded position' is most clear because, literally it's saved/recorded position in history.

As you said, last known position without context could make user confused because the practical last know position for current playing media is just current playing time.
Also, in the phrase of position for last playback, 'the last' playback is current playback.
I think 'previous' is better word than 'last' if I take this phrase.

**Comment by xylosper** [comment]
Implemeneted with 'Play > Seek > Recorded Position' for now.
This menu is disabled when no record exists.
The menu name can be changed so, if you have better idea please let me know.
If you think it would be ok, please close this.

**Comment by Rabcor** [comment]
I think you had it at previous;

seek to 'Last position of previous playback' or even "Previous playback's last position"

Yeah, I like that, "Previous playback's last position" is good I think.

**Comment by xylosper** [comment]
It's definitely clear but too verbose... What about just 'Previous Playback'?
It's a submenu of 'Play > Seek' and, any item in there suppose to denote some kind of position anyway.

**Comment by Rabcor** [comment]
Yeah, considering the context we have in the seek menu, 'Previous Playback" should be good enough.

**Comment by xylosper** [comment]
The problem of 'last playback' is, as I already pointed out, the last playback is current playback because it's already started to be played.
In the context of resuming playback, the playback is not yet started, so 'last played position' makes sense.
However, this feature is supposed to be used after start of new playback, that is during playback and current playback becomes the last playback.

**Comment by Rabcor** [comment]
Well, if you prefer to call it 'Previous Playback' I'm cool with that too, I guess in a sense now that you say that again, neither previous nor last is a perfect term to use for this, but both can work, so you pick the one you like better, and lets use that.

**Comment by xylosper** [comment]
Named `Previous Playback` and shortcut is alt+home.
Thanks alot!

**Comment by Rabcor** [comment]
Thank you :)
