### ISSUE TITLE
Motion Interpolation

### ISSUE THREAD

**Issue by Rabcor** [xylosper/bomi#148]
I have a feature request, on some forums I noticed an interesting thread titled "anyone else watching videos at 60fps?" (Turns out he was looking for help because of A/V desyncs) I looked into it a bit further and turns out they use an interesting technique called [Motion Interpolation](https://en.wikipedia.org/wiki/Motion_interpolation), the most notable project focusing on this would be the [Smooth Video Project](http://www.svp-team.com/), they do it apparently with the help of AviSynth, unfortunately AviSynth's development has been stalled since 2007 but an [AvxSynth](https://github.com/avxsynth/avxsynth/wiki) project exists which is a linux port of said AviSynth.

There's been some discussion on this on the [Arch forums](https://bbs.archlinux.org/viewtopic.php?id=183946) too, or users annoyed by the lack of a player capable of doing this. Cmplayer could become the first to do it properly. It seems we already have a player that can slow down framerate smoothly, but not the other way around (at least not on the fly).

I realize that this might be a bit of a big feature request (major feature), so far this has almost only been seen in commercial video players (like PowerDVD and WinDVD), and since this isn't exactly my strongest area in coding I don't have any good ideas for how it could be done here, but it most certainly would be a very interesting feature to have, and many (including me) would use it, as long as they have the hardware for it that is. (Many would possibly even just start using CMPlayer because of this feature if it had it) think you can do it, Xylosper?

**Comment by xylosper** [comment]
It seems that mpv's trying this although I'm not sure I can use that feature.
There might be some good news.

**Comment by Rabcor** [comment]
Oh yeah it would be awesome, since Youtube supports 60FPS playback now I]ve seen some examples there, and it actually does look awesome to have this. If you've watched a lot of animation like me, i'm sure that you've noticed how there's a noticable lag, or "jump" between frames (especially noticeable when the camera is panning, or moving horizontally over a background/landscape, if you look at the edges of the view you will see it, subtle, but there) this motion interpolation smooths that away by adding frames inbetween these "jumps"

It's really cool, I never expected that (considering how everyone hated HFR/48FPS movies in cinemas) it works out incredibly well for animation. I think for movies people would have to get used to the higher framerates more, since 24fps has been a standard for movie recordings since god knows when... and people are used to that shit quality, anything higher just feels "off"

**Comment by xylosper** [comment]
Integrated it and added 'Video > Motion Interpolation' menu but I'm not sure it's working well.
Can you test it?

**Comment by mac1202** [comment]
I tested it and I get the same result as mpv with smoothmotion option enabled so I think you can close this one.

**Comment by xylosper** [comment]
Fine. Thank you.
