### ISSUE TITLE
Disable Screensaver Not Working

### ISSUE THREAD

**Issue by Rabcor** [xylosper/bomi#152]
After I updated to the latest version, I'm getting screen blanks while I'm in the middle of video files.

I'm pretty sure this didn't happen before. I'm running openbox. I completely forgot how I configured my screen blanking (if I configured it at all; I think it's set to default) but it's on 10 or 15 minute intervals it would seem.

**Comment by dontdieych** [comment]
@Rabcor try `xset s reset` as external command. Set interval less than your scrrensaver timeout. `xset q` would show that value.

@xylosper how about consider this as fallback method? It also blocking dpms trigger.

**Comment by dontdieych** [comment]
I've found `xset` required by 'xdg-utils' package and there is `xdg-screensaver` command. 'xdg-utils' has `xdg-open`. So, we can be sure about that there will be `xdg-screensaver`.

It supports suspend and resume in addition to reset.

```
       suspend WindowID
           Suspends the screensaver and monitor power management.  WindowID must be the X Window ID of an existing window of the calling
           application. The window must remain in existence for the duration of the suspension.

           WindowID can be represented as either a decimal number or as a hexadecimal number consisting of the prefix 0x followed by one
           or more hexadecimal digits.

           The screensaver can be suspended in relation to multiple windows at the same time. In that case screensaver operation is only
           restored once the screensaver has been resumed in relation to each of the windows

       resume WindowID
           Resume the screensaver and monitor power management after being suspended.  WindowID must be the same X Window ID that was
           passed to a previous call of xdg-screensaver suspend
```

**Comment by dontdieych** [comment]
Anyway, I've got same problem in Arch linux + xmonad. I saw fallback to XResetScreenSaver() in debug output but did not working.

**Comment by xylosper** [comment]
As far as I know, I cannot figure out XResetScreenSaver() failed.  Without recognization of failure, no way to fallback to other method. In fact, XResetScreenSaver() should be the last fallback for every WM/DE which utilizes X11.

**Comment by xylosper** [comment]
I've added some code for screen saver. Since I cannot reproduce this problem, I'm not sure this is right fix, so please test and let me know.

**Comment by dontdieych** [comment]
It's working but one glitch.

If I set timeout 5sec and then play video, it changed to 0sec. If I quit bomi, it changed to 600sec(default). So we lost previous timeout setting.

**Comment by xylosper** [comment]
I can make it recovered. However, one big problem is there's a change to lose settings anyway if bomi crashed. So, I don't think this method is desirable. Reverted it.

**Comment by xylosper** [comment]
@dontdieych  Btw, does `xset s reset` work for you? I've looked the source code of xset and that command does exactly one call of `XResetScreenSaver()`, so if that command works for you, then there should be no problem.

**Comment by dontdieych** [comment]
Yes, it works.

I've tried like this,

```
xset s 5
watch xset s reset # or xdg-screensaver reset
```

I'm using xmonad and there is `XResetScreenSaver()` wrapper function. So I tried with that but no luck.

http://xmonad.org/xmonad-docs/X11/Graphics-X11-Xlib-Misc.html#v:resetScreenSaver

```
import Graphics.X11.Xlib
import Graphics.X11.Xlib.Misc
import Control.Concurrent
import Control.Monad

main = do
    dpy <- openDisplay ""
    forever $ do
        putStrLn "reset"
        resetScreenSaver dpy
        threadDelay (5*1000000)
```

At least we are not the only one.

**Comment by dontdieych** [comment]
https://www.haskell.org/pipermail/xmonad/2015-January/014506.html

I'd ask about this once to xmonad mailing list but no answer.

**Comment by xylosper** [comment]
Which is totally not understandable.
```c
    } else if (strcmp(arg, "reset") == 0) {	/* force it inactive */
        XResetScreenSaver(dpy);
        i++;
    } else if (*arg >= '0' && *arg <= '9') {	/* Set as user wishes. */
```
This is exactly what `xset s reset` does.

**Comment by dontdieych** [comment]
What is exactly `dpy` variable means? My haskell code are copy and pasted from somewhere. So I don't know what is exactly means `dpy` on `resetScreenSaver dpy`

Does it matter if I use dual monitor setup?

```
$ xrandr
Screen 0: minimum 8 x 8, current 3200 x 1080, maximum 8192 x 8192
DVI-I-0 disconnected (normal left inverted right x axis y axis)
VGA-0 connected primary 1280x1024+1920+0 (normal left inverted right x axis y axis) 376mm x 301mm
   1280x1024     60.02*+  75.02
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   800x600       75.00    72.19    60.32    56.25
   640x480       75.00    72.81    59.94
TV-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     60.00*+  59.94    29.97    23.97    60.05    60.00
   1680x1050     59.95
   1600x900      60.00
   1440x900      59.89
   1366x768      59.79
   1280x1024     75.02    60.02
   1280x800      59.81
   1280x720      60.00    59.94
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   800x600       75.00    72.19    60.32
   720x480       59.94    60.05
   640x480       75.00    72.81    59.94
```

**Comment by xylosper** [comment]
`dpy` is `Display` variable which is obtained by `XOpenDisplay()`.

> Does it matter if I use dual monitor setup?

I don't know but I think it doesn't matter.

**Comment by xylosper** [comment]
Added xss code to suspend/unsuspend screensaver. Please test it.

**Comment by dontdieych** [comment]
I've found something. At least my haskell code, calling `getScreenSaver` before `resetScreenSaver` does something and it's working.

https://www.haskell.org/pipermail/xmonad/2015-February/014545.html

**Comment by dontdieych** [comment]
If we can reproduce this from minimal c or c++ code, we could ask about this to upstream.

**Comment by xylosper** [comment]
Did you try the latest git source? If it works for you, it would be better.

**Comment by xylosper** [comment]
```c
#include <stdio.h>
#include <string.h>
#include <X11/Xlib.h>
#include <unistd.h>

int main(int argc, char **argv) 
{
    if (argc != 2 || (strcmp(argv[1], "get-reset") && strcmp(argv[1], "reset"))) {
        printf("Usage: %s [get-reset|reset]\n", argv[0]);
        return -1;
    }
    Display *dpy = XOpenDisplay(0);
    int timeout, interval, blanking, exposures;
    int get = !strcmp(argv[1], "get-reset");
    
    for (;;) {
        if (get) {
            printf("Call XGetScreenSaver()\n");
            XGetScreenSaver(dpy, &timeout, &interval, &blanking, &exposures);
        }
        printf("Call XResetScreenSaver()\n");
        XResetScreenSaver(dpy);
        sleep(10);
    }
    XCloseDisplay(dpy);
    return 0;
}
```

Here's a short code to reproduce it. Compile it with `gcc -lX11 <filename>` and execute it `./a.out reset` for XReset only and `./a.out get-reset` for XGet/XReset.
Although I cannot find any documentation, maybe Get->Reset is right usage?

**Comment by dontdieych** [comment]
It's working well. Current setting does not reset.

I'll checkout this code.

**Comment by xylosper** [comment]
Okay then I'll go with xss suspending. Thank you.

**Comment by dontdieych** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=89028#c1

See this.

**Comment by xylosper** [comment]
So, XFlush() works for you?

**Comment by dontdieych** [comment]
Yes, It's working.


        printf("Call XResetScreenSaver()\n");
        XResetScreenSaver(dpy);
        XFlush(dpy);
        sleep(3);

**Comment by xylosper** [comment]
Okay, thank you. I'll put a code to flush.

2015-02-09 2:21 GMT+09:00 dontdieych <notifications@github.com>:

> Yes, It's working.
>
>
> printf("Call XResetScreenSaver()\n");
> XResetScreenSaver(dpy);
> XFlush(dpy);
> sleep(3);
>
>
> On Mon, Feb 9, 2015 at 2:17 AM, Lee, Byoung-young
