### ISSUE TITLE
Missing file 'subtitlestyle.hpp'?

### ISSUE THREAD

**Issue by mmetak** [xylosper/bomi#158]
562s] In file included from subtitle/subtitlerenderingthread.hpp:4:0,
[  562s]                  from subtitle/subtitlerendereritem.cpp:2:
[  562s] subtitle/subtitledrawer.hpp:4:29: fatal error: subtitlestyle.hpp: No such file or directory
[  562s]  #include "subtitlestyle.hpp"

**Comment by xylosper** [comment]
Wasn't all packages depending on ffmpeg blacklisted?
I used to ditribute packages through OBS but I abandoned it after I read this doc:
https://en.opensuse.org/openSUSE:Build_Service_application_blacklist

**Comment by mmetak** [comment]
Somehow I forgot about that... ;-)
I guess I'll just remove those blacklisted packages from my project page...
