### ISSUE TITLE
dvd 에서 yadif 디인터레이싱이 안됩니다.

### ISSUE THREAD

**Issue by p76837** [xylosper/bomi#165]
iso 파일을 마운트 하여도 장치에 실제 디스크를 넣어도 yadif 디인터레이싱이 안됩니다.

**Comment by xylosper** [comment]
git 소스에서 정상 작동하는 것을 확인하였습니다. 최신 소스로 다시 시도해보시기 바랍니다.

**Comment by xylosper** [comment]
피드백이 없어 닫습니다.
