### ISSUE TITLE
--action <id>

### ISSUE THREAD

**Issue by dontdieych** [xylosper/bomi#172]
사용 가능한 id 목록을 어디서 찾아볼 수 있을까요?

play
stop
toggle pause
next subtitle
next/prev item in playlist

이런 기능들이 필요 합니다.

**Comment by xylosper** [comment]
현재 별도 문서는 없고 환경 설정>유저 인터페이스>키보드 단축키 항목을 보시면 모든 메뉴 항목이 나오는데 각각의 메뉴에 해당하는 action id가 오른쪽 끝 컬럼에 표시되어 있습니다.

**Comment by xylosper** [comment]
참고로 재생이라는 건 없고 play/pause 가 재생/일시정지 전환역할만 합니다.

**Comment by dontdieych** [comment]
잘 되는데 반응 속도가 좀 느리네요.

```
time cmplayer --action play/pause
[Translator] Cannot find translations for Qt, qt_en_US in /usr/share/qt/translations
[Main] Another instance of CMPlayer is already running. Exit this...
0.14user 0.08system 0:00.91elapsed 25%CPU (0avgtext+0avgdata 68136maxresident)k
0inputs+208outputs (0major+7392minor)pagefaults 0swaps
```

dbus 인터페이스를 사용하니 반응 속도가 만족스럽습니다. 다만 Seek 메소드를 호출할 때 offset을 어떻게 지정해야 하는지 모르겠네요.

```
qdbus org.mpris.MediaPlayer2.CMPlayer /org/mpris/MediaPlayer2 Seek 1000000
```

1~2초 가량 앞으로 이동 하는데 숫자를 크게 해봐도 변화가 없네요.

**Comment by xylosper** [comment]
--action 명령은 새로운 어플리케이션을 구동시켜서 메시지를 전달하고 종료하는 방식이기 때문에 느릴수밖에 없습니다.
Seek의 인자는 마이크로초입니다. 1000000이라고 쓰면 1초 앞으로 갑니다. -5000000라고 쓰면 5초 뒤로 갑니다.

**Comment by dontdieych** [comment]
감사합니다. 잘 되네요.

리눅스 사용하면서 오랫동안 자막 처리 잘 되고 편의성 좋고 재생, 탐색 성능 좋은 플레이어를 원했었습니다. CMplayer가 그 자리를 채워주네요. 감사드립니다.

**Comment by xylosper** [comment]
잘 된다니 다행입니다. 감사합니다.
