### ISSUE TITLE
OSD Timeline Seekbar Timeout (causing distraction) & Position

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [xylosper/bomi#173]
Hello, excellent work on this great MPV frontend!  It's now my favourite (after many years using SMPlayer!)  (Also; BOMI!? - I see (in commit log) you've decided to rename CMPlayer to Bomi 7 hours ago! Interesting...)

My issue;  The OSD Timeline Seekbar takes 2.5s (or 3s) to disappear.  

I have shortcuts set to seek back 2s in case I missed a word of dialogue (happens a lot to me - I'm always working / multi-tasking, & often lose focus for a small moment and miss a word or two, so I quickly mouse over the video & scroll-seek back 2s to hear what was missed)

I find the timeline VERY distracting during this time.  It's position is also right in the middle.  

I would like a custom timeout option for the timeline (I would like ½s / 0.5s, maybe 1s, but other people may want something else).

I would also like a option to specify the placement of the timeline seekbar.  I would likely place it near the bottom (but maybe at the top to avoid clash with subtitles which I always have visible - helps multi-tasking!)

So; options for timeline-seekbar custom timeout, & custom position. 

Thank you

**Comment by xylosper** [comment]
Thank you for compliment.

When you say 'custom position', should it be fully customizable?
It's easy to add some options to adjust position for top/middle/bottom and can be done soon. However, to support fully customizable postion, I expect quite big job for this.

**Comment by xylosper** [comment]
I added some options to configure these. You can find them in pereference > Appearance > OSD. If you think it works for you, please close this.

**Comment by KangarooCreativeTeam** [comment]
OMG WOW - that was fast!  Thank you so much! 

I'll be honest - I'm not good at packaging (I'm currently using your PPA) & I've been trying a lot (~2h *very* late night), but am having loads of dependency issues.  Yeah - I suck in this area :(  

Now, I'm **not** going to be a [help-vampire](http://slash7.com/2006/12/22/vampires/) about it, so I'll just wait weeks / months until the PPA is officially updated o_O  

I'll say a huge thank you in advance, & I'll update this with another thank you once I've tried it out :P  

Also as much as the control-freak in me would love the option for precise custom positioning, as it's going to be a lot of work, I'm sure what you've done will suffice.  (I'll give feedback once I've eventually tried it out :P )

I wish I could help contribute to this project / fix bugs / provide features myself, but my speciality lies in Python, & Django.  If you need help in these areas, I'll be happy to help :)  Just give me a shout! 

O_O

**Comment by xylosper** [comment]
I just pushed to make the margin for timline position configurable, so close this. Thank you.
