### ISSUE TITLE
no https support

### ISSUE THREAD

**Issue by mc4man** [xylosper/bomi#174]
Wondering why no https support in your ffmpeg build?
Somewhat renders youtube-dl less than useful

Tested via ppa trusty build

**Comment by xylosper** [comment]
> Wondering why no https support in your ffmpeg build?

I don't know. Does it? What flag disabled it? Here's my flags:

```
args="--prefix=`pwd`/build --enable-gpl --disable-debug --disable-shared --enable-static \
  --enable-runtime-cpudetect --disable-doc --disable-programs \
  --disable-avdevice --enable-avfilter --enable-swresample \
  --disable-avresample --enable-pthreads --disable-dxva2 --enable-postproc \
  --disable-encoders --disable-muxers --disable-devices --enable-filters"
```

> Somewhat renders youtube-dl less than useful

What do you mean?

**Comment by mc4man** [comment]
Well I guess it doesn't really matter, if one has urls that are https many times they'll work if the s is removed.
Though overall why have to bother to, enabling the protocol in ffmpeg takes care of having to notice, ect.
Here I use gnutls (--enable-gnutls) though openssl is also an option (--enable-openssl

As far as debian/ubuntu builds,  which gnutls to add to the control file depends on release using
(14.04 should use  libgnutls-dev, 15.04+ should use  libgnutls28-dev,  - 
https://github.com/mpv-player/mpv-build/issues/53

**Comment by xylosper** [comment]
Enabled gnutls support. Thank you.
