### ISSUE TITLE
Find subtitle not work in Bomi

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#176]
Find subtitle now not work on bomi, i have bomi-git-0.8.16.r40402.g0a3cd9c-1-x86_64 newest pull from git, and i use Arch linux, i deleted all settings and tryed again, but still not list subtitles for movies, i tryed on smplayer too, and there work.

**Comment by xylosper** [comment]
There's a promised name to communicate with opengsubtitles and it contains 'CMPlayer'.
When I replaced CMPlayer with bomi automatically, it shouldn't be changed.
Now I've reverted, so it should work now.

**Comment by Kosava** [comment]
Now works, thanks.
