### ISSUE TITLE
transifex support

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#177]
Could you add transifex support? It would make the translation process faster and easier.

**Comment by xylosper** [comment]
I don't know transifex well but with a glimpse, I found that It's not free.

https://www.transifex.com/pricing/

And I don't think it's worth paying.

**Comment by ahjolinna** [comment]
I'm translating calamares with it, it's really good...there is even SailfishOS app for it so I can even do the translations with my phone

**Comment by xylosper** [comment]
Well, If I were rich enough to play $19 for every month for no-income-project, it was possible.
But I'm not, and transifex is not an option for me. Thank you.

**Comment by ahjolinna** [comment]
It seems if your project is open source u can use transifex for free:
"I have an open source project. Where do I sign up?
We are committed to supporting open source initiatives! Open source projects can sign up for free using the option above and enjoy unlimited translations. If you’re an open-source project and need a premium account for some reason, get in contact with us."

**Comment by xylosper** [comment]
I've read descriptions and viewed the video and tried a bit, but I cannot found any merit.
As far as I can see, it's just translation web interface which can be done by linguist without compatibiliy issue in offline.
What does make transifex special?

**Comment by ahjolinna** [comment]
Every "language team"  has "coordinator, reviewer and oc translator".
web interface looks great and it is simple for this job...your old/current way is hard for many.
It also has a good community.
there is a reason why many uses transifex...at least Qt apps and jolla, sailfishOS apps

**Comment by M4rtinK** [comment]
The main benefit of using a web based translation platform is the lowered barrier to entry. Basically it is more likely that people will translate your project using a simple to use web interface (with a one-time registration) than:
* install linguist
* download your translation files
* load them to linguist
* do the translation
* save the result
* send it to you/send a pull request, etc.

Some people who would like to help with translations might not have the necessary technical skills to do that, but they would be able use a web interface just fine.

BTW, Transifex going proprietary - that's unfortunately correct and for that reason we are switching from Transifex to Zanata (which is fully open source) in Fedora:
https://lists.fedoraproject.org/pipermail/infrastructure/2014-July/014475.html

Still AFAIK they should still have some sort of free tear/plan for open source projects and I have been using like that to translate my Mieru application without ever paying anything to Transifex:
https://www.transifex.com/projects/p/mieru/
The Jolla Czech translation project also uses Transifex and AFAIK they are also not paying for it (I can ask the maintainer):
https://www.transifex.com/projects/p/jolla-cesky/

So I would recommend using some web based translation platform (Transifex, Zanata, whatever) to make it easier for translators. All of these platforms usually provided command line tools that make it easy to integrate them to the build process - one command for feeding string updates to the service and another one for pulling new translations. So using such a service basically amounts to a one-time registration, project creation and build system integration. After that you just update the strings and pull translation updates from people automatically. :)

**Comment by xylosper** [comment]
I reopen this because at least this can be an option for me too.

@ahjolinna 

> Every "language team" has "coordinator, reviewer and oc translator".

I don't have a team.

> web interface looks great and it is simple for this job

Have you ever seen linguist? It's simpler than transifex interface about one hundred times.

> your old/current way is hard for many.

for many, for instance?

> there is a reason why many uses transifex...at least Qt apps and jolla, sailfishOS apps

But there's no reason I have to follow their way. it cannot be a reason to change something.
It is a good reason that new way is better, and I cannot find better thing.

@M4rtinK 

> Some people who would like to help with translations might not have the necessary technical skills to do that, but they would be able use a web interface just fine.

You don't need any special techincal skill to use linguist.

> BTW, Transifex going proprietary 

Well, I don't mind using proprietary things if there's no legal/license issue.
Also, I think it's not a news because transifex.org in github is abandoned way before.

> So I would recommend using some web based translation platform (Transifex, Zanata, whatever) to make it easier for translators.

How does web based translation platform make translation easier?
I've already tried transifex as I said and I found it loses all context for translations and any comments.

I'll check zanata, too anyway.

**Comment by xylosper** [comment]
All translation files are uploaded to transifex. If you want to translate, plase request there: https://www.transifex.com/projects/p/bomi/

**Comment by ahjolinna** [comment]
nice, thanks

**Comment by ahjolinna** [comment]
@xylosper : could u add Finnish (Finland)...what I just requested, so I and one other can start to translate
