### ISSUE TITLE
재생 목록의 기록을 보관하면 어떨까요

### ISSUE THREAD

**Issue by dontdieych** [xylosper/bomi#178]
파일 단위로 재생 정보를 저장 해두는 기능이 아주 쓸만 합니다.

한가지 아쉬운 점은 시리즈로 된 영상들을 연속해서 보다 종료하면 내가 어느 파일까지 봤는지 정확히 기억하기 힘들때가 많습니다. 9편 보기 시작해서 12편까지 봤던가 13편까지 봤던가 고민하게 되는 경우가 많습니다.

Recent File 기능은 처음 재생을 시작한 9편 파일 만을 기억하는 것 같습니다. 하지만 연속해서 한 편 이상을 시청한 경우는 도움이 되질 않습니다.

Recent File 기능을 다음과 같이 만들어서 파일을 열 때마다 바뀌는 재생 목록들을 기록해 두면 어떨까요?

```
tv-show-A-s01e04 (4/13)
movie-B (1/1)
tv-show-B-s03e11 (11/14)
재생중이던 파일 이름 (재생 목록에서의 위치)
```

재생 목록이 바뀌는 경우 마지막 재생 중이던 파일 이름과 재생 목록에서의 위치를 보여주면 이어 보기가 한결 수월해질 것 같습니다.

**Comment by xylosper** [comment]
히스토리 기능을 써보셨나요? V키를 누르면 나오는데 재생한 모든 파일이 기록되어있습니다.

**Comment by dontdieych** [comment]
원하는 용도로 쓸만한 것 같습니다.

감사합니다.

2015-01-18 20:34 GMT+09:00 xylosper <notifications@github.com>:
