### ISSUE TITLE
black frame 찾는 기능이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by dontdieych** [xylosper/bomi#179]
영상 앞쪽의 지난 줄거리나 인트로 영상을 자동으로 건너뛰는 용도로 쓸 수 있을까요?

**Comment by dontdieych** [comment]
avidemux 사용하다가 이 기능을 써봤는데 재생기에 있으면 참 쓸만한 기능일 것 같습니다.

어차피 지금도 눈으로 보면서 화살표 키로 건너 뛰고 있으니 정확도가 그렇게 높지 않아도 도움이 될 겁니다.

**Comment by xylosper** [comment]
아직 재생하지 않은 부분의 정보를 가져온다는 건 불가능합니다.
avidemux의 경우는 '재생'이 아니라 '스캔'의 개념이기 때문에 모든 프레임을 디코딩한후에 분석하면되지만 플레이어의 경우에는 그때그때 필요한 부분을 디코딩하여 재생해야 하므로 이것처럼 앞부분의 내용을 미리 가져오는 기능은 플레이어의 들어가기엔 좀 힘든 기능입니다.
플레이어에서도 하려면 '스캔'하는 건 가능하니까 약간의 딜레이가 있어도 상관없다면 고려해볼만 한거 같습니다.
예를 들어 5분후에 black frame이 있다고 하면 이걸찾으려면 처음 5분 분량을 디코딩해서 찾아야되는데, 5분치의 디코딩하는 시간(얼마나 걸릴진 모르겠지만 30초~1분 정도걸릴듯합니다)동안 기다려야겠지요.

**Comment by dontdieych** [comment]
재생하는 동안 동작해야 하는 기능은 아니니 재생을 잠시 멈추고 스캔 해도 상관 없을 것 같습니다.

2015-01-18 20:32 GMT+09:00 xylosper <notifications@github.com>:

**Comment by dontdieych** [comment]
영상 앞 부분을 건너뛰는 용도로 제한해서 생각한다면 5분에서 10분정도로 제한 시간을 정해 놓고 스캔하는 것이 안전하겠네요.

2015-01-18 20:41 GMT+09:00 Dontdie YCH <dontdieych@gmail.com>:

**Comment by xylosper** [comment]
추가하였습니다. 좋은 의견 감사합니다.

**Comment by dontdieych** [comment]
http://i.imgur.com/YMQCtYo.png

우측 하단의 방송사 로고 때문에 블랙 프레임으로 판독이 안되는 걸까요? 같은 시리즈의 영상 두 개로 실험해 봤는데 시간이 한참 지나도 찾질 못하네요.

**Comment by xylosper** [comment]
그럴순 있는게 맞습니다만 저정도 어두우면 판독할 수 있을듯합니다. 파일을 받아서 작업해봐야알수 있을 듯합니다.

**Comment by dontdieych** [comment]
magnet:?xt=urn:btih:HBIQRK45GZEPMS5VFMJL2SUPECIYJKGR&dn=Homeland%20Season%201~3%20Complete%20720p&tr=udp%3a%2f%
2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%
2ftracker.publicbt.com%3a80%2fannounce

s01e02
s01e09

저 두 파일로 해봤었습니다.

화면을 사등분하고 그 중 세군데 이상이 블랙인지 확인하면 어떨까요? 보통 방송사 로고가 네 귀퉁이 중 한 군데에 자리를 잡으니깐요.

그리고 판독 작업 중에 영상은 멈추는데 소리는 계속 납니다. 둘 다 멈추는게 자연스러울 것 같습니다. 현재 어느 부분을 진행 중인지
보여주는 것도 좋을 것 같습니다.


2015-01-20 1:03 GMT+09:00 xylosper <notifications@github.com>:

**Comment by xylosper** [comment]
>  화면을 사등분하고 그 중 세군데 이상이 블랙인지 확인하면 어떨까요? 보통 방송사 로고가 네 귀퉁이 중 한 군데에 자리를 잡으니깐요.

이게 좋은 방법인지는 솔직히 모르겠습니다. 현재 판독 기준은 화면 전체 평균을 내서 일정값보다 밝기가 낮으면 검은 화면으로 판독하는 것이고, 올리신 화면보다 더 하얀 로고있는 화면 몇개 테스트 해본결과 문제가 없었기 때문에 그정도는 판독가능해야 한다고 말씀드린것이었습니다.

>  그리고 판독 작업 중에 영상은 멈추는데 소리는 계속 납니다. 둘 다 멈추는게 자연스러울 것 같습니다. 현재 어느 부분을 진행 중인지 보여주는 것도 좋을 것 같습니다.

보미는 인코더가 아니라 플레이어입니다. 소리가 나는 이유는 재생을 멈춘게 아니기 때문입니다. 재생하지 않고서 앞의 프레임 정보를 가져오는 방법은 없습니다. 대신 탐색중에는 볼륨을 0으로 하여 소리가 나지 않게해야겠네요. 중간 프레임을 보여주는건 작업중입니다.

**Comment by dontdieych** [comment]
그러면 제대로 동작한다고 했을 때, 현재 위치에서 블랙 프레임까지 기본 속도로 재생하는 시간과 같은 만큼의 시간 동안 기달려야 하는
건가요?
2015. 1. 20. 오전 1:59에 "xylosper" <notifications@github.com>님이 작성:

**Comment by xylosper** [comment]
아뇨. 찾을때까지 비디오는 타임스탬프가 제자리인거죠.

**Comment by xylosper** [comment]
싱크를 맞추지 않고 최대한 빠르게 비디오만 재생하고 있는 상황이라고 생각하시면 됩니다.

**Comment by xylosper** [comment]
확인해봤는데 잘 동작합니다. 혹시 하드웨어가속 켜둔 상태시면 끄고 다시해보시기 바랍니다.
그래서 해결되면 그래픽카드와 드라이버를 알려주세요.

**Comment by xylosper** [comment]
하드웨어가속관련해서 문제가 발견되어 수정하였습니다.
확인부탁드립니다.

**Comment by dontdieych** [comment]
말끔하게 잘 동작 합니다. 탐색 속도가 더 빨랐으면 하는 욕심은 생기네요. :smile: 

감사합니다.
