### ISSUE TITLE
Urlencoded URLs doesn't open when passed as a parameter

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/bomi#18]
If you pass urlencoded URL as a parameter to cmplayer (like when you click on an icon in Dolphin file manager), it won't be recognized as a valid URL, however it works from the "Load URL" dialog.
So:

`cmplayer --open ftp://serv.valdikss.org.ru:21/Anime/Higurashi%20No%20Naku%20Koro%20Ni/%5BExiled-Destiny%5D_When_They_Cry_Higurashi_Ep01_\(6B18F06D\).mkv` — doesn't work
`cmplayer --open "ftp://serv.valdikss.org.ru:21/Anime/Higurashi No Naku Koro Ni/[Exiled-Destiny]_When_They_Cry_Higurashi_Ep01_(6B18F06D).mkv"` — works

`Open → Load URL → paste urlencoded url` — works

**Comment by ValdikSS** [comment]
Sorry for reopening this bug, but right now i'm hitting somewhat similar bug. I can't play any files with spaces, like this one:
`http://wormtube.worms2d.info/vids/Best Games of the Season 3.mp4`
It doesn't work with both spaces and quoted spaces (%20)

**Comment by xylosper** [comment]
It seems something's wrong in mpv.
mpv can play 'ftp://serv.valdikss.org.ru:21/Anime/Higurashi No Naku Koro Ni/[Exiled-Destiny]_When_They_Cry_Higurashi_Ep01_(6B18F06D).mkv' but cannot play 'http://wormtube.worms2d.info/vids/Best Games of the Season 3.mp4' which is weird because both URL contain spaces.

I'll report this to mpv.

**Comment by ValdikSS** [comment]
Are you sure? mpv plays fine for me while cmplayer not. Maybe this is a regression in mpv, i'll check network dump later.

**Comment by xylosper** [comment]
When this issue opened, I thought I had to decode all percent encoding before hand over it to mpv. So currently, bomi always decodes all percent encoding even if you input percent encoded URL.
It seems that ftp and http do not follow same rule. ftp does not allow percent encoding and http has to use percent encoding.

**Comment by ValdikSS** [comment]
Hrmm, you're right. This is definitely a bug in mpv, it should play non-urlencoded URL. I'll fire a bug to their bugtracker. Thanks.

**Comment by ValdikSS** [comment]
You already did it. Thanks!

**Comment by xylosper** [comment]
I made a fix to percent-encode http/https URLs. Please test it.

**Comment by ValdikSS** [comment]
Works fine, thanks!
