### ISSUE TITLE
Bad audio playback

### ISSUE THREAD

**Issue by ViperScull** [xylosper/bomi#180]
Fresh install of bomi 0.9.0-1 under arch linux x64.
The pitch of the audio is lower than the original (looks like it is being played at a slower rate, but audio and video seemed synced) . Playback with mpv is correct. Tested with different videos (mp4).
Mpv uses pulse, bomi uses alsa. I tried with different output devices (auto, alsa/pulse and so on and it always uses alsa); there's no just pulse option.

Mpv output:
[stream] Video (+) --vid=1 (*) (h264)
[stream] Audio (+) --aid=1 --alang=und (*) (aac)
File tags:
 major_brand: mp42
 minor_version: 0
 compatible_brands: isommp42
 creation_time: 2014-11-30 20:00:08
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1280x646 yuv420p

bomi output:
[mpv/cplayer]  (+) Video --vid=1 (*) (h264)
[mpv/cplayer]  (+) Audio --aid=1 --alang=und (*) (aac)
[mpv/vf] Opening video filter: [noformat address=26612624 swdec_deint=Bob|1|OpenGL hwdec_deint=Bob|1|GPU]
[mpv/vd] Using software decoding.
[mpv/cplayer] AO: [alsa] 44100Hz stereo 2ch float
[mpv/cplayer] Setting vo cmd line to 'lscale=bilinear:cscale=bilinear:dither-depth=auto:dither=fruit:frame-queue-size=3:frame-drop-mode=clear:fancy-downscaling=no:sigmoid-upscaling=no:custom-shader=%320%const mat4 c_matrix = mat4(vec4(1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00),vec4(0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00),vec4(0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00),vec4(0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00)); vec4 custom_shader(vec4 color) { return c_matrix * color; }'.
[mpv/cplayer] VO: [opengl-cb] 1280x646 yuv420p

**Comment by xylosper** [comment]
> The pitch of the audio is lower than the original (looks like it is being played at a slower rate, but audio and video seemed synced) . Playback with mpv is correct. Tested with different videos (mp4).

What did you make think so? FYI, sample rate of renderer in playback information is inaccurate because of buffering.

> Mpv uses pulse, bomi uses alsa. I tried with different output devices (auto, alsa/pulse and so on and it always uses alsa); there's no just pulse option.

I missed an option to enable pulseaudio in AUR package. I uploaded new package, so update and try again.

**Comment by ViperScull** [comment]
I didn't mean it was actually being played at a slower rate but that it was the same feeling. Usually when you play something at a slower rate the pitch lowers.

I had not checked the redender data,  I have now, and it is indeed lower. Both fps and audio frequency. I don't know how to check it in mpv to confirm, but if you say that's normal because of the buffering I believe you.

>I missed an option to enable pulseaudio in AUR package. I uploaded new package, so update and try again.
It is present now, but the audio is still the same.

I have uploaded a piece of both audios so you can see the difference.
https://soundcloud.com/viper_scull/mpv
https://soundcloud.com/viper_scull/bomi

If there some tests or debugging that I could do, just let me know.

**Comment by xylosper** [comment]
Please post the log with with `--debug` option.

**Comment by xylosper** [comment]
I tested with your file. What you uploaded shows difference but, when I downloaded and played it in my PC, I cannot find difference. Check next:

* Is the playback speed 100%?
* Is the tempo scaler turned on?

**Comment by ViperScull** [comment]
It was the playback speed. It's weird cause I clicked on restore to defaults, and I thought that would correct all those attributes.
It's all ok now. Sorry for the wasted time.

**Comment by xylosper** [comment]
'Restore to defaults' restores options preferences, not playback state.
playback speed is not an option but state.
