### ISSUE TITLE
[Feature Request] Collapsible anchored panels

### ISSUE THREAD

**Issue by kehugter** [xylosper/bomi#186]
As an alternative to calling the playlist with `L` and the progress bar disappearing after some seconds, could them be anchored to the sides of the window and shown/hidden automatically when the mouse is close/far enough?

Potplayer has this behaviour by default. Although I like bomi's current design, for videos I personally prefer when panels get out of the way as soon as possible but remain easy to access . In this case, moving the mouse instead of having to look for the `L` key.

**Comment by xylosper** [comment]
First of all, you have to split the issue.

The progress bar is mainly maintained by skin.
If you want such progress bar, use other skin. For instance, recently added 'Breeze' skin is a such type of skin (which I call dock type skin).

The playlist also can be handled by skin, but for now, there's no skin which handles differently playlist, so this is about  changing default behavior. Of course it's possible, but it's quite annoying thing to some people(including me). So, instead, I'll add new options to choice the behavior.

**Comment by kehugter** [comment]
Skins, you're right! I went trough them just after installing, kept the default and completely forgot about it. I'm looking forward to the optional handling of playlists.

**Comment by xylosper** [comment]
I have two kind of idea to show playlist:

1. show a 'handle' to pull out playlist by cliicking when mouse cursor hovers at edge area. 
2. show playlist if mouse cursor hovers at edge area during certain time.

Also, to hide playlist again:

1. add a close button to playlist
2. hide playlist when mouse cursor gets out edge area.

Which one do you think better?

**Comment by xylosper** [comment]
Done.

* When mouse cursor hovers on the edge, playlist will be shown
* Once mouse cursor gets out from playlist, playslit will be hidden after some time delay

Thank you.

**Comment by kehugter** [comment]
Perfect, thanks a lot!
