### ISSUE TITLE
재생 도중에 가끔 디스크 접근을 하면서 툭툭 끊어집니다

### ISSUE THREAD

**Issue by dontdieych** [xylosper/bomi#187]
iotop 한쪽에 켜두고 끊길 때마다 쳐다 보니까 bomi가 순간적으로 30% 이상의 점유율을 보입니다. 10분 안팎?으로 이런 증상이 나타납니다.

전에는 이런 증상이 없었는데,

- bomi-git 0.9.0.r12.g08fd963-1 버전으로 업데이트. 그 전에는 cmplayer 0.8.17-1 사용 했었습니다.
- linux-ck 커널에서 linux 커널로 변경 - cpu 스케줄러 뿐만 아니라 io 스케줄러도 bfq에서 cfq로 바뀌었습니다.

ck 커널로 다시 써보면서 증상을 살펴볼 계획입니다.

**Comment by xylosper** [comment]
커널보다는 스케쥴러를 우선 바꿔보시는게 좋을 듯합니다.

**Comment by xylosper** [comment]
그리고 IO 성능에 문제가 있어보이면 캐쉬 설정을 해보시면 도움이 될 수도 있습니다.
