### ISSUE TITLE
Add screenshots to the site

### ISSUE THREAD

**Issue by Baldrs** [xylosper/bomi#188]
This player is a GUI application, so it will be a very good thing for the newcomers to have an idea how your program does look like before installing.

**Comment by seniorivn** [comment]
I agree, no one needs browser without screenshots. In addition, I would like to see a screenshot of a dark theme

**Comment by xylosper** [comment]
I agree, too. I'll post a screenshot after new version with new skin released.

**Comment by xylosper** [comment]
Added a gallery page. If you want some specific scenes, please let me know. Thank you.
