### ISSUE TITLE
Auto loading external audio

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#189]
Feature is present in MPC-HC.

Linux users unlike Windows ones can't switch to MPC-HC for TV series watch.

There can be 2 options in the settings:
1) Automaticly load external audio file
2) -- recursively
 Thank you.

**Comment by xylosper** [comment]
What is 'external audio'?

**Comment by swamp-fish** [comment]
For example in the same folder you have video.mp4 and video.mp3. If you want to watch a video file with different language that isn't inside *.mp4 file but external audio source you'd have to add it manually. MPC-HC(present on Windows only but its opensource so maybe it would possibl how they did it) already does that automaticly. Unfortunately no Linux player can do it.

**Comment by xylosper** [comment]
> Unfortunately no Linux player can do it.

That's not true. mpv (and, its ancestors, mplayer2, MPlayer) support it already.
Anyway, since mpv supports it, it will be easy to implement in bomi, I think.

Btw, what do you expect with 'recursively'? What should the player do recursively for audio file?

**Comment by swamp-fish** [comment]
I've used Smplayer with mplayer, mplayer2 and mpv - no player automaticly loaded external audio file.
By recursively i mean if the sound file isn't inside the same folder as video but in the next by hierarchy, example:
folder1 contains video.mp4, folder2 and folder3
folder2 contains video.mp3
folder3 contains video.mp3

So it would load both of those sound options for the same video file to chose from.

**Comment by xylosper** [comment]
Is the 'recursive' behavior really needed? Your example does not show typical recursive behavior.
It's just one-level down and I think it's enough. Please check the options about loading subtitle in preferences. Don't you think similar option for audio would be enough?

Recursive is very dangerous behavior especially, searching files because I/O can be easily stuck.

**Comment by swamp-fish** [comment]
Yes, i guess one level down is enough. Currently i am on old laptop and Bomi isn't loading here because OpenGL is lower than needed. So at the moment i can't say if those options look similiar enough. I could check it in 6-8 hours or so.

**Comment by swamp-fish** [comment]
Hi, yes, similar options for audio would be more then enough. Thank you.
Also, just for consistency of features right click could Audio menu could have the same option as Subtitles have: 
Open File(s)
Auto-load File(s)
Reload File(s)
Clear File(s)

**Comment by xylosper** [comment]
Done. Thank you for good suggestion!

**Comment by swamp-fish** [comment]
Wow, thank you! Could you please update your ppa(ppa:darklin20/bomi)?

**Comment by xylosper** [comment]
I'll update PPA once new version released. I think I can release it in few weeks.

**Comment by swamp-fish** [comment]
Ok, thanks.
