### ISSUE TITLE
yle-dl does not work

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#190]
It seems after yle-dl got updated to 2.5.0 it does not work any more.
yle-dl output:
http://pastebin.com/raw.php?i=RxNfmgFF

**Comment by xylosper** [comment]
I don't think this is an issue related with bomi. Please talk with yle-dl.

**Comment by ahjolinna** [comment]
@xylosper : this was the devs answer: "Looks like yle-dl for some reason selects a wrong downloader backend for you. You can force the old behavior with --protocol switch as follows:

yle-dl --protocol hds --pipe http://areena.yle.fi/tv/2409251 | mplayer -cache 1024 - "

**Comment by xylosper** [comment]
> .... it did't work

This should be fixed in yle-dl.
