### ISSUE TITLE
How can i enable multiple subtitles?

### ISSUE THREAD

**Issue by seniorivn** [xylosper/bomi#192]
when i choose "select all" it didn't choose anyone, when i choose any item in the subtitles list it choose this one, never more then one. so this function doesn't work for me.

**Comment by xylosper** [comment]
Internal subtitle tracks and ASS subs cannot be selected more than one.
Did you try non-ASS external subtitle files?

**Comment by seniorivn** [comment]
ok, thanks, it was internal subs, external works well.

**Comment by seniorivn** [comment]
is it possible to use multiple internal?

**Comment by xylosper** [comment]
Not possible. In fact, multiple internal subtitle doesn't make sense in most cases, because they're decoreated to be displayed a fixed position except some very simple srt ones.
