### ISSUE TITLE
Typo in home page

### ISSUE THREAD

**Issue by fisadev** [xylosper/bomi#195]
It says "Welcome to bomi proEJct page" :)
(could not find the page repo to send a pull request)

**Comment by xylosper** [comment]
Thank you! It's fixed.

The website repo is https://github.com/bomi-player/bomi-player.github.io .

The website is not reviewed thoroughly(more precisely, never reviewed) and futhermore, english is my second(in fact, it's third) language. So, if you can check typo, grammatical error, or bad expression, please do that and make pull request.
