### ISSUE TITLE
plugin or feature to find subtitles on special sites

### ISSUE THREAD

**Issue by seniorivn** [xylosper/bomi#196]
it's my everyday/week case, it's feature of KODI media center(xbmc). What i want: magic button to find all subtitles by name of video file on the subscene.com , opensubtitles.org and others.

**Comment by xylosper** [comment]
bomi already can find and download subtitles from opensubtitles.org.
Do you need other sites? subscene.com does not support public API unlike opensubtitles.org, this requires quite works.

**Comment by seniorivn** [comment]
Oh, sorry, but i can't find this option. If opensubtitles.org work fine of course i don't need more.

**Comment by xylosper** [comment]
It's under Tool menu (shorcut: CTRL+SHIFT+F).

**Comment by seniorivn** [comment]
Ok, thanks. It's awesome!
