### ISSUE TITLE
Window style set to Windows when disabling "hide the window..." on first launch

### ISSUE THREAD

**Issue by AladW** [xylosper/bomi#197]
Steps to reproduce:
1. delete ~/.config/xylosper (to simulate first launch)
2. Go to Tools > Preferences and uncheck "Hide the window rather than quit when closed"
3. Press "Apply"

The window style is now reset to Windows (from GTK+), without changing its respective option. Restoring the style to GTK+ solves the issue for subsequent launches.

Arch Linux x64, i3wm
bomi 0.9.0

**Comment by xylosper** [comment]
I can't reproduce this. Maybe GTK specific issue? Can you KDE?

**Comment by AladW** [comment]
With KDE 4 I can't reproduce it either... FWIW in i3, it's the same with Adwaita, Clearlooks or the Raleigh theme.

Not sure it helps (let me know if you want other output), but here's strace -e trace=open

http://pastebin.com/PaTdg4mV

**Comment by xylosper** [comment]
Does this still exist for 0.9.1?

**Comment by AladW** [comment]
Tested with 0.9.2, I can't reproduce this anymore, neither when I first change the (now default) Fusion to GTK+. Thanks!

**Comment by xylosper** [comment]
Thank for feedback
