### ISSUE TITLE
Inaccurate seeking

### ISSUE THREAD

**Issue by edison23** [xylosper/bomi#199]
I'm having serious problems with acuracy of seeking (or rather jumping) in a videos. I have seek steps set to 1 sec, 5 sec and 20 sec and sometimes e.g. the 1sec step jumps 2 seconds, sometimes even 10, which is kinda annoying. When I play the same parts of the same video in mpv, it seems to seek fairly accurately. When I looked where the keyframes in the video are, I found out Bomi jumps only on them, never between, which is very undersirable (at leas for me).

**Comment by xylosper** [comment]
I'll add option to activate accurate seeking.

**Comment by edison23** [comment]
Maybe a possibility to pass command-line argument to mpv would do?

**Comment by xylosper** [comment]
No option but there's an envrioment variable `BOMI_MPV_OPTIONS` to pass options.
In your case, you can launch bomi with `BOMI_MPV_OPTIONS="--hr-seek=yes" bomi`.

**Comment by edison23** [comment]
thanks, that works perfectly; however, an option in GUI would be nice anyway

**Comment by xylosper** [comment]
Done. Thank you!
