### ISSUE TITLE
Play remembered position when there is more then one file in playlist issue

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#201]
Resuming on the last remembered position is a good feature but for situations when there is more than 1 file it shouldn't work on the next file only the current playing.
For example there're 2 files in the playlist v_episode_1 and v_episode_2. But v_episode_2 was aleady opened at some point and it was closed somewhere in the middle, for example. And when someone will watch series from the start currently he'll watch second episode right from the middle.

Also it doesn't mean that all rememberd positions must be erased about all files from the playlist other than the current playing. Only when next file becomes current.

**Comment by xylosper** [comment]
> for situations when there is more than 1 file it shouldn't work on the next file only the current playing.

It SHOULD work. There's no reason whiy it SHOULDN'T work

> aleady opened at some point and it was closed somewhere in the middle

So, you've already seen that file, so bomi remembers. That's exactly what I intended.

If you want to see a file from start, you can use 'Seek > To the Beginning' menu (which is only available in latest git source yet).
If you think such behavior will be convenient for you, I can add an option for it.
But, the default behavior won't be changed.

**Comment by swamp-fish** [comment]
An option would be good as well. Thank you.

**Comment by xylosper** [comment]
Done. You can find it 'General > Play' tab in preferences. Thank you.
