### ISSUE TITLE
Aspect Ration not change 

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#202]
I'm using bomi-git-0.9.0.r54.g4daec0e-1-x86_64.pkg.tar, and i deleted all settings in xylosper folder, i have issue with changing aspect ration, when i want to change it not responding. it is allways original Aspect Ration.

**Comment by xylosper** [comment]
It seems that change is applied only after resizing. Can you check it applied after resizing?

**Comment by Kosava** [comment]
Still not work.

**Comment by Kosava** [comment]
Yea after resize it work.

**Comment by xylosper** [comment]
Fixed. Thank you!
