### ISSUE TITLE
sharpen/blur filters missing

### ISSUE THREAD

**Issue by jpyper** [xylosper/bomi#203]
CMPlayer had the ability to right click in the video window, go in Video menu -> Filters menu, then select Sharpen or Blur. From what I can tell by looking through the menus, this ability is no longer available in the Bomi Player.

Using the Sharpen filter was nice for blurry 480p or less DVD encoded anime/cartoon videos. It made a lot of the blurry videos look _almost_ Blu-Ray sharp and a lot easier on the eyes to watch.

I like testing and breaking things, so if you have a solution to this, I'm willing to try it out and give you back any broken parts. :)

Here's some of my system info. Hopefully it will help some. Please let me know if you need more info.

DISTRO:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

KERNEL (Canonical Mainline):
$ uname -a
Linux minime 3.15.0-031500rc2-generic #201404201435 SMP Sun Apr 20 18:36:18 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

BOMI INFO (Launchpad PPA darklin20):
$ bomi --version
[Translator] Cannot find translations for Qt, qt_en_US in /usr/share/qt5/translations
bomi 0.9.0

MPLAYER INFO (Launchpad PPA motumedia):
$ mplayer --version
Unknown option on the command line: --version
Error parsing option on the command line: --version
MPlayer2 2.0-701-gd4c5b7f-2ubuntu2 (C) 2000-2012 MPlayer Team

**Comment by xylosper** [comment]
Have you tried unsharp masking under 'Video > Interpolator'? I dropped blur/sharpen filters because obviously noone wants blur filter and I thought unsharp masking interpolator would be enough instead of sharpening filter

**Comment by jpyper** [comment]
Unsharp Masking (Radius:5) gets fairly close to the old Sharpen option, but it's not quite there. I guess it will have to do.

As for the old Blur option, I never used it, so that one I won't miss.

**Comment by xylosper** [comment]
Technically, unsharp masking with radius=5 is very similar with previous sharpening filter.
I think by tuning parameters, you can get more satisfactory result. I'm working on it now.

**Comment by xylosper** [comment]
Advanced setting dialog for interpolators is added.
You can adjust some parameters. Thanks.
