### ISSUE TITLE
Player doesn't honour prefered by default language of subtitles/audio

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#204]
For example i have language priorities in the settings for sound:
jap* (also tried jap, japanese)
orig*
eng*
ukr*
rus*

and for subtitles:
eng*
rus*
ru*

But it chooses either the first ones or the ones that were made default ones in the container.

**Comment by ValdikSS** [comment]
Works fine for me. I suppose regex is not supported there. You should use ISO country codes.

**Comment by xylosper** [comment]
Work fine. Are you sure the language is contained and noted the language in your file?
Also, priority list does support regular expression and does not support wild card.
So, `jap*` will match ja, jap, japp, jappp, japppp.... and so on. I think what you wanted is `ja.*`.

**Comment by swamp-fish** [comment]
I see, my bad ".*." did the trick and i've checked that some write "jpn" rather then "jap" as language.
It would be nice for you to add an example down there right after the text that says that regular expression is supported. With brackets, something like (example: ja.*.)

**Comment by xylosper** [comment]
> I see, my bad ".." did the trick

What trick? `ja..` will match four letter words which start with `ja` such as `ja12`, `jaab`, `ja&t`, `ja~1`, `jafg`, and so on. It won't match any words of `ja`, `jap`, `jpn`.

There's a description telling 'Regular expression is supprted.', literally.

**Comment by swamp-fish** [comment]
Nah i meant adding to the part where it says about that an example:
Regular expression is supported.(example: ja.* .)
I've had 2 problems there i didn't know that some write jpn as opposed to jap and i didn't know that there is a need to write .* . rather than just *

**Comment by xylosper** [comment]
The word 'regualr expression' tells everything. I don't think `ja.*` is a helpful example. Who don't know regex still doesn't understand it and who know regex knows what he should write without the example.
Who knows? Maybe someone who doesn't know regex take `ja.*` as a special expression to represent all japanese language code, as you thought that ja* would work for all japanese langaugae code.
If he/she doesn't know regex, they'll ask or find what it is and then he/she can learn something, like you asked here.
