### ISSUE TITLE
Leaving Preferences window issues

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#206]
If you go to the "preferences" during playback and then press "cancel" it just closes "preferences" window.
But if you press "ok" or "apply" (whether you changed something in the settings or not) it will close "preferences" window and reload all the settings including auto/manual loaded subtitles that will go away from the list and will result in a momentary video flickering when it will show blank player backround for a brief moment before starting playback.

**Comment by xylosper** [comment]
> But if you press "ok" or "apply" (whether you changed something in the settings or not) it will close "preferences" window and reload all the settings including auto/manual loaded subtitles that will go away from the list

Fixed.

> a momentary video flickering when it will show blank player backround for a brief moment before starting playback.

Is this issue, too?

**Comment by swamp-fish** [comment]
Thanks for fixing.
Flickering when you changed something in the preferences is ok, but if you didn't change anything then it should close the windows without one as if you're pressing Cancel. Which i presume works like that right now.

**Comment by xylosper** [comment]
> if you didn't change anything then it should close the windows without one as if you're pressing Cancel

Well, it would be better but it requires some changes in internal structure. It'll take some time.

**Comment by swamp-fish** [comment]
Well it is not an issue of high importancy. You've fixed the main problem.

**Comment by xylosper** [comment]
Fixed. Thank you.
