### ISSUE TITLE
Current position and length are broken

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/bomi#208]
Current position is always at 00:00:00 and video length is either 00:00:00 or 00:00:01
OSD works fine.

**Comment by xylosper** [comment]
There are several parts show position and length. Which one?
One screenshot would be perfect.

**Comment by ValdikSS** [comment]
That one in theme I suppose.
![screen78](https://cloud.githubusercontent.com/assets/3054729/6056929/bee612be-ad28-11e4-9e7b-1574ab0b4c28.png)

**Comment by xylosper** [comment]
Fixed. Thank you!
