### ISSUE TITLE
Skin Numix

### ISSUE THREAD

**Issue by freeniki** [xylosper/bomi#210]
![2015-02-05 23 26 05](https://cloud.githubusercontent.com/assets/8083855/6068600/65f5825a-ad8e-11e4-8c02-584429628cfb.png)

Autor: varlesh
License: Free
Based on Modern
Icons: Numix
Download: http://www.datafilehost.com/d/8cf2c476
Tested on bomi 0.9 in Ubuntu 14.04 (ppa:darklin20/bomi)

**Comment by xylosper** [comment]
Thank you again! Because some internal changes, made some fix in your code.
