### ISSUE TITLE
Anyone else got sometimes random close on next file in playlist?

### ISSUE THREAD

**Issue by DoTheEvo** [xylosper/bomi#213]
bomi sometimes closes itself suddenly when switching to a next file in the playlist
when run it in console to check outputs it just says core dump which happens in /var/lib/systemd/coredump
and close request with PID I think

Got it since the name switch from cmplayer to bomi
Switched back to cmplayer on AUR v0.8.17-1
this fixed the issue
I am on arch x64 + i3
files in the playlist are usually there because I have option to load all the files in the directory

**Comment by xylosper** [comment]
That... is too unspecific to fix something. When you said random, how frequently does it occur?
If it's enough to reproduce with several tries, please run bomi with --debug option and post the log. If you can post backtrace, it would be better. But, you have to enable debug option first in AUR package (which is commented out by default).

**Comment by DoTheEvo** [comment]
> When you said random, how frequently does it occur?

If I have a folder with same type of video files, like whole tv series, it never happens.
If theres bunch of videos files ranging from avi, wmv, flv, mp4,... to whatever theres like 75% chance that some of them will trigger the quit when switching to them, but can be played without a hitch if they are run as first.

>please run bomi with --debug option and post the log

I get this notification when I run it with it, but might not be a deal breaker
*[Engine] Debug property unavailable: Couldn't get property 'vo-drop-frame-count'.*

if by log you mean terminal output, here it is
http://pastebin.com/YpCgQx7T
http://pastebin.com/YTUGES0G
http://pastebin.com/haQtXp1w

if there are some log files being created I dont see them

>If you can post backtrace, it would be better.

I googled around what it is, trying gdp to open dump files is failing, using it like this
'''gdp /usr/bin/bomi /var/lib/systemd/coredump/core.bomi.1000.81c2d8daf42e42d69cfbd86c62add7c3.12082.1423398023000000.lz4'''

the core dump is freshly created by bomi runned with --debug flag

if I run bomi under gdp, first defining exec-file then runing it, it crashes after like 3 seconds
making some noises and with error decoding audio, mp1: header missing

>But, you have to enable debug option first in AUR package (which is commented out by default).

if you mean in PKGBUILD, then it seems it is enabled by default
[options=(debug !strip)](https://aur.archlinux.org/packages/bo/bomi/PKGBUILD)

**Comment by xylosper** [comment]
If you are trying `bomi` package, can you try `bomi-git` following next steps?

1. uncomment `options=(debug !strip)` in PKGBUILD
2. run bomi with `gdb bomi` and type `run --debug` in gdb console.
3. make it crash and type `bt full` in gdb console.
4. please post the entire logs.

**Comment by xylosper** [comment]
I've just made a commit to fix a crash issue. This also can be related with it, so please test try git package.

**Comment by DoTheEvo** [comment]
nope, the newest commit did not fixed the issue for me

here are two bt full reports, going according to your list

http://pastebin.com/4sukqkF4
http://pastebin.com/mxgR3FCG

heres one with also stuff before bt full
http://pastebin.com/7pNnWnVU

**Comment by xylosper** [comment]
Fixed. Please test and if it works, close this. Thank you!

**Comment by DoTheEvo** [comment]
Fixed Confirmed. THANKS
