### ISSUE TITLE
Subtitle encoding not work

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#220]
I'm using Arch Linux and bomi-git-0.9.1-1-x86_64.pkg.tar.xz , I'm deleted all previus files from xylosper folder, im unchecked Auto-Detect enconding when accuracy is above 70% , setup for CP1250 encoding and not work, when i check accuracy for 70% it work but if i want to change font size or soemthing it again not work... here is subtitle which make me problem http://www.4shared.com/office/QisUCT6gba/Big_Hero_6.html on smplayer work

**Comment by xylosper** [comment]
I cannot download because it's blocked by stupid goverment. Please send it to me by e-mail.

**Comment by Kosava** [comment]
OK it is sended.

**Comment by xylosper** [comment]
Fixed. Can you try git source?

**Comment by Kosava** [comment]
Now works fine thank you.

**Comment by xylosper** [comment]
You're welcome. Thank you.
