### ISSUE TITLE
Show time on mouse hover on the seek bar

### ISSUE THREAD

**Issue by notargets** [xylosper/bomi#221]
In players such as VLC or vanilla mpv, if you hover the mouse cursor on the seek bar it automatically shows you the time of the position it would jump to if you clicked. I would love to see this feature in bomi, too.

**Comment by xylosper** [comment]
Done. Depending on skin, target time will be displayed in tool tip or time text in skin. Thank you.

**Comment by notargets** [comment]
Thank you! Keep up the good work!
