### ISSUE TITLE
MKV chapter markers are no longer shown on seekbar

### ISSUE THREAD

**Issue by notargets** [xylosper/bomi#223]
In Bomi 0.9.0 the chapters of a Matroska file were marked on the seekbar, at least with the GaN skin. In 0.9.1, they are no longer there. Is it possible to bring them back, or at least make the visibility an option?

Edit: Actually they can be seen if the Ardis skin is being used, but not with the GaN skin.

**Comment by xylosper** [comment]
Fixed. Thank you!
