### ISSUE TITLE
Please revert playlist and history behaviour linked to mouse at the edge of the window.

### ISSUE THREAD

**Issue by bhrgunatha** [xylosper/bomi#224]
Previously to make the playlist or history appear we had to press L or C (those were the default values but the actual ketys could be changed.)  We still have that behaviour now and it's fine. The problem is recently the playlist appears whenever the mouse pointer is close to the right hand side of the window and the history appears when the mouse is near the left of the screen.

I'm not sure if this is a bug or by design, but it's really intrusive and annoying. There doesn't seem to be any way to stop it. 

If it's was a design decision to include the behaviour, can we please have an option to turn it off and just have the leyboard control it as it was before.

**Comment by xylosper** [comment]
You can turn it off in Skin & Style option.

**Comment by bhrgunatha** [comment]
Thanks for the quick reply - and sorry for being so dumb :( 
CMPlayer and now bomi has relpaced vlc for me as my main media player.
Thanks for all your hard work!

**Comment by xylosper** [comment]
never mind. abcense of documentation is my fault too.
