### ISSUE TITLE
"metro-skin" for windows port

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#229]
I notice that u are porting bomi to windows, I think "metro-skin" (or whatever M$ wants to call it) would be nice to have for win8-10...win7 supports ends this year so there is no point to make a skin for win7.

**Comment by xylosper** [comment]
What is metro-skin? If you mean the fullscreen app for window, I won't because I hate it.

**Comment by ahjolinna** [comment]
@xylosper : no, no... I was thinking more something that like this https://www.neowin.net/images/uploaded/screenshot.80712.1000000.jpg

**Comment by xylosper** [comment]
I can't see it. It seems the website blocked external link.

**Comment by ahjolinna** [comment]
well I uploaded it to my dropbox: https://dl.dropboxusercontent.com/u/64361252/screenshot.80712.1000000.jpg

**Comment by xylosper** [comment]
OKay, I'll do that later. Thank you.

**Comment by ahjolinna** [comment]
btw. how do u do debugin with windows?! and when do u think u will have the first version ready for testing? (that is somewhat stable)

**Comment by xylosper** [comment]
Nothing special. Just in the same way as in Linux.

About release, I'm planning to include window binary in next version or the next of next version release.

**Comment by ahjolinna** [comment]
what kind of installer will u use?

**Comment by xylosper** [comment]
Never considered yet. First release may contain only portable .zip.

**Comment by xylosper** [comment]
Where did you find the screenshot?
I have a problem to start this.
I cannot find icon set which is free from legal issue.

**Comment by ahjolinna** [comment]
http://www.neowin.net/news/videolan-team-to-get-fake-vlc-windows-8-app-removed-from-windows-store

this had metro icon set (metro skin for AIMP3) http://maverick07x.deviantart.com/art/metro-skin-for-AIMP3-286787367
other vlc metro skin: http://maverick07x.deviantart.com/art/VLC-MetroX-345256054

**Comment by xylosper** [comment]
I cannot find any reusable icon. What I need is not a skin file but actual resources I can use, and the license should be specified.

**Comment by ahjolinna** [comment]
@xylosper : I asked Kotus Works dev. if he could help with "metro-skin" and he said will look into it

**Comment by xylosper** [comment]
Oh, you really don't have to do that. I don't think this is important feature because lots of windows prefer something different from default style. Lots of popular players on windows do not even use default window frame.

**Comment by ahjolinna** [comment]
well it gives a good first impression that u have "native" look for windows...those small things matter for end users in the end

**Comment by xylosper** [comment]
As a matter of fact, it's not. They don't care about uniformity of look & feel. Lots of Windows users, at least around me, think it's out of style when they see native widgets. They even think the developer is too lazy or untrained to make a something different default one. It's not only about player. For instance, see the browsers. This is true even for the default browser internet explorer which doesn't share button icon with other default applications. Also, firefox and chrome have their own style and the users think what they're using looks better.

Because I can make a new skin easily with help of flexible QML, I can make a try. However, it's absolutely not worth to draw new icons to support native look on windows.

**Comment by ahjolinna** [comment]
I think that mentality has changed with the newer/next generation, because they have grown up with Android/iOS/WP..etc. and OC all the console (and other devices) have also unifying look on everything nowdays.

Also if u look what KDE guys are doing/planning with kf5/plasma5, it also will have unifying look...same goes with gnome/unity/cinnamon DE's... so yes "old" generation maybe don't care one way or another, newer might ..subconsciously at least.

But the question is that is this unifying look & feel just a temporary trend or not.

**Comment by xylosper** [comment]
Finally, done. Thank you.

**Comment by ahjolinna** [comment]
I know, I have seen it...I have been talking with Ivan from Kotus Works...I can't wait to try it out :P
