### ISSUE TITLE
mpv volume affects volume in bomi

### ISSUE THREAD

**Issue by notargets** [xylosper/bomi#230]
If I turn the volume down in mpv, the next time I run bomi the volume is turned down as well and I cannot increase it using the volume slider in bomi. Instead, I have to open something in mpv and restore the volume to 100% or use the system volume control in KDE.

The two players do not need to be running at the same time by the way.

**Comment by xylosper** [comment]
Which version do you use?
You are using pulse audio for audio output, right?
I have same issue and I talked with mpv dev(https://github.com/mpv-player/mpv/issues/1578) but still I couldn't find what's wrong.

**Comment by notargets** [comment]
I use mpv 0.7.3, bomi 0.9.2, and PulseAudio 5.0.

**Comment by xylosper** [comment]
Fixed. Thank you.
