### ISSUE TITLE
Subtitle explorer

### ISSUE THREAD

**Issue by notargets** [xylosper/bomi#231]
Is it possible to implement a subtitle explorer in bomi?

I mean a feature similar to what is found in two Windows players, KMPlayer and Daum PotPlayer. In other words, what I have in mind is a table that displays all the lines—the text and time codes—found in the current subtitle (and maybe you can switch between the subtitles by clicking on a tab), and when you double click on a line, the player jumps to where that line begins in the video.

**Comment by xylosper** [comment]
subtitle view is already included(SHIFT+V) but seeking is not possible.
I'll add it.

**Comment by notargets** [comment]
Oh, OK. I did not know it was already there. Thank you!

**Comment by xylosper** [comment]
Done. Thank you.
