### ISSUE TITLE
Subtitle not load 

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#232]
Subtitle not load in this file https://mega.co.nz/#!75p3ySbK!KMQT8chDDhpY48roECFCNDN2QkF_j9d3YYCo_3fR_84 There is video file which incule in that video file 3 titles. Serbian ASS file, Serbian SRT, and English SRT. non of this 3 not work, i use 
bomi-git-0.9.2.r22.gd82bfca-1-x86_64.pkg.tar.xz

**Comment by xylosper** [comment]
I can't reproduce your problem. Can you post `bomi --debug` log?

**Comment by Kosava** [comment]
Here is log http://pastebin.com/GZ1dmnTV
not work subtitle dont know why... i tryed to load all 3 not work

**Comment by xylosper** [comment]
Can you test same file with mpv? If you can, please try `mpv --msg-level=all=debug --sid=1 <filename>` and let me know the result.

**Comment by Kosava** [comment]
It work http://pastebin.com/3hWS7cwr it is not whole log it is too long

**Comment by xylosper** [comment]
I found similar issue and fixed it. I think your problem also fixed, too. Please test it.

**Comment by Kosava** [comment]
Now work thank you.
