### ISSUE TITLE
Please add option to ./configure to use system's mpv

### ISSUE THREAD

**Issue by s8321414** [xylosper/bomi#233]
As title says,please add option to ./configure to use system's mpv.

**Comment by xylosper** [comment]
Not possible. bomi needs its own customized one.

**Comment by xylosper** [comment]
I wrote an article about this. If you are interested, please read [wiki](https://github.com/xylosper/bomi/wiki/bomi-is-not-a-front-end)

**Comment by s8321414** [comment]
ah,OK,thanks for your response
