### ISSUE TITLE
Try it ;)

### ISSUE THREAD

**Issue by bob-art** [xylosper/bomi#235]
@xylosper
Seriously, it's not a problem, only try it:
sed -i 's/"\/\"/" \/\ "/' src/bomi/imports/bomi/TimeDuration.qml

...in my impression, it will look good on any skin =)

**Comment by xylosper** [comment]
You can specify spacing around '/' by `spacing` property in TimeDuration item. For instance, Ardis skin gives `spacing: 2`.

**Comment by bob-art** [comment]
Thank you, now i'll know =)
