### ISSUE TITLE
Check box in the FindSubtitle

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#236]
It would be neat to have checkbox in FindSubtitle to check languades to display, there is several similar languades, and when is checked to show only thats languade, or who know several languades to check it.

**Comment by xylosper** [comment]
Can you give me an example?

**Comment by larsjohnsen** [comment]
I would implement this as a "select multiple" (the Qt equivalent) in the options page, which would be used to filter what languages is shown when searching for subtitles.

**Comment by Kosava** [comment]
Thanks.

**Comment by xylosper** [comment]
Done. Thank you.
