### ISSUE TITLE
Subtitle Artifactes 

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#237]
Here is screenshot http://www.dodaj.rs/?2s/rn/1YNwCcWf/2015-02-18-0109201920x12.png

Artifactes from bomi player is in the cyrilic, it is cp1251, whole subtitle is in latin (cp1250), in the smplayer shows both regular.

https://dl.dropboxusercontent.com/u/9382990/The.Mentalist.S07E01.HDTV.x264-LOL-The.Mentalist.S07E01.720p.HDTV.X264-DIMENSION.srt

**Comment by larsjohnsen** [comment]
The subtitle displays fine for me when using default settings (UTF-8, auto-detect when accuracy > 70%). What is your settings (see Preferences -> Subtitle -> Load -> Encoding)?

**Comment by Kosava** [comment]
CP1250 encoding, and uncheked box for accuracy couse make mess with titles.

**Comment by xylosper** [comment]
The file is encoded in UTF-8. Select proper encoding.
