### ISSUE TITLE
icon does not show on plasma 5 menu

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#238]
I just installed netrunner 15 (work's really well) and I noticed that bomi icon does not show on menu but it does show on task manager...there is only a question mark icon instead, is this just a netrunner problem?

PS. I notice that netrunner 15 uses systemd already (kubuntu based)...I can't wait for the rolling version, it's arch/manjaro based :P

**Comment by xylosper** [comment]
Check the .desktop file installed right path. It depends on distro, for instacne Ubuntu use different path.

**Comment by ahjolinna** [comment]
It's ok...its there, and when I checked KDE Menu Editor I can see the icon also there, so the only place where I can't see is the menu's...and yes I tried both menus.

**Comment by xylosper** [comment]
In that case, please ask netrunner. In unbuntu/kubuntu, I checked the menu icon displayed well.

**Comment by ahjolinna** [comment]
okay scratch that...it was a plasma 5 problem.. reboot helped...really need to shutdown my PC more often :D ...okay there are some problems with plasma5, that it displays systemtray icon on the menu instead of the normal icon..its only some no idea why
