### ISSUE TITLE
Manually adjust subtitles' size and position

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#240]
Sometimes there is a need to quickly adjust size and position of subtitles. 
I know there is an option to change subtitles position in bomi (W and S buttons) but it never worked for me.
And currently there is no way to change their size manually.

**Comment by xylosper** [comment]
> Sometimes there is a need to quickly adjust size and position of subtitles. 

Can you give me more specific explanation about what's the case when is 'sometimes'?

> I know there is an option to change subtitles position in bomi (W and S buttons) but it never worked for me.

It's not an option but menu. What kind of subtitle did you try?

> And currently there is no way to change their size manually.

You can adjust it in preferences.

**Comment by swamp-fish** [comment]
When you're watching video and subtitles are either too small or too big, depending on your deaults in the preferences and dependig on what style they have you may to make them smaller/bigger because they take 3 rows. And you'd want to change such setting on the fly without interruption.

I tried to change position of ass ones, srt ones work but they're minority nowadays. Using Smplayer with mpv i can change position and size of both ass and srt. It would be nice to see those features here.

Also in the preferences they're no option to override ass subtitles settings and settings of height do not work on ass types.

**Comment by xylosper** [comment]
That's intentional because ass subtitles are supposed to be displayed a fixed style and position.

**Comment by swamp-fish** [comment]
From time to time i am seeing horrible styles in ass subtitles and overriding those settings helps alot.
Also changing size and positions with a few keys is super useful for all types of subtitles.

**Comment by xylosper** [comment]
Done. If you check 'Override ASS Style' in Subtitle menu, subtitle position and style will be applied to ASS subtitles too. Also you can adjust font scale through 'Subtitle Scale' menu.

**Comment by swamp-fish** [comment]
Oh wow, thanks.
