### ISSUE TITLE
Loosing focus on mouse click in full screen

### ISSUE THREAD

**Issue by zoli** [xylosper/bomi#241]
In arch linux using gnome with 2 monitors. This is how this bug is reproduced:
- Make bomi full screen in one of monitors
- Click on the other monitor screen so bomi looses focus
- On clicking back on bomi for gaining focus, The app below bomi gets focus and comes to front

**Comment by xylosper** [comment]
I can't test it because I don't have additional monitors.

> On clicking back on bomi for gaining focus, The app below bomi gets focus and comes to front

Can you get the lost focus back by, for instance alt+tab or selecting in task bar?

**Comment by zoli** [comment]
Yes after alt+tab i can get the lost focus back. After some digging it seems bomi isn't catching mouse events at all in this situation.

**Comment by xylosper** [comment]
Try this:

1. Select Window > Stays on Top > Off
2. Make it full screen and test

1. Select Window > Stays on Top > Off
2. Make it full screen through task bar (not double clicking) and test

Please let me know the results.

**Comment by xylosper** [comment]
Also, can you check other players?

**Comment by zoli** [comment]
The bug is still happening, Yes I checked this with mpv and vlc they both worked fine.

**Comment by zoli** [comment]
Maybe this is related to [mpv #1217](https://github.com/mpv-player/mpv/issues/1217)?

**Comment by xylosper** [comment]
It could be. I sent a test program by e-mail to you. Please test and let me know the result.

**Comment by xylosper** [comment]
Also, please test in other WM/DE. If it works in others, defintely gnome bug.

**Comment by zoli** [comment]
The program you sent works fine the bug doesn't happen. Also another thing maybe helpful when there is no video playing in bomi and it's just showing the logo this problem doesn't occur in full screen mode.

**Comment by xylosper** [comment]
In that case, disabling stays on top should've work....
Can you follow next again?

1. Select Window > Stays on Top > Off
2. Turn bomi off and execute again
3. Test fullscreen

**Comment by zoli** [comment]
Tested again doesn't work.

**Comment by xylosper** [comment]
Btw, which version do you use?

**Comment by xylosper** [comment]
I borrowed a laptop and tested in KDE but I cannot find any problem. I'd like to test in gnome but I couldn't because it wasn't mine. Can you check in other WM/DE?

**Comment by zoli** [comment]
I tested on version 0.9.2-3 also tested with the latest master branch git repo. I will look into mpv code as i suspect it's from mpv.

**Comment by ahjolinna** [comment]
I never had this problem with KDE (kde4 or kf5)... I have always used 2 monitors

**Comment by zoli** [comment]
Tested on kde works fine, it seems related to gnome

**Comment by meteque1902** [comment]
Did you find a solution (or a workarround)? It's very annoying. I have also Arch with Gnome but I've been using Awesome, so I don't know if it's a bug of this version.

**Comment by zoli** [comment]
I found that most likely the problem is with gnome & x11, looking forward if there is any solution, patch or claimed issue. I will try to create a patch if there isn't any patch submitted yet.

**Comment by xylosper** [comment]
https://bbs.archlinux.org/viewtopic.php?id=192304
Does this help you?

**Comment by zoli** [comment]
@xylosper Thanks, on sloppy focus I can get focus on bomi by moving the cursor on bomi but clicking still goes through the window because gnome X11 is catching mouse move event but not the click event.

**Comment by xylosper** [comment]
It seems there are three types of focus mode, sloppy, mouse, click. None of them works for you?

**Comment by zoli** [comment]
No the clicking problem still exists on all of them however this isn't bomi or mpv issue.

**Comment by zoli** [comment]
Closing this as it's not related to bomi.
