### ISSUE TITLE
Frame number in OSD

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/bomi#243]
Hello!
Is it possible to add frame number in an informational OSD? I'm writing avisynth scripts which are bound to frames and it would be very convenient.
Thanks.

**Comment by xylosper** [comment]
It depends on how you define 'frame number'.
It's possible to display a 'guess' calculated from fps and pts.

**Comment by ValdikSS** [comment]
pts number from the beginning of file I believe.

**Comment by xylosper** [comment]
What is 'pts number'? If you're talking about pts itself, it's totally different thing from 'frame number'.
pts is a timestamp when a frame should be presented, and usually, it's close to the current playing time position when a frame is displayed.

**Comment by ValdikSS** [comment]
pts number is just a number of processed frames with ptses from the beginning of file. How does ffmpeg counts frame numbers (%{n} variable in filters)?

**Comment by xylosper** [comment]
Here's the difference between encoder and player.
Encoder just scans all frames, so it can count frames exactly.
A player does not work so. A player should be able to seek to an arbitary point in the stream and in that case, there's no way to figure out exact frame count at the seeked point. The only way to figure out is scan all data from the beginning whenever seeked which is totally nonsense for a player.

**Comment by ValdikSS** [comment]
You're right.

**Comment by xylosper** [comment]
I don't know this is still useful for you, I just committed to add estimated frame number in playback information anyway becuase it's not difficult.

**Comment by ValdikSS** [comment]
Ok thanks!
