### ISSUE TITLE
Evolution : subtitles sync 

### ISSUE THREAD

**Issue by camembert7** [xylosper/bomi#245]
One wonderful feature, present in smplayer could be an improvement for bomi:
* One key to jump to the next subtitle in the sub file (Y in smplayer)
* One key to jump to the previous subtitle (G in smplayer)

Synchronizing your subs becomes easy! You don't have to shift your sub sync on and on until your find the line you are looking for (difference between the video you are watching and the sub file, for example when there is the channel annoucement), it directly jumps to the next line of dialogue, even if there is a 8 seconds gap.
Thank you!

**Comment by Kosava** [comment]
Truee this feature will much make easyer life, with some bad timed subtitles.

**Comment by xylosper** [comment]
This is easy. But, I don't think the expression 'jump to ... ' is good because it may make user think it will cause a seek(jump) of playback.
I'm thinking 'bring previous/next subtitle' for the menu text.

**Comment by camembert7** [comment]
You're right, the name may not be adapted.
Actually, smplayer says : 
"y and g Step forward/backward in the subtitle list"
But your text is also valid.
Thanks for being ready to do the evolution! That's the last feature I miss to be soooo happy with bomi
Cheers

**Comment by xylosper** [comment]
Done. Default shotcuts are shift+left/shift+right. Thank you.

**Comment by camembert7** [comment]
thank YOU!
