### ISSUE TITLE
External subtitles instead of the video's subtitles

### ISSUE THREAD

**Issue by camembert7** [xylosper/bomi#248]
Hello,
I don't know if I use that right, but I suspect there is a bug in the video embedded subtitles handling.
I cannot deactivate the embedded video subtitle and activate the external one (from a file). Each time, the embedded sub stays visible. If I chosse "hide", all subtitles disappear altogether. Clicking on the subtitle line alone doesn't make it disappear.
I am using bomi 0.9.2-3 from Arch-AUR.
Thanks

**Comment by xylosper** [comment]
Fixed. Thank you!

**Comment by camembert7** [comment]
You're welcome.
