### ISSUE TITLE
Taking snapshot on windows build.

### ISSUE THREAD

**Issue by AsukaLangleyfag** [xylosper/bomi#251]
First issue: taking snapshots pretty laggy (only for this build, no problems with mpv and SMPlayer with mpv on win and with breed-808's build for Fedora)
Second issue: taking snapshot without subs do the same thing as taking snapshots with them. mpv's official windows build doesn't have this problem, and breed-808's build doesn't have this too.
Oh, my OS is 64-bit Windows 10 Technical Preview.

**Comment by xylosper** [comment]
I confirmed that the bug exsits in 0.9.3. Now working.

**Comment by xylosper** [comment]
Fixed. Thank you!
