### ISSUE TITLE
Crash when opening some videos with multiple audio tracks

### ISSUE THREAD

**Issue by notargets** [xylosper/bomi#252]
Bomi 0.9.3 crashes when I try to open a few videos with more than one audio track. I do not know what causes the problem, but I will try to report as much information as I can.

This is the trace log I get: http://pastebin.com/qzQGh9EB

In terminal, I get a segmentation error when trace logging to text file is enabled through preferences. When it is disabled, I get the following in the terminal:

```
bomi: ../audio/filter/af.c:782: af_add_output_frame: Assertion `mp_audio_config_equals(&af->fmt_out, frame)' failed.
Aborted (core dumped)
```

**Comment by xylosper** [comment]
Can you provide a sample file?
Also, usually, you don't have to enable 'trace' level. 'debug' level would be enough.
Please try `bomi --log-level=debug` and post the crash log.

**Comment by notargets** [comment]
Oh, sorry about that. Here is the debugging log: http://pastebin.com/UkWB3wdY

And here is a few-second-long clip cut out with avidemux from a video bomi crashes with:
https://drive.google.com/file/d/0B1y42vbEmRaoX1BBSmtKbHpXMm8/view?usp=sharing
I can reproduce the issue with this file, too, so I hope it will be enough.

**Comment by xylosper** [comment]
Can't reproduce your problem. Audio environment is more fragmentized than video environment.
Are you sure your log is complete? Your log is ended with `(D)[mpv/demux] Trying demuxer: rawvideo (force-level: normal)`.

**Comment by notargets** [comment]
It looks like if I run `bomi --log-level=debug --debug > ~/bomi.log` instead of `bomi --log-level=debug`, the last lines are different:

```
(D)[mpv/demux] Trying demuxer: mkv (force-level: normal)
(D)[mpv/mkv] Found the head...
(D)[mpv/mkv] + a segment...
(D)[mpv/mkv] /---- [ parsing seek head ] ---------
(D)[mpv/mkv] \---- [ parsing seek head ] ---------
(D)[mpv/mkv] |+ segment information...
(D)[mpv/mkv] | + timecode scale: 1000000
(D)[mpv/mkv] | + duration: 9.134s
(D)[mpv/mkv] | + segment uid 1a 14 a0 74 d5 42 64 a8 e2 e5 33 c6 83 49 56 40
(D)[mpv/mkv] |+ segment tracks...
(W)[mpv/mkv] Error parsing element Tracks
(D)[mpv/mkv] | + a track...
(D)[mpv/mkv] |  + Track number: 1
(D)[mpv/mkv] |  + Track type: Video
(D)[mpv/mkv] |  + Video track
(D)[mpv/mkv] |   + Pixel width: 1280
(D)[mpv/mkv] |   + Pixel height: 688
(D)[mpv/mkv] |  + Codec ID: V_MPEG4/ISO/AVC
(D)[mpv/mkv] |  + CodecPrivate, length 39
(D)[mpv/mkv] |  + Language: und
```

I posted the full log here: http://pastebin.com/SmdYLaSB

**Comment by xylosper** [comment]
Hmm, it's still not useful...
Can you post systemd log?
You can get the logs by `journalctl -b _COMM=bomi` for all logs since last boot, or `journalctl -since=today _COMM=bomi` for all logs for during today(or set -since=yesterday if crashed yesterday).

**Comment by notargets** [comment]
Here's the systemd log, but I'm afraid it may still not be useful because it looks very similar to the previous one to my eyes: http://pastebin.com/M3jnFgUk

**Comment by xylosper** [comment]
Your log terminated while opening demuxer.
There's really nothing I can do in that stage.
Can you check if original mpv or other players work?

**Comment by notargets** [comment]
Yes, both mpv and VLC can open it without problems.

**Comment by xylosper** [comment]
Thank you. Can you try mpv-git package?

**Comment by notargets** [comment]
I've tried compiling several times in the past few days as shown [here] (https://github.com/mpv-player/mpv-build), but when I issue the `./rebuild -j4`, it takes forever for "Receiving objects" to complete (slow download speed). I only tried mpv-build because I don't know how to compile mpv.

**Comment by xylosper** [comment]
Oh, it's very easy. Just clone mpv git repository and run waf. For instance, in your home directory, run next:

```
$ git clone --depth=1 https://github.com/mpv-player/mpv.git mpv-git
$ cd mpv-git
$ ./bootstrap.py
$ ./waf configure
$ ./waf
```

Then your new executable will be created at `~/mpv-git/build/mpv`.
So, test it, e.g.,
```
~/mpv-git/build/mpv --vo=opengl-hq <your-vieo-file>
```

**Comment by notargets** [comment]
Thank you for the instructions, I've got it now!

mpv-git seems to be working fine with the files.

**Comment by xylosper** [comment]
Does this problem still exists in 0.9.10?

**Comment by notargets** [comment]
No, fortunately, it now plays all the files that used to be problematic.

**Comment by xylosper** [comment]
Glad to hear that. Thank you for testing.
