### ISSUE TITLE
Screensaver Windows

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#253]
I see you realased windows version, and strarted to test, screensaver start when videos is playing

**Comment by xylosper** [comment]
> screensaver start when videos is playing

Does screensaver start whenver you start video?

**Comment by xylosper** [comment]
I changed the method to disable screensaver on windows.
I think it's difficult to compile git source by yourself, please test it later when next version released.

**Comment by Kosava** [comment]
Tested, and now work.

Thank you

**Comment by xylosper** [comment]
Good. Thanks.
