### ISSUE TITLE
ASS subtitles min/max positions and letterbox don't work

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#255]
Currently we can adjust srt sub. positions to the point where video/letterbox ends. However with "Override ASS Style" option enabled positioning ass subs can go to the very down/up, there is a limit.
And we can't place those subtitles in the letterbox.

**Comment by xylosper** [comment]
This is done except one thing.
It's not possible to remove bottom margin of ASS subtitle.
It seems restriction of libass.

**Comment by swamp-fish** [comment]
I see, thanks.
