### ISSUE TITLE
Changing size and positiion of ass subtitles without enabling "Override ASS Style" option.

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#256]
In my opinion it should work as it is for every type of subtitles, its natural for the user. I thought "Override ASS Style" option would apply only to style.

**Comment by xylosper** [comment]
'ASS Style' includes positioning and scale defined by ASS subtitle.
Also, any feature which might break something cannot be default one.
ASS subtitles are not supposed to be changed the given style and overriding ASS style can break ASS rendering.

**Comment by swamp-fish** [comment]
Ok, then how about two options? One to change only style and the other to override position and and scale?

**Comment by xylosper** [comment]
That would be acceptable but still, it won't be turned on by default.

**Comment by xylosper** [comment]
Oh, and 'scale' cannot be separated from bomi's subtitle style because that menu just overrides the font size in preferences.
position can be separated.

**Comment by xylosper** [comment]
Done. Also, changed behavior of  subtitle scale to apply scale to ass, too.
It was adjusted font size directly(3% + 1%->4%), but now it actually scales up/down font size(3%+1%->3.01%).

**Comment by swamp-fish** [comment]
Thanks.
