### ISSUE TITLE
Option "Use external command"

### ISSUE THREAD

**Issue by bob-art** [xylosper/bomi#257]
@xylosper 
Hi! Please, return option "Use external command" for disable screensaver in preferences. 
It was a very convenient option! And i'm hope, that it will be useful not only to me. 
Once again, please, return it!

Current version - bomi 0.9.3-1

**Comment by xylosper** [comment]
Why do you need this? Disabling ss doesn't work for you?

**Comment by bob-art** [comment]
xylosper, the fact, that i like to use for screensaver in KDE is "xset [options]" - it works is fine, but not for bomi, therefore, separately for bomi i use: 
"qdbus org.kde.screensaver /ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity"
- at the same time, me do not need to have KDE Power Management service in autostart.
For me preferred it would be used for a "global" screensaver is xset as a utility independent of the current Desktop Environment, but with selectable commands within any particular program, in this case - it's your program =)
But, if your position is principled about the "external command" - well, your right, you are the master of its code.

**Comment by xylosper** [comment]
So, you disabled screensaver by KDE and you are using xset instead?
Internally, bomi tries in next order:

1. org.gnome.SessionManager /org/gnome/SessionManager org.gnome.SessionManager.Inhibit
2. org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.Inhibit
3. XScreenSaver

XScreenSaver can work with xset so, I think to exposure above choices to preferences whould be fine for you.

**Comment by bob-art** [comment]
xylosper, XScreenSaver is working, i know, but i do not use it =)
If you use a ... 1, 2, 3 commands, what prevents use and this?

  4. qdbus org.kde.screensaver /ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity

**Comment by xylosper** [comment]
You said you're using `xset`. It means you're using XScreenSaver.

**Comment by bob-art** [comment]
if we are talking about xscreensaver - no, i don't use it.

**Comment by xylosper** [comment]
I'm talking about Xlib functions which `xset` calls.
For instance, `xset s reset` calls `XResetScreensaver()`.

**Comment by xylosper** [comment]
I added option to choice method to disable screensaver.
Please try  XScreenSaver.

**Comment by bob-art** [comment]
Thank you, i will check and report the result a bit later. 
I understand that this option was added to the bomi-git version?
In any case, let's will close this problem =)

**Comment by bob-art** [comment]
Thank you!
I installed bomi-git and checked it: screen does not turn Off, if i choose "XScreenSaver".
Only one question remains: if bomi enumerates different methods to disable the screensaver, why it did not work on bomi 0.9.3-1 and before?

**Comment by xylosper** [comment]
No, it doesn't enumerate. It detects what method is available and once found, use the method. Because you're using KDE which supports freedesktop screensaver dbus interface, bomi detects that the interface exits and works. However, you don't let KDE control screensaver and control screensaver through xset.

**Comment by bob-art** [comment]
Thank you. Issue is closed.
