### ISSUE TITLE
Skin "native" - control panel and status line disappeared after exiting from full-screen mode

### ISSUE THREAD

**Issue by vladimiry** [xylosper/bomi#259]
Version 0.9.3, there was no such issue for previous version 0.9.2.

Start playing in non full-screen mode, controls panel is displayed
![controls-ok](https://cloud.githubusercontent.com/assets/1560781/6547030/e1d6bd3e-c5db-11e4-9253-ed122fa3d73f.png)
Turn to full-screen and exit back to windowed mode, controls panel and status line is disappeared
![controls-disappeared](https://cloud.githubusercontent.com/assets/1560781/6547032/fef91c7c-c5db-11e4-8161-e13bf74326ed.png)
Application restarting helps to get control panel back in window mode. In full-screen mode it's still possible to use control panel by hovering mouse to the bottom of the screen.

**Comment by xylosper** [comment]
It's already fixed at https://github.com/xylosper/bomi/commit/2bae21c2e0f29367d876e0a5b26249b1c22bd976.
