### ISSUE TITLE
Doesn't remember windowed size after you finished to watch a video in fullscreen

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#261]
If you uncheck an option in the preferences "Resize to video resolution in windowed-mode when video is changed" Bomi remembers the window size. But if you go into fullscreen mode and end up watching video there it will remember the last window size as fullscreen and once you go out of it you won't get windowed mode size.
Could it also remember the size of last windowed mode?

**Comment by xylosper** [comment]
Done. Thank you.
