### ISSUE TITLE
Playlist and Subtitlefinder

### ISSUE THREAD

**Issue by Kosava** [xylosper/bomi#262]
When next video starts and when i want to search subtitle in subtitle finder, subtitle not fetch any subtitle it come to 50%, solution was to turn off bomi and again fetch subitles and appear, this problem is not constant, it sometimes come sometimes not, but in most cases there is nothing fetching for next video.

**Comment by xylosper** [comment]
Wrong value '50%' for progress is fixed.
I cannot reproduce downloading disabled. Can you re-check the problem still exists?

**Comment by Kosava** [comment]
I tested it, and it seams work just fine.
Thanks.
