### ISSUE TITLE
Show floating panel only when mouse moved nearby

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#264]
An option(s) in the preferences. If checked it will show floating panel when mouse pointer is moved right to it (since some themes have free floating control that you can place anywhere), up or/and down of the video(or/and close border of the floating panel).
If its too much just Up and Down would be helpful, thanks.

**Comment by xylosper** [comment]
> Show floating panel only when mouse moved nearby

This is nonsense.
This requires you to **remember** where the panel was located because it's invisible.
Why don't you just use non-floating type skin, if it's obstructive to you?

**Comment by swamp-fish** [comment]
Actually its not really something thats hard to remember and is not supposed to be default behavior just an option in the preferences.
Anyway just up and bottom of the visible area would be nice, just like non-floating type skin can do but for up region as well.

**Comment by xylosper** [comment]
Why don't you just use non floating type skin?

**Comment by swamp-fish** [comment]
Because i like the style of GaN theme and i like to keep it at the top.
If that is too troublesome could you add an option to show/hide a panel and to make it possible to assign not just for keyboard button but for mouse button as well?

**Comment by xylosper** [comment]
Which one is purpose of your suggestion?

1. Show controls only if enforced
2. Hide controls only if enforced

**Comment by swamp-fish** [comment]
The second one. Default one should stay as it is right now and so when you need to hide it you press a button to hide controls.

**Comment by xylosper** [comment]
In that case, what about not hiding controls while the cursor is inside of floating panel?

**Comment by swamp-fish** [comment]
Seems ok, i guess everyone woud expect for control to stay if you hover over with a mouse.

**Comment by xylosper** [comment]
I agree and it's implemented at df956df1ce48da6f5e682ab0f606c2974b0a7dec.

**Comment by xylosper** [comment]
Have you tried? Not hiding for mouseover is included in 0.9.5.

**Comment by swamp-fish** [comment]
Controls aren't hide on mouse over yes. But what about a way to actually hide them with key combination or mouse button? As of right now for floating skins if your mouse move in a ny direction it controls are shown right away. You don't even need to assign default key combinationso that people wouldn't accidentally hit those.

**Comment by xylosper** [comment]
At the very first time, why do you need to show/hide it manually?
I'm asking this because I want to know what makes you do so and it may help to improve skin design.

**Comment by swamp-fish** [comment]
Wait, have you added an option to hide controls automaticly unless you move mous nearby? If so then it doesn't work. 
I suggested to make it manual because i believe it would be easier to code but if it will be automatic like with static controls then that would be even better.

**Comment by xylosper** [comment]
> Wait, have you added an option to hide controls automaticly unless you move mous nearby? If so then it doesn't work. 

No I didn't.

> I suggested to make it manual because i believe it would be easier to code but if it will be automatic like with static controls then that would be even better.

Yes, it's much easier to implemt manual one than automatic one.

I'm asking why you need such behavior.
For instance, do you think floating control is obstructive? Or, do you think the timeout is too short?

**Comment by swamp-fish** [comment]
Because sometimes either mouse pointer moves by itself or someone can move it unintentionally slightly. And this results in controls showing up. This is the same reason you implemented it for static controls.

**Comment by xylosper** [comment]
You will see an option 'Show hidden controls whever mouse moved' which is checked by default in next version.
If you uncheck the option, the skin behaves as what you want, I think.

**Comment by swamp-fish** [comment]
Thank you.

**Comment by xylosper** [comment]
New version released. Please test it.

**Comment by swamp-fish** [comment]
Hi, tested it, its working, thank you

**Comment by xylosper** [comment]
Thanks.
