### ISSUE TITLE
Bug drawing interface on Gnome-Shell

### ISSUE THREAD

**Issue by varlesh** [xylosper/bomi#265]
If you switch to fullscreen mode and back again , you can not see the panel.
![2015-03-14 14 39 55](https://cloud.githubusercontent.com/assets/8083855/6651535/2f01db2c-ca58-11e4-951b-b32f380a3370.png)
Please see video: http://youtu.be/OZY_KxOv6GE
OS: Manjaro x86_64
DE: Gnome-Shell 3.14.3
GTK3: 3.14.9
GTK2: 2.24.27
bomi: 0.9.3

**Comment by xylosper** [comment]
This is already fixed.

**Comment by varlesh** [comment]
Thx ))
