### ISSUE TITLE
Is it possible to use bomi on Mac OS X?

### ISSUE THREAD

**Issue by seniorivn** [xylosper/bomi#268]
Mac version?

**Comment by xylosper** [comment]
It was till 0.8.17 but disabled after my mac broken.

**Comment by seniorivn** [comment]
so if somebody will test it on mac, it will possible?

**Comment by xylosper** [comment]
Current source cannot even be compiled in Mac because OS dependent part for Mac is not maintained.

**Comment by seniorivn** [comment]
ok, thanks
