### ISSUE TITLE
Ability to recursively add sub folders.

### ISSUE THREAD

**Issue by shaggytwodope** [xylosper/bomi#271]
I can not seem to find a way to add multiple files in sub folders, is this possible and I'm simply missing something?

**Comment by xylosper** [comment]
Why do you need to add sub folders recursively?
For now, you can specify subtitle folders non-recursively in 'Subtitle > Load' tab in Preferences.

**Comment by shaggytwodope** [comment]
I said this wrong, I meant to say add or play files in multiple sub folders.

**Comment by xylosper** [comment]
If what I said is not what you want, would you explain what you're looking for?

**Comment by shaggytwodope** [comment]
Want to be able to play alot of videos at once, and alot of them are in sub folders to keep organized. Any way I add files to the play list, it doesnt look in sub folders for video files.

**Comment by xylosper** [comment]
Can you explain more detail?
Did you set subtitle folder in preferences? If you did, what you did?
Can you tell me the directory structure of your organized folders?

**Comment by shaggytwodope** [comment]
I must not be explaining myself well at all and sorry about that.  I want to play alot of videos in different folders. Is there a way to queue up video files in different folders or "sub folders" such as:

├── Tv Shows
         ├── The Big Bang Theory
                   │   ├── The.Big.Bang.Theory.S01
                   │   ├── The.Big.Bang.Theory.S02
         ├── Friends
                   │   ├── Friends.S01
                   │   ├── Friends.S02

I want to be able to play everything in "Tv Shows" But for some reason when i try to add folders it doesn't add anything unless that folder I add has media in it (.mp4 .avi etc)

**Comment by xylosper** [comment]
Now I got it. You meant 'subfolder' not 'sub folder'.

**Comment by xylosper** [comment]
Done. Thank you!

**Comment by shaggytwodope** [comment]
Your awesome, thank you. For the record It adds over 11,000 files in seconds with no lag. Best video player ever used.
