### ISSUE TITLE
link failure (vdpau related)

### ISSUE THREAD

**Issue by ff2000** [xylosper/bomi#274]
<...>/bomi/src/mpv/build/../video/decode/vdpau.c:160: undefined reference to `av_vdpau_alloc_context'

libvdpau-0.9 is installed.

**Comment by xylosper** [comment]
Check your ffmpeg version is 2.4 or higher.

**Comment by ff2000** [comment]
It's ffmpeg-2.6.1.

**Comment by xylosper** [comment]
I think you disabled vdpau support in ffmpeg, don't you?

**Comment by xylosper** [comment]
Yeah, that's the problem. This will be fixed by your another issue (#273).
