### ISSUE TITLE
extremely large pref.json

### ISSUE THREAD

**Issue by ff2000** [xylosper/bomi#275]
It has 103028 lines and needs nearly 2 MB on disk.
channel_manipulation seems to make up for the most of the lines.
Is that really needed? Here it looks like most of the entries are simply empty.

**Comment by xylosper** [comment]
By eliminating whitespaces and line breaks, it can be more compressed.
But, why do you care? 2MB is NOT extremely large.
For instance, a subtitle file is about 50~100kB more or less.
2MB is equivalent to approximately only 20~40 sub files.

**Comment by ff2000** [comment]
> By eliminating whitespaces and line breaks, it can be more compressed.
> But, why do you care? 2MB is NOT extremely large.
I wanted to manually change the timeout to hide the cursor - 3sec for my taste is too large and the control in the preferences dialog is set inactive.
And going through the config was a pain ;)

But the main reason I reported this was cause I thought it was a bug. If it is normal I can live with the size. So you can close this issue as invalid if you like to.

But I think it probably could make things easier to store those channel settings in seperate files. Even with a preferences dialog it happens from time to time that you need to edit te config by hand and not every editor can cope with such large files liek vim does.
Compression would be great, too.

> For instance, a subtitle file is about 50~100kB more or less.
> 2MB is equivalent to approximately only 20~40 sub files.
I do not have seperate subtile files, they all are bundled in my mkv's :)

**Comment by xylosper** [comment]
> I wanted to manually change the timeout to hide the cursor - 3sec for my taste is too large and the control in the preferences dialog is set inactive.

In that case, you'd better make a bug report because it was a bug and it's fixed now.

> Compression would be great, too.

Now channel manipulation item saved in compact string instead of raw json array.

> I do not have seperate subtile files, they all are bundled in my mkv's :)

Well, that's why I said 'for instance'.

Anyway, thank you!

**Comment by ff2000** [comment]
Lee, Byoung-young wrote:
> > I wanted to manually change the timeout to hide the cursor - 3sec for my taste is too large and the control in the preferences dialog is set inactive.
> 
> In that case, you'd better make a bug report because it was a bug and it's fixed now.
I wanted to use that as a chance to dive into the sources (+fix the issue and create a PR).
But you were much faster :) And being able to set in ms is also a good idea.

> > Compression would be great, too.
> 
> Now channel manipulation item saved in compact string instead of raw json array.
Yay, thx alot!

**Comment by xylosper** [comment]
>But you were much faster :)

Maybe I should've been lazier :)
Anyway, there are still lots of hidden bugs. I think you'll find another issue soon.
