### ISSUE TITLE
Some files don't play anymore

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#277]
They did play with previous bomi version and are still playable with mplayer and mpv.
I couldn't cut a part of the video but i can give a torrent as an example http://filepi.com/i/L7GoRUK

And one question about ppa. What is ffmpeg-bomi for?

**Comment by xylosper** [comment]
> And one question about ppa. What is ffmpeg-bomi for?

Literally, FFmpeg for bomi.

**Comment by swamp-fish** [comment]
I see, i thought bomi was built with ffmpeg already as mpv is.
Installed it, tried it, still the same.

**Comment by xylosper** [comment]
As you thought, it's already built against ffmpeg-bomi statically. So, you don't have to install it. It's only for building package and that's why the result package does not depend on it.

**Comment by xylosper** [comment]
Fixed. Thank you!
