### ISSUE TITLE
Doesn't remember position of floating panel

### ISSUE THREAD

**Issue by swamp-fish** [xylosper/bomi#278]
Thanks for updating ppa after fixing 2 previous bugs. But with bomi 0.9.5 the next bug appeared. Small one.
If you're using floating panel then it always appears at the right part like in the screenshot i attached. The round floating panel appears at the center though.

![bomi_bug_floating_panels](https://cloud.githubusercontent.com/assets/9247853/6863213/af922f4c-d455-11e4-9c3f-89e1ec513b7b.jpeg)

**Comment by xylosper** [comment]
0.9.5 only with two fixes was a special case because it contains fix for critical issue.
Anyway, fixed. Thank you!

**Comment by swamp-fish** [comment]
Hi, regression here, same trouble.

**Comment by xylosper** [comment]
Are you sure? I cannot find any problem.

**Comment by swamp-fish** [comment]
Sorry, I forgot to mention details. In windowed mode it remembers the position but if you go in fullscreen mode and quit while being in that mode then next time you open a player position will be changed.
