### ISSUE TITLE
Screenshot filename template?

### ISSUE THREAD

**Issue by AsukaLangleyfag** [xylosper/bomi#279]
Can you please make it customizable, like in mpv: http://mpv.io/manual/stable/#screenshot
offtop: thanks for good work and 64-bit build, switched from  smplayer to bomi on win and all works fine

**Comment by xylosper** [comment]
Of course possible, but to add it, I have to define some placeholders(ph).
At least to support current implementation, time phs needed:

* %YEAR% for year in 4 digits (2015)
* %YEAR_2% for year in 2 digit (15)
* %MONTH% for month in digits without leading zero (3)
* %MONTH_0% for month in digits with leading zero (03)
* %MONTH_S% for month in short name (Mar)
* %MONTH_L% for month in long name (March)
* %DAY%, %HOUR%, %MIN%, %SEC%, %MSEC% similar with %MONTH%
* %DAY_0%, %HOUR_0%, %MIN_0%, %SEC_0%, %MSEC_0% similar with %MONTH_0%
* %HOUR_12% for hour in 1-12
* %HOUR_12_0% for hour in 01-12
* %AP_U% for AM/PM
* %AP_L% for am/pm

With these phs, current format can be represented as:
bomi-%YEAR%-%MONTH_0%-%DAY_0%-%HOUR_0%-%MIN_0%-%SEC_0%-%MSEC_0%

Other phs which I can imagine now:

* %T_HOUR%, %T_MIN%, %T_SEC%, %T_MSEC% for current playback time in same format of %HOUR%, %MIN%, .... Also, Other suffices such as _0 have same meaning with those of %HOUR_0%, %MIN_0%, ....
* %MEDIA_NAME% for file name
* %MEDIA_DISPLAY_NAME% for display name in player
* %COUNTER_n% for incremental counter in 'n' digits with leading zero(for instance, 14th snapshot with %COUNTER_3% will betranslated 014).

If you have any suggestion for placeholder or better idea, please tell me.

**Comment by dragons4life** [comment]
Can you add a %unix like in sharex, where is just a bunch of random numbers?

**Comment by xylosper** [comment]
What is '%unix like in sharex'?

**Comment by dragons4life** [comment]
<img src="http://a.pomf.se/nsnyvn.png"/>

**Comment by xylosper** [comment]
I googled and found that %unix is a UNIX timestamp NOT random numbers.
Which one do you want? UNIX time or random number?

**Comment by dragons4life** [comment]
You are correct, I just tough they were "random numbers" so go with unix timestamps.
<img src="http://a.pomf.se/swdxpi.png"/>

**Comment by xylosper** [comment]
Okay, I'll add:

* `%UNIX%` for UNIX timestamp in seconds 
* `%UNIX_MS%` for UNIX timestamp in milliseconds

Also, if you like random number, I can add:

* `%RAND_n%` for random number with n digits

**Comment by dragons4life** [comment]
That's fine with me, thanks.
Also the latest release is really good, thank you for that too.

**Comment by xylosper** [comment]
New version released. Please test it.

**Comment by AsukaLangleyfag** [comment]
Well, fixed I guess. Thanks!
