### ISSUE TITLE
Priority of external subtitles

### ISSUE THREAD

**Issue by developer000** [xylosper/bomi#280]
Switch between using external subtitles when possible and reverse.

**Comment by xylosper** [comment]
What you want is an option such as 'select external subtitle preferentially' in preferences?
If not, would you explain/define what you want in detail?

**Comment by developer000** [comment]
"What you want is an option such as 'select external subtitle preferentially' in preferences?"
yes something like this. (like "Prefer subtitles from external file" in smplayer2)

**Comment by xylosper** [comment]
Done. Thank you.
