### ISSUE TITLE
Video quality issue in windowed mode.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#282]
Hi i got an issue with bomi the image quality in windowed mode are really poor especially on dark scene.
Here a screenshot in windowed mode : http://i.imgur.com/6iWBqNk.png
And the same scene in fullscreen : http://i.imgur.com/BOrg2MF.png
Try with standalone mpv and didn't get the issue.
Edit : Disabling high quality scaling > upscaling fixed it. Isn't this suposed to improved image quality ?

**Comment by xylosper** [comment]
If you changed something in Video menu, please try in default state.
Especially, check next:

* Chroma Upscaler = Bilinear
* Interpolator = Bilinear
* High Quality Scaling = both unchecked

**Comment by mac1202** [comment]
I edited my report High Quality Scaling > upscaling was the culprit but isn't this suposed to improved image quality ?

**Comment by mac1202** [comment]
Do you now what option High Quality Scaling > upscaling pass to mpv so i can test if the result is the same in mpv ?

**Comment by xylosper** [comment]
That's good idea. I have a hunch. Please try next options and let me know the result:

1. mpv --vo=opengl:fbo-format=rgba16:sigmoid-upscaling
2. mpv --vo=opengl:fbo-format=rgba:sigmoid-upscaling

**Comment by mac1202** [comment]
ok so 
1. with this option no problem the quality is fine
2. i got the same poor quality in windowed mode as with bomi

**Comment by xylosper** [comment]
That's exactly what I expected. Thank you for report & test.
I should've enforced 16bit fbo for hq upscaling.

**Comment by xylosper** [comment]
Fixed. Thank you!
