### ISSUE TITLE
Pause when minimize issue.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#283]
Hi when I enable pause when minimize + only apply to video file, I got my mp3 file with embeded cover also paused when i minimize bomi. No problem with mp3 without embeded cover.
Edit : also for some mp3 with cover bomi doesn't display the cover properly it just display a black background.

**Comment by xylosper** [comment]
> some mp3 with cover

What kind of mp3? Can you provide it?

**Comment by xylosper** [comment]
> Hi when I enable pause when minimize + only apply to video file, I got my mp3 file with embeded cover also paused when i minimize bomi. No problem with mp3 without embeded cover.

Fixed.

**Comment by mac1202** [comment]
>What kind of mp3? Can you provide it?
Here is [one mp3](http://s000.tinyupload.com/?file_id=45057128249231980980) that doesn't display the album art.

**Comment by xylosper** [comment]
Fixed. Thank you!
