### ISSUE TITLE
Show playlist/history when mouse hover edge stop working.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#284]
All is in the title I can't no longer display playlist/history when the mouse over left or right edge.

**Comment by xylosper** [comment]
It works fine here.
Did you happen to uncheck corresponding options?

**Comment by mac1202** [comment]
I just try another theme and it work. It doesnt work with the breeze theme.

**Comment by xylosper** [comment]
Fixed. Thank you!
