### ISSUE TITLE
Video thumbnails for seeking specific scenes.

### ISSUE THREAD

**Issue by befehlen** [xylosper/bomi#287]
I have a feature request.

I would like to seek specific scenes with video thumbnails.
Video thumbnails might let users see a quick snapshot of the certain time.

When a user moves and holds a mouse pointer on the progress bar, the bomi player displays
the thumbnail image of that specific time above the progress bar.
(Maybe some players - or just some online players - provide this feature.)

I think the player doesn't need to display exact frames, just key frames might be enough.

**Comment by mac1202** [comment]
It could be a nice feature. The only linux video player I know with this feature is [audience](https://code.launchpad.net/audience)

**Comment by ahjolinna** [comment]
I also like this feature but it should be a optional

**Comment by befehlen** [comment]
@ahjolinna I agree. It could be just a lagging and annoying feature to someone.

**Comment by xylosper** [comment]
Implemented. Thank you.

**Comment by befehlen** [comment]
Wow! Already?! I really appreciate it!!
