### ISSUE TITLE
Skin Freya

### ISSUE THREAD

**Issue by varlesh** [xylosper/bomi#288]
Hi Xylosper :) New skin.
Author: varlesh
License: Free
Icons: elementary
![2015-04-03 09 43 53](https://cloud.githubusercontent.com/assets/8083855/6979109/52517710-d9e7-11e4-8d0a-cd7364c6a507.png)
Download: http://www.datafilehost.com/d/09f8aa0d

**Comment by befehlen** [comment]
Wow! I like it!!

**Comment by xylosper** [comment]
Uploaded. Thank you.
