### ISSUE TITLE
[Feature] Snap to Edges

### ISSUE THREAD

**Issue by dragons4life** [xylosper/bomi#290]
Pretty simple make it so that the player window snap to edges, also if you can make it stay/fixed on the edges when you change size?

**Comment by xylosper** [comment]
> the player window snap to edges

This is done by WM/DE.

>  if you can make it stay/fixed on the edges when you change size?

Already doing so.

**Comment by dragons4life** [comment]
<blockquote>This is done by WM/DE.</blockquote>
Honestly don't understand what you mean by this.

**Comment by xylosper** [comment]
I remember you are using windows. WM/DE is about linux.
Implemented for Windows. Thank you.
