### ISSUE TITLE
Refresh directory list option in shortcut menu

### ISSUE THREAD

**Issue by Nekmo** [xylosper/bomi#293]
The chapter list isn't updated after copying new files in the directory. I think It would be useful a option to refresh the list. Another option is to automatically update the list.

![ff4](https://cloud.githubusercontent.com/assets/740106/7015028/87c17ad8-dccd-11e4-9da7-d5ff2f391b44.png)

**Comment by xylosper** [comment]
Technically, a playlist does not corresponds with any folder.
Playlist can contains files from different folders and also remote URLs.
I think what you need is a menu to regenerate playlist with current media.

**Comment by xylosper** [comment]
Add new menu 'Tool > Playlist > Regenerate'.

**Comment by xylosper** [comment]
New version released. Please test it.

**Comment by Nekmo** [comment]
Works fine. Thanks :D

**Comment by xylosper** [comment]
Thanks.
