### ISSUE TITLE
Add some kind of favorite.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#294]
I use bomi + youtube-dl to watch online video. Sometime I want to show some of them later to my friends but it could be difficult to retrieve a specific title when you have a big history list. It would be great to have some kind of favorite function to make specific title persistent in history and make them stay even after clearing the history.

**Comment by xylosper** [comment]
A starmark has added to history.
Starred items are displayed in front of history list and they are not removed when clear history.
Do you think this works for you?

**Comment by mac1202** [comment]
That's awesome. Thank you.

**Comment by mac1202** [comment]
I reopen it as I got a little issue. By default bomi starmark all video I open.

**Comment by xylosper** [comment]
Try again. I've just fixed it.

**Comment by mac1202** [comment]
Seems to work properly now.
