### ISSUE TITLE
Qt Installer Framework for windows version

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#295]
Now when Qt Installer Framework 2.0 is out and its ported to Qt5, you could use it as an standalone installer for windows users. It requires Qt 5.4 as a minimal version.

"The Qt Installer Framework allows for offline and online installers for Windows, Linux, and OS X. This framework is focused on Qt's needs but can also be used by other applications as an installer/updater."

https://blog.qt.io/blog/2015/04/07/qt-installer-framework-2-0-released/

**Comment by xylosper** [comment]
Why did you write this here?

**Comment by ahjolinna** [comment]
you mean why made a bug report a emailed you about this? ...well no idea :D 
maybe because every time I send a email to someone it goes to their spam folder.... I have no idea why it happens. So I thought why not make a bug report it seems more appropriate anyway.

**Comment by xylosper** [comment]
I mean here is not a Qt forum.
You're not supposed to write Qt news here.
Or, do you want some feature from new Qt installer?

**Comment by ahjolinna** [comment]
@xylosper : what I understand the installer Framework generates standalone installers (also updates) for your software, so I thought you could you this instead of the .zip files on the win version.

**Comment by xylosper** [comment]
Then you'd rather request windows installer, instead of writing a new of Qt installer without any context.

**Comment by ahjolinna** [comment]
so new bug report?

**Comment by xylosper** [comment]
If you want to discuss it, please do so.
