### ISSUE TITLE
Allow changing the filename in the online subtitle search

### ISSUE THREAD

**Issue by usedasbugtracking** [xylosper/bomi#298]
Hi,
When we look for a subtitle (on opensubtitles.org) for the current video, the filename can't be modified (readonly). However sometimes the filename is not generic enough and bomi ends up with no search results. Would it be possible to allow the end-user to modify the filename in this dialog and that the Find button uses the textbox content?

Regards

**Comment by xylosper** [comment]
The method to find subtitle is depend actual file (hash) so, it's meaningless to make filename ediatable.
Instead, I added two method to find subtitles: Find by Name and Find by Info and renamed current method to Find by File.

Find by Name accepts one tag which indicates media file name or subtitle file name or tagged information on opensubtitles.org.
Find by Info accepts title/season/epsiode for video.

Thank you for suggestion.
