### ISSUE TITLE
Windows: UI does not load; wrong skin path

### ISSUE THREAD

**Issue by larsjohnsen** [xylosper/bomi#299]
Release: bomi-0.9.5-win64, Windows 8.1

Happens when opening a media file in Bomi from Explorer. For some reason does this not happen when using "Open with".

Note: The media file's location is on a Samba share. The Bomi directory is on the desktop.

![bomi-screenshot](https://cloud.githubusercontent.com/assets/1748521/7087799/5d4dc9f4-df8f-11e4-856b-cdb05489c8b0.png)

**Comment by xylosper** [comment]
Fixed. Thank you!
