### ISSUE TITLE
실행 문의 드립니다.

### ISSUE THREAD

**Issue by yueunseon** [xylosper/bomi#301]
우분투 서버를 설치하고 xorg openbox bomi 를 깔았는데요.
터미널에서 bomi 를 입력하면 실행이 안 되요.

~$ bomi
libva info: VA-API version 0.37.0
bomi: dri2_util.c:199: isDRI2Connected: assertion `dri_state->base.fd >= 0' 실패.
중지됨 (core dumped)

~$ bomi --debug > ~/bomi.log
libva info: VA-API version 0.37.0
bomi: dri2_util.c:199: isDRI2Connected: assertion `dri_state->base.fd >= 0' 실패.
중지됨 (core dumped)

근데 sudo bomi 를 쳐야 실행이 되던데 원래 sudo 권한으로 실행시켜면 프로그램이 실행되구요.
반면 파일관리자에서 동상영파일을 오른쪽클릭하여 bomi로 재생선택하면 무응답이구요.

~$ sudo bomi
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
(I)[X11] Initialized hardware acceleration API: vaapi.
(I)[OpenGL] Check OpenGL stuffs.
(I)[OpenGL] Version: 3.0
(I)[OpenGL] Available FBO texture format: OGL::RGBA16_UNorm
(I)[OpenGL] Available FBO texture format: OGL::RGBA8_UNorm
(I)[OpenGL] Available extensions: GL_ARB_texture_rg, GL_ARB_texture_float, GL_KHR_debug, GL_ARB_framebuffer_object
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0

Batrail GPU 인텔 내장 그래픽을 사용중인데 드라이버를 잘못 깐걸까요?

**Comment by xylosper** [comment]
/dev/dri/card0 또는 비슷한 dri 장치의 권한이 올바르게 잡혀있는지 확인해보시기 바랍니다.
