### ISSUE TITLE
History and controlbar overlap on Tethys skin.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#303]
When you have a long history list try to open a title on the bottom of the list make the control bar appears on skin like tethys. The history panel keep the focus and you can still select the title you want but it's not very convenient. See this [screenshot](http://i.imgur.com/dGOcrUH.png)

**Comment by xylosper** [comment]
That's intentional. What did you make you think it's not very convenient?

**Comment by mac1202** [comment]
I find that is making the bottom of history list less readable.

**Comment by xylosper** [comment]
Now, when cursor is on history/playlist, overlapped controls get hidden automatically.
Do you think this is enough?

**Comment by mac1202** [comment]
Yeah that's good now. Thank you.
