### ISSUE TITLE
Album art is not send to mpris interface.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#304]
With bomi the album art is not displayed in plasma5 mpris applet. Here a screenshot with [cantata](http://i.imgur.com/3Y75Jtt.png) and with [bomi](http://i.imgur.com/GTLW4AX.png). As you can see even the title and the artist isn't properly displayed with bomi.

**Comment by xylosper** [comment]
I've fixed the wrong metadata issue.
However, there's a technical probelm internally to provide albumart image.
I'm trying to fix this but maybe it won't be easy...

**Comment by xylosper** [comment]
Fixed. Thank you.
