### ISSUE TITLE
video preview lags the video on full screen

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#305]
I just updated bomi (to 0.9.6) and I tried the preview thing, and I notice that on full screen video starts to lag/freeze everytime the preview window popups...the lag is way less on window mode.

I havent tried on my ultrabook yet because there is no OS on it yet :D

**Comment by xylosper** [comment]
Have you checked CPU usage when freezing?
Does it freeze only when popping up preview?
No problem during moving cursor on seek bar once the window popped up?

**Comment by ahjolinna** [comment]
cpu usage goes to 100% ...well almost, and the freezing happens during moving cursor on seek bar...but there is small lag (frame loss) when keep cursor on the same place (@seek bar)

**Comment by xylosper** [comment]
Does this problem occur with all your video?
Have you tried low quality video?

**Comment by ahjolinna** [comment]
yes, I tried many different types of videos from my 10tb anime collection (low&high quality)...same thing.

**Comment by xylosper** [comment]
Where is your video located? Local or remote(including home network)?
If it's remote, please try in local again.

**Comment by ahjolinna** [comment]
everything is local

**Comment by xylosper** [comment]
I assumed your PC is much more powerful than mine.
Just in case, what is your environment?

**Comment by ahjolinna** [comment]
I have the horrible netrunner15, aka ubuntu utopic with plasma5 (with latest nvidia driver)...for now until I find some good stable distro with plasma5 by default.

I think you have better PC, at least GPU, because I havent had any reason to upgrade mine yet (I will next year)..anyway here is My Desktop Specs: CPU: Intel i5-2550K@3.4GHz, Ram: Corsair Dominator: 24GB DDR3 1866Mhz GPU: 2x Asus Nvidia GTX 560ti (sli), SSD: Kingston HyperX 240gb, HDD: 13tb, Full ATX case:  NZXT Phantom 820, PSU 1000W, Motherboard: AsRock z68 extreme 3 Gen 3, Headphone: beyerdynamic DT-880, Keyboard: Roccat Ryos Pro MK

**Comment by ahjolinna** [comment]
btw. I notice that this problem affects: breeze, breeze-dark, Faenza-Zukitwo, Numix, Freya, classic, modern, native, simple

not: Ardis, Tethys, air

oh and it does not work on : GaN and one (maybe it shouldn't)

**Comment by dragons4life** [comment]
Tried to reproduce the issue, but it didn't happen to me on my laptop.
I am also using breeze-dark, going to try the other skins when I test the issue on my Desktop.

**Comment by ahjolinna** [comment]
@dragons4life : what kind of system spec do u have? and what distro/DE?

**Comment by dragons4life** [comment]
Using Windows 8
i3-3120M 2.5ghz
4GB Ram
Intel HD 4000

**Comment by xylosper** [comment]
@ahjolinna 
I assumed that you're talking about playback of video, but did you happen to mean delayed display of preview image?

**Comment by ahjolinna** [comment]
@xylosper : yes I'm talking about video playback. Preview image displayed just fine, except on GaN skin.

**Comment by xylosper** [comment]
Did you enabled or adjusted menus to enhance video quality?
Please check next menus in Video and try again in next value:

* Texture Format: 8-bit
* Chroma Upscaler: Bilinear
* Interpolator: Bilinear
* Highquality Scaling: turn off both
* Motion Smoothing: turn off

**Comment by ahjolinna** [comment]
@xylosper : no, does value settings did not help...at all

PS. here is Terminator Genisys trailer :P https://www.youtube.com/watch?v=rGSxss7gWak

**Comment by ahjolinna** [comment]
btw. if this info matters : with Ardis, Tethys, air -skin the cpu usage goes to max 150% of 2 cores but the video playback still works. Those others skin it's almost 100% on all 4 cores. ...I mean this happens when I move the cursor on the seek bar

**Comment by xylosper** [comment]
I don't think it's relavant.
Video preview is not a magic.
It just runs another player internally and seek to target frame which is extremeley CPU-intensive work.

**Comment by ahjolinna** [comment]
@xylosper : I just wonder why it works on those 3 skins and not on others...I really hope its netrunner15 only problem, I think I will install manjaro plasma5 pre version or maybe kubuntu 15.04 when its stable

**Comment by ahjolinna** [comment]
@xylosper : I just installed Manjaro Plasma 5 pre5 on my desktop and I tried bomi-git and I didn't have any problems now :P 

btw. I this mean I can test now the -git versions again :P

**Comment by xylosper** [comment]
Glad to hear that :)
