### ISSUE TITLE
Video playback does not start

### ISSUE THREAD

**Issue by Gustorn** [xylosper/bomi#306]
After an update to the new 4.0 Linux kernel video playback suddenly stopped working. After opening any video file the playback immediately stops, CPU utilization jumps up and after a few seconds a short audio fragment is stuck in a loop with the video still not moving.
Linux kernel version:
```
Linux arch-desktop 4.0.0-1-ARCH #1 SMP PREEMPT Mon Apr 13 08:57:29 CEST 2015 x86_64 GNU/Linux
```

I'm running the latest bomi from the [AUR](https://aur.archlinux.org/packages/bomi/):
```
$ bomi --version
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'vdpau'
libva info: Trying to open /usr/lib/dri/vdpau_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0
(I)[X11] Initialized hardware acceleration API: vdpau.
bomi 0.9.6
```

A log file of the unsuccessful playback (with --log-level=debug): [gist](https://gist.github.com/Gustorn/a9d8f36891139666ff93)

Also, this only happens on my PC with the AMD graphics (HD6950). My laptop with a 660M works fine with the newest updates. I also tried turning off HW acceleration and even uninstalling the `VAAPI` and `VDPAU` drivers, but still no luck. Playback works fine with either raw MPV or VLC (either with or without HW accel).

EDIT: I recompiled after the kernel upgrade just in case, still not working.

**Comment by xylosper** [comment]
Can you show me the playback info(shorcut: tab) in stopped state?

**Comment by Gustorn** [comment]
Sure, here it is: [playback info](http://imgur.com/cfI8Fkn)

**Comment by xylosper** [comment]
Good. Thank you.
