### ISSUE TITLE
정말 좋은 미디어 플레이어네요 , 그리고 이런 점은 불편했습니다 ^__^

### ISSUE THREAD

**Issue by bagjunggyu** [xylosper/bomi#307]
* 마우스만 조금 움직여도 플레이 리스트가 자주 나와서 영상을 가려요
* 나온 플레이 리스트를 클릭해서 닫아지게 하면 좋겠네요
* 전체화면에서 다시 작은 창 화면으로 돌아갈 때 esc키 로도 되면 좋겠어요
* 전체화면 표시 버튼을 눌러도 돌아가는 기능인가 확인하려고 할때마다 플레이 리스트가 나옵니다.
* 창크기에 맞춰 화면크가 바뀌면 좋겠습니다.
* 이런 부분이 해결되면 좋겠네요
* 멋진 미디어 플레이어 고맙습니다 ^__^

**Comment by xylosper** [comment]
>    마우스만 조금 움직여도 플레이 리스트가 자주 나와서 영상을 가려요

자동 팝업이 불편하시면 꺼버릴수 있습니다. 환경 설정>테마 탭의 컨트롤 그룹에 있는 체크박스를 확인해보세요.
너무 빈번하게 나타나지 않게하기 위해서 자동 팝업 인식하는 범위 넓이와 마우스가 올라가 있는 시간등을 조절하고 있는데 아직 최적의 값을 찾지 못한거 같습니다.

>    나온 플레이 리스트를 클릭해서 닫아지게 하면 좋겠네요

0.9.6 사용중이시라면 플레이리스트 왼쪽 상단에 닫기 버튼이 있습니다.

>    전체화면에서 다시 작은창 화면으로 돌아갈 때 esc 키로도 되면 좋겠어요

esc는 이미 다른 곳에 할당되어있기 때문에 직접 환경 설정에서 단축키 설정을 하셔야합니다.
참고로 현재 보미는 풀스크린 전환만 가능하고 들어가기/나가기가 따로 없기 때문에 전체 화면 메뉴에 엔터와 esc를 모두 할당하는 방법이 있습니다.
참고로 하나의 메뉴당 최대 4개까지 단축키를 설정할 수 있습니다.

>    전체화면 표시 버튼을 눌러도 돌아가는 기능인가 확인하려고 할때마다 플레이 리스트가 나옵니다. 이런 부분이 해결되면 좋겠네요 멋진 미디어 플레이어 고맙습니다 ^__^

마우스가 스킨 컨트롤 위에 올라가 있는 상태에서는 자동팝업이 작동하지 않도록 수정하였습니다.

**Comment by xylosper** [comment]
전체 화면 시작/전체 화면 종료 메뉴가 추가되었습니다.
다음 버전에서 전체 화면 종료 메뉴에 esc를 설정하시면 될듯합니다.

**Comment by bagjunggyu** [comment]
* 상단의 닫기 버튼으로 닫는 일이 조금 불편하더구요, 리스트 창을 더블클릭해서 닫게 하는것이 더 편할것 같네요
* esc는 다음 버전을 기대하겠습니다.

**Comment by xylosper** [comment]
화면의 빈곳(리스트나 컨트롤이 아닌 곳)을 클릭하면 닫히는건 어떨까요?
리스트창에서 더블 클릭하려면 리스트안에서 더블클릭을 받으면 안되는 곳을 골라내야 되는데(예를 들면 재생 목록 그자체나 버튼이 있는 곳등) 이건 사용자에게도 오히려 더 불편할겁니다.

**Comment by bagjunggyu** [comment]
* 맞네요^^ 그렇게 하면 되겠네요, 두번 클릭을 하면 어떨까 방금 생각하고 보미에서 눌러보니, 현재 보미에서는 기본 두번 클릭은 전체 화면 이더군요,일시 정지 기능이 일반적으로는 화면에서 이루어 지던데, 보미에서는 버튼을 누르게 되어 있더군요, 그부분에 대한 설정을 어떻게 하실지가  관건 이긴 하군요,화면 한 번 클릭 = 일시 정지 , 다시 클릭 = 재생 ,일반적으로는 이렇게 사용하잖아요. 이부분에 대한 정리를 하신후에 화면 빈곳 어딘가를 누르면 리스트가 사라지게 하는것 좋은것 같습니다^^
* 그리고 목록 닫기 버튼을 재생 반복 과 섞기 옆에 두면 어떨까 합니다.
* 보미가 항상 우선순위를 가지기 때문에, 경우에 따라 다른 필요한 프로그램들을 실행 하려고 하면 , 늘 보미나 제일 위에 있어서 , 실행 하는 프로그램이 안보이게 되네요,그래서 보미를 패널 트레이나, 플랭크 등의 런처에 내려놓아야 되더군요. 이부분도 좀 수정되었으면 합니다^^;;;;

**Comment by xylosper** [comment]
> 화면 한 번 클릭 = 일시 정지 , 다시 클릭 = 재생 ,일반적으로는 이렇게 사용하잖아요.'

일반적이지 않습니다.
저는 지금까지 윈도우/리눅스/맥 모두 사용해보면서 이걸 기본 동작으로 하는 플레이어는 한번도 보지 못했습니다.
참고로 보미의 해당 동작은 마우스 가운데 버튼 클릭에 대응됩니다.
기타 마우스 동작에 대한 설정은 환경설정>마우스 동작 탭에서 설정할 수 있습니다.

> 이부분에 대한 정리를 하신후에

무엇을 정리해야하는지 조금더 자세히 말씀해주시면 감사하겠습니다.

> 그리고 목록 닫기 버튼을 재생 반복 과 섞기 옆에 두면 어떨까 합니다.

닫기 버튼이 그곳에 들어가는건 맥락이 없습니다(out-of-context).

> 실행 하는 프로그램이 안보이게 되네요,그래서 보미를 패널 트레이나, 플랭크 등의 런처에 내려놓아야 되더군요. 이부분도 좀 수정되었으면 합니다^^;;;;

메뉴에서 '창 > 맨위에 표시 > 끄기'를 선택해주세요.

**Comment by bagjunggyu** [comment]
일반적이지 않았군요, 유투브에 익숙해서 그게 일반적이라고 생각했었네요.
그래서 한 번 클릭과 두번 클릭 등 클릭으로 화면을 사용하는 방법이 정리가 되면, 목록이 사라지게 하는 방법으로 두번클릭이면 어떨까 했던 것이구요, 한 번 클릭으로 목록 밖을 클릭해서 하는 것으로 정리 하셨더군요. 그렇게 제가 불편하게 느꼈던 부분에대한 이야기를 전해봤습니다.

**Comment by xylosper** [comment]
말씀하신 '정리'라는건 마우스 동작을 고정시켜버리는 것 같습니다.
보미는 마우스 동작을 커스터마이징할 수 있기 때문에 말씀하신 '정리'는 하지 않는게 좋을 듯합니다.

**Comment by akrtlqkf** [comment]
유튜브좀 재생되게 해줘유
