### ISSUE TITLE
Runing multiple instances of bomi

### ISSUE THREAD

**Issue by fawz** [xylosper/bomi#309]
Hi there,

I was wondering whether there's a plan to allow bomi to run multiple instances at once. As far as I can see this is impossible at the moment. 

Thanks for a great player!

**Comment by xylosper** [comment]
Please uncheck the option 'Run only single bomi application at the same time' in Application tab of preferences.

**Comment by fawz** [comment]
I'm blind -.- Sorry for the inconvenience.

**Comment by xylosper** [comment]
Never mind :)
