### ISSUE TITLE
playlist doesn't work

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#310]
I just installed bomi-git and tried the metro skin and I notice that the playlist does not work, I only see a small 1cm edge/border from it.

**Comment by xylosper** [comment]
I've made auto display truned off by default.
What you're seeing is a handle to pull playlist by clicking.

**Comment by ahjolinna** [comment]
I just notice that playlist doesnt work at all, not just on metro skin

**Comment by xylosper** [comment]
Please read previous my comment.

**Comment by ahjolinna** [comment]
okay, its seems I have to have "Show locations in playlist" enabled so it worked

**Comment by xylosper** [comment]
> okay, its seems I have to have "Show locations in playlist" enabled so it worked

Are you sure? Related option is 'Show history/playlist when mouse hoveres on screen edge'.

**Comment by ahjolinna** [comment]
yes I am, without  "Show locations in playlist" the clicking doesn't work... also I had 'Show history/playlist when mouse hoveres on screen edge' disabled and I still see the 1cm of the playlist

**Comment by xylosper** [comment]
> yes I am, without "Show locations in playlist" the clicking doesn't work...

Okay, this is a bug.

> also I had 'Show history/playlist when mouse hoveres on screen edge' disabled and I still see the 1cm of the playlist

The option is to display 'automatically' history/playlist without clicking.

**Comment by xylosper** [comment]
Fixed. Thank you!
