### ISSUE TITLE
네트워크(i.e 삼바)를 통해 영상을 열 경우 자막이 같이 열리지 않습니다.

### ISSUE THREAD

**Issue by chwnam** [xylosper/bomi#311]
로컬 파일의 경우, 영상을 열면 자막 파일이 같이 잘 열립니다. 그러나 삼바 경로에서 영상을 열 경우 자막 파일이 같이 열리지 않네요.

**Comment by xylosper** [comment]
현재 로컬파일에 대해서만 지원하고 있습니다.
리모트 파일의 경우에는 구조적으로도 당장 지원하기 힘든것도 있지만, 그뿐만 아니라 파일 IO속도가 보장되지 않기 때문에 로컬파일과 똑같이 처리해버리면 접속이 느리거나 응답이 없으면 그상태로 프로그램이 먹통이 되버릴수도 있어서 지원하지 않는 이유도 있습니다.
