### ISSUE TITLE
Blurry video in Bomi; clear in VLC and Mpv

### ISSUE THREAD

**Issue by Rabcor** [xylosper/bomi#312]
I recorded a video, and in VLC and Mpv it shows up crystal clear, whereas in Bomi it shows up slightly blurry.

(However it is also worth noting that VLC has brutal artifacts in the video's playback, but bomi and mpv play it smoothly all the way through)

I recorded the video myself with ffmpeg, it is 8 seconds long. This is the command used to record:
    
    ffmpeg -f alsa -ac 2 -i hw:0,0 -async 1 -f x11grab -s 1920x1080 -i :0.0 -c:a libmp3lame -b:a 384k -c:v libx264 -b:v 4000k -profile:v high444 -r 30 -preset ultrafast /mnt/stash/Record/Linux.mkv

If I play it back in VLC and Bomi side by side (or even pause it and display it in both players) everything will look slightly blurry in Bomi but crisp and clear in VLC (until the artifacts start showing up that is), you can easily read any text in VLC, meanwhile in Bomi it is legible, but blurry.

I remember way back (like maybe even a year) I recorded a video with these same settings, and it was as crisp in bomi (cmplayer back then) as it is now in VLC if my memory serves me right.

It's clearly not an upscaling issue (considering that the video is the same size as my monitor, and the blurriness is still there in fullscreen so it's not just a matter of downscaling either) 

Video: https://www.mediafire.com/?by9b4arn4hwp8cc

VLC is using default settings, Bomi also is using mostly default settings.

In most cases I find that the playback quality of Bomi is a notch above VLC (this is especially true about upscaling, I usually set it to Lanzcos and for exmaple upscaling a 720p video to 1080p will to me look much better in Bomi than in VLC, so I find it totally weird that VLC is showing me higher quality than Bomi with this one file; although after some minor testing, I've found that this applies to all 1080p videos (i.e. bomi's output of 1:1 ratio videos; videos that don't need to be scaled, is blurry compared to VLC, whereas bomi's output of upscaled videos is much better than VLC, maybe if we find out what's causing the blurring and fix it bomi will display videos in even higher quality than it does now.)

I have no idea why this happens, but it sure would be cool if you could fix it.

No tweaking of bomi's settings seemed to fix it (I tried changing the upscaler and interpolator, disabling and enabling deinterlacing and tweaking dithering.)

I am also wondering why hardware acceleration remains unavailable for that video, VDPAU should fully support it for this format.

**Comment by xylosper** [comment]
Fixed. Thank you.

About hardware acceleration, there are lots of missing profiles in source code which is added relatively recently including H264_HIGH_444_PREDICTIVE which is the profile of your example.
These profiles are supported by recent hardwared only and I cannot test them.
Just in case, check your hardware. You can confirm what profiles are supprted using `vdpauinfo`.

**Comment by Rabcor** [comment]
I'm on a 550-Ti; it should be (barely) recent enough. This is what it supports according to vdpauinfo:

MPEG1                           0  8192  2048  2048
MPEG2_SIMPLE                    3  8192  2048  2048
MPEG2_MAIN                      3  8192  2048  2048
H264_BASELINE                  --- not supported ---
H264_MAIN                      41  8192  2048  2048
H264_HIGH                      41  8192  2048  2048
VC1_SIMPLE                      1  8190  2048  2048
VC1_MAIN                        2  8190  2048  2048
VC1_ADVANCED                    4  8190  2048  2048
MPEG4_PART2_SP                  3  8192  2048  2048
MPEG4_PART2_ASP                 5  8192  2048  2048
DIVX4_QMOBILE                   0  8192  2048  2048
DIVX4_MOBILE                    0  8192  2048  2048
DIVX4_HOME_THEATER              0  8192  2048  2048
DIVX4_HD_1080P                  0  8192  2048  2048
DIVX5_QMOBILE                   0  8192  2048  2048
DIVX5_MOBILE                    0  8192  2048  2048
DIVX5_HOME_THEATER              0  8192  2048  2048
DIVX5_HD_1080P                  0  8192  2048  2048
H264_CONSTRAINED_BASELINE      --- not supported ---
H264_EXTENDED                  --- not supported ---
H264_PROGRESSIVE_HIGH          --- not supported ---
H264_CONSTRAINED_HIGH          --- not supported ---
H264_HIGH_444_PREDICTIVE       --- not supported ---
HEVC_MAIN                      --- not supported ---
HEVC_MAIN_10                   --- not supported ---
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   --- not supported ---
HEVC_MAIN_444                  --- not supported ---

I see, so it doesn't support H264 fully, and not H265 at all, what a shame. Oh well, I'm upgrading soon enough.

I have a 670 on my other system, maybe that one will support it better since it's kepler architecture. Anyhow, I updated Bomi and tested it to confirm, and everything looks good in Bomi now. Actually in windowed mode it looks a lot better than in VLC (Apparently not only better upscaling than VLC, but better downscaling as well) :+1: 

Good job :)

**Comment by xylosper** [comment]
Well, I don't think 6xx can provide better support.
At least, AFAIK, HEVC profiles are only supported 9xx(maxwell architecture).
Anyway, thank you for testing!

**Comment by Rabcor** [comment]
I'm upgrading to the 1000 series next year when they're released. (And buying a whole new system while at it)

My 670 card is going to remain in my little Windows media center that I use for things like Steam's in-home streaming. (But it does have a dual boot with Arch so I can always test stuff on it)
