### ISSUE TITLE
Save interval to a new video file (a.k.a. video clips)

### ISSUE THREAD

**Issue by Nekmo** [xylosper/bomi#313]
Bomi already have a repeat functionality. You select an interval start (A) and interval end (B). Bomi repeats this fragment until you pressing Esc. Bomi could be much better (and the best player in the world!) if you could save that fragment to a new video.

The possibilities are endless. Make gifs would be quick and easy! No need to open a video editor. If you liked a scene, save it would be easy!

I do not know if it's asking a lot, but I think it would be very cool!

**Comment by xylosper** [comment]
Done. Thank you.

**Comment by ahjolinna** [comment]
I hate gif quality, apng or bpg would be nice to have also ...for "high quality gifs"

what is bpg? : http://bellard.org/bpg/

**Comment by Nekmo** [comment]
I knew jpg but not bpg. Interesting.

**Comment by xylosper** [comment]
Everyone knows gif sucks. It's not about quality. It's about compatibiliy.

**Comment by ahjolinna** [comment]
well apng is meant to be the new standard, and bpg needs x265 encoder?...what I understand ...and its supported by most web browsers (..with a small javascript decoder).

**Comment by xylosper** [comment]
@ahjolinna 
Exactly, you are saying that those formats are not supported well.

**Comment by ahjolinna** [comment]
@xylosper : well apng support is really good...it was released 2008 http://en.wikipedia.org/wiki/APNG#Support
bpg was released last year..but it has surprisingly good support for such a short time...well biggest problem with it is the HEVC patent : http://en.wikipedia.org/wiki/Better_Portable_Graphics#Patents

**Comment by Nekmo** [comment]
Gfycat use webm, and Imgur use gifv (mp4). Include webm can be interesting.

**Comment by xylosper** [comment]
@ahjolinna 
How can you say apng support is good from the table?
The table says gecko is the only browser engine which supports apng currently.

bpg is not even candidates. No browser supports it.
You cannot say it's supported if it requires additional component.

@Nekmo 

For image format, there's a so-called webp format which is only supported by chrome.

**Comment by ahjolinna** [comment]
@xylosper : well those bpg test images and animations did work on my firefox.. and I have no Idea why apng isnt yet supported on chrome/blink engine...maybe because it isn't googles?

**Comment by xylosper** [comment]
@ahjolinna Without additional component? If you're saying http://bellard.org/bpg/gallery3.html, it depends on javascript decoder which is not supported by browser itself. It's just a binary file for firefox.
