### ISSUE TITLE
Find subtitles

### ISSUE THREAD

**Issue by usedasbugtracking** [xylosper/bomi#314]
Hi,

Thanks for the modifications that you did in your last release (find by info...). However I do have an issue: it seems that some required initializations are missing. When I watch a movie in bomi and start watching a new one (by double clicking on a selected file from dolphin) and using the shortcut (CTRL-Shift-F), bomi doesn't manage to find any subtitle (regardless of the find method). But if I do exit bomi (through the exit option) and launch it again (by double clicking on a selected file from dolphin) then bomi is able to find possible matches...
Could you have a look into that?

Regards

**Comment by xylosper** [comment]
I've experienced similar issue from time to time but I couldn't find the condition to reproduce it.
Do you know a procedure which can reproduce your problem always?

**Comment by usedasbugtracking** [comment]
Everytime I watch a movie and search for a subtitle, for any next movie I watch I cannot find any subtitle match until I exit and restart bomi. That means it doesn't work for the second movie search. I use dolphin to watch every movie (by a file association) (I don't know if it changes anything in the initialisation phase or not).

**Comment by usedasbugtracking** [comment]
I stand corrected: It seems that if I immediately search for the second movie without having watched the show for more than a few minutes it works. But 40 minutes later it won't. Some kind of timeout. Rather strange. Or there's some random factor that I hadn't noticed until now...

**Comment by xylosper** [comment]
From your description, I noticed that the session may be disconnected after timeout.
I have made a change to keep the connection. Can you test git version?

**Comment by usedasbugtracking** [comment]
Sorry but why do you need to keep the connection open the whole time? Can't you just open a new connection once the subtile dialog opens?

**Comment by xylosper** [comment]
That's possible. I repeat your question: but why?

**Comment by usedasbugtracking** [comment]
Just curious...
I'll give it a try (I'll first look for instruction and how to retrieve from git and compile)...

**Comment by xylosper** [comment]
What distro do you use? If you're using Arch or something based on Arch, you can use bomi-git package in AUR.

**Comment by usedasbugtracking** [comment]
My distro is kubuntu (14.10 for now) and I use your ppa. I just installed the 0.9.9 version.

**Comment by xylosper** [comment]
If you think it's fixed, please close this issue.

**Comment by usedasbugtracking** [comment]
Indeed it's fixed. Thanks again.
