### ISSUE TITLE
Make Video Clip not works (Bomi crashed)

### ISSUE THREAD

**Issue by Nekmo** [xylosper/bomi#315]
Steps to reproduce:
1. Select "Vídeo -> Make Video Clip -> Start range", after, select "Select Range".
2. Save video in new dialog. Default options.
3. Bomi crash.

Tested with mkv and mp4 videos. It's always reproducible.

Version: commit 1216d11f15532e145438fda248c951d2a0cdf0a9
OS: Arch Linux 3.19.2-1-ARCH
Mpv and ffmpeg builded with Bomi (view PKGBUILD).
https://www.dropbox.com/s/0yw0jyj5mc0kyxq/bomi-build-git-v0.9.5.39.g4c207ff-1.src.tar.gz?dl=1

**Comment by xylosper** [comment]
There's no action such as 'Start Range' nor 'Select Range'.
Can you provide log of `bomi --debug`?

**Comment by xylosper** [comment]
Why do you use static build of ffmpeg? The build script for ffmpeg is outdated and it disables all encoders.

**Comment by Nekmo** [comment]
Bomi not compile in another way. I will modify the official PKGBUILD to use the last commit.

**Comment by Nekmo** [comment]
With --debug parameter returned:

    (D)[X11] Enable screensaver with 'org.freedesktop.ScreenSaver'.
    (F)[mpv/encoder] invalid parameter: Couldn't initialize mpv.
    Abortado (`core' generado)

**Comment by xylosper** [comment]
bomi-git in AUR should work.

**Comment by Nekmo** [comment]
For me it doesn't work:

    g++: error: /tmp/bomi-git/src/bomi/build/lib/libmpv.a: No existe el fichero o el directorio
    Makefile.Release:1295: fallo en las instrucciones para el objetivo '../../build/bomi'
    make[2]: *** [../../build/bomi] Error 1
    make[2]: se sale del directorio '/tmp/bomi-git/src/bomi/src/bomi'
    Makefile:38: fallo en las instrucciones para el objetivo 'release'
    make[1]: *** [release] Error 2
    make[1]: se sale del directorio '/tmp/bomi-git/src/bomi/src/bomi'
    Makefile:40: fallo en las instrucciones para el objetivo 'build/build/bomi/bomi'
    make: *** [build/build/bomi/bomi] Error 2
    ==> ERROR: Se produjo un fallo en build().
        Cancelando...

Translated:

    g++: error: /tmp/bomi-git/src/bomi/build/lib/libmpv.a: Not exists file or directory
    Makefile.Release:1295: fail in instructions for target '../../build/bomi'
    make[2]: *** [../../build/bomi] Error 1
    make[2]: leaving directory '/tmp/bomi-git/src/bomi/src/bomi'
    Makefile:38: fail in instructions for target 'release'
    make[1]: *** [release] Error 2
    make[1]: leaving directory '/tmp/bomi-git/src/bomi/src/bomi'
    Makefile:40: fail in instructions for target 'build/build/bomi/bomi'
    make: *** [build/build/bomi/bomi] Error 2
    ==> ERROR: An error occurred in build().
        Cancelling...

**Comment by Nekmo** [comment]
Ok, now works. Sorry for the trouble caused, and thanks for your concern!

Now the problem is that it keeps subtitles :( I guess this is the desired result for many times. But I think it would be useful to leave the option. I will create a new task.

Thanks for everything.

**Comment by xylosper** [comment]
That's weird. It should not display subtitles.

**Comment by Nekmo** [comment]
Sorry, I misspoke. My English is very bad :( The problem is that the video has no subtitles. I created a new task: #316 

Please, close this thread.
