### ISSUE TITLE
Include subtitles option in make video clip dialog

### ISSUE THREAD

**Issue by Nekmo** [xylosper/bomi#316]
Currently, subtitles are not included when a video clip is created. This is useful for certain scenes, but lost for example karaokes.

Include a option "include subtitles" (a checkbox, for example) in Make Video Clip dialog, solve this.

**Comment by xylosper** [comment]
Done. But please be aware that bomi is not an encoder nor editor. There are some limiations.
This time, no multiple subtitle supported. Rendering priority is:
1. selected internal subtitle
2. selected ass external subtitle
3. last selected non-ass external subtitle
