### ISSUE TITLE
Sometimes floating controls don't react to click

### ISSUE THREAD

**Issue by Nekmo** [xylosper/bomi#317]
It's difficult to reproduce. Only happens after seeing a video several minutes. The problem disappears when you pause with the keyboard. 

This video shows the bug. I try unsuccessfully pressing all buttons in floating controls panel. Please, note that the "next chapter" option is marked (blue color) while mouse is hover others buttons. After pause with space bar, all works fine.
http://share.nekmo.org/bugs/bomi_bug2.mkv

**Comment by xylosper** [comment]
Yeah, it's hard to reproduce. I've had same problem but I cannot tell when this happen and what causes this...

**Comment by Nekmo** [comment]
I have not reported this error until now because I don't know how reproduce this fail always. I have tried many things but I haven't more information.

**Comment by ahjolinna** [comment]
it seems the  "duplicated OSD handling" fix also fixes this issue...well at least for me..for now :D

**Comment by xylosper** [comment]
I found that a way to reproduce this always:  this behavior always occurs after drag & drop.
I made a fix for this and close for now but maybe there still are other corner cases. If you find other case, please let me know.
Thank you.
