### ISSUE TITLE
Don't create bomi-albumart.png in curent folder

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#318]
I see that now bomi create a temporary file in current folder for mpris album art export. I don't think it should create it in current directory because if the folder is in read only mode file isn't created and mpris album art doesn't work. A better place in linux should probably the /tmp directory.

**Comment by xylosper** [comment]
Oops, that was a mistake. Fixed. Thank you.

**Comment by xylosper** [comment]
Ah, btw, I've put initail frame as art image for videos. Do you think this is ok?
