### ISSUE TITLE
Error in building bomi-0.9.7

### ISSUE THREAD

**Issue by tetris4** [xylosper/bomi#319]
Hello,

I am trying to build 0.9.7 for Chakra but I am coming across this error:
https://paste.kde.org/praxmp7ek

This is the PKGBUILD I am using:
https://paste.kde.org/pbmnvwmgb

Any help would be appreciated.

**Comment by xylosper** [comment]
Check libass version. You need libass >= 0.12

**Comment by tetris4** [comment]
Thanks for the quick response! That did the trick! 
Wouldn't it be better if bomi could pop out an error during configure about this and stop the build earlier? I do not know if it is possible, just saying. =)

**Comment by xylosper** [comment]
Already done as soon as I saw this issue :)
