### ISSUE TITLE
Bomi fails to build with GCC 5 on Fedora 22 Beta

### ISSUE THREAD

**Issue by M4rtinK** [xylosper/bomi#320]
I've just updated to the Fedora 22 Beta and tried to build Bomi with the default compiler, which is GCC 5:

$ gcc --version
gcc (GCC) 5.0.0 20150319 (Red Hat 5.0.0-0.21)

I've tried to build master, v0.9.7 and v0.9.6 and all of them fail with the same error messages:

https://gist.github.com/M4rtinK/81900ecb69fe0c31edce

I think this is probably caused by GCC 5 and shows on on the Fedora 22 Beta because it is one of the first distros with GCC 5.

**Comment by xylosper** [comment]
I can tell nothing but this is a bug of GCC.
As a workaround, you can try this patch:
```patch
diff --git a/src/bomi/player/mpv.hpp b/src/bomi/player/mpv.hpp
index 40879b0..866f15a 100644
--- a/src/bomi/player/mpv.hpp
+++ b/src/bomi/player/mpv.hpp
@@ -14,8 +14,7 @@ class OpenGLFramebufferObject;
 
 SCIA s2ms(double s) -> int { return s*1000 + 0.5; }
 
-#define MPV_CHECK(err, fmt, ...) \
-    (isSuccess(err) ? true : (_WriteLog(e2l(err), "Failed to " fmt ": %%", __VA_ARGS__, e2s(err)), false))
+#define MPV_CHECK(err, fmt, ...) isSuccess(err)
 
 class Mpv : public QThread {
     template<class R, class...Args> using func = std::function<R(Args...)>;
```

**Comment by M4rtinK** [comment]
Thanks for the patch! I've applied it on top of v.0.9.6 and I am now able to build Bomi & it appears to work fine. :) There seems to be already an update for GCC 5 (5.0.1) in the testing repo, so I'll try compiling Bomi without the patch once the new GCC version reaches the stable repo.

**Comment by xylosper** [comment]
I found a better workaround. Please use this patch instead of previous one.
```patch
diff --git a/src/bomi/player/mpv.hpp b/src/bomi/player/mpv.hpp
index 40879b0..7d801f4 100644
--- a/src/bomi/player/mpv.hpp
+++ b/src/bomi/player/mpv.hpp
@@ -120,7 +120,7 @@ private:
         node.format = MPV_FORMAT_NODE_ARRAY;
         node.u.list = &list;
         fill(list.values, name, args...);
-        const int error = f(&node);
+        int error = f(&node);
         return MPV_CHECK(error, "execute %%", name);
     }
     auto newObservation(const char *name, std::function<void(int)> &&notify,
```

There's no regression by this patch.

**Comment by M4rtinK** [comment]
Sure, I'll try the new patch tomorrow. :)
