### ISSUE TITLE
v0.9.7 LiNUX  >  Hangs on start when "auto_unmute": true, in pref.json

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [xylosper/bomi#321]
Hiya, just updated from v0.9.6 to v0.9.7 via PPA (Kubuntu 14.04 x64). 

Everything working nicely.  Trying all new settings.  Bomi closed / opened a lot = working. 

Suddenly, it started hanging on launch:
* Window never appers / renders
* Spawned process not cleaned up
  * (have to invoke 'killall' command to clean up all processes - 1 for each time I try to launch)
* (nothing useful seen in "bomi --debug")  (this seems to hang too!)

I compared, & tested > New option in pref.json:
* "auto_unmute": true,    == Hangs on Launch
* "auto_unmute": false,    == Working good

O_O

**Comment by xylosper** [comment]
Already fixed at https://github.com/xylosper/bomi/commit/d3d4717f6cc3af4b4ab655ebc8497ac6557542f2.
