### ISSUE TITLE
시스템 트레이 아이콘이 안 보입니다.

### ISSUE THREAD

**Issue by demokritos** [xylosper/bomi#322]
저는 Gnome-shell 최신 버전을 사용하고 있습니다.
지난 버전에서도 안 되었는데요, 시스템 트레이에 보미 아이콘이 안 보입니다. 
자리에 뭔가 있다는 것은 확실하고 오른쪽 마우스 버튼을 누르면 메뉴가 나타납니다. 
아이콘만 안 보입니다.  Gnome-shell의 문제일 수도 있습니다. Dropbox라든지 다른 
프로그램에서도 아이콘이 안 보였다가 다시 보이기 시작했거든요.
보미도 Dropbox처럼 보이게 만들어 주실 수 있을까요? Dropbox도 Qt를 쓰는 걸로 
알고 있습니다.
보미는 아치리눅스 bomi-git를 사용하고 있습니다.

**Comment by xylosper** [comment]
Qt 5.5.0에서 해결된 문제로 보입니다.
