### ISSUE TITLE
Time codes in the lower right corner cannot be seen clearly with the native theme

### ISSUE THREAD

**Issue by notargets** [xylosper/bomi#323]
In Bomi 0.9.8, when the native theme is selected in the preferences, the time codes in the lower right corner cannot be seen clearly.

So, for instance, instead of something like "00:02/1:39:52", all I see is "00:021:..." (the digits 2 and 1 even overlap a little). Also, by every single left click on it more and more digits disappear, so, at the end, only "00....." is displayed.

(I'm using KDE4 with QtCurve.)

**Comment by xylosper** [comment]
Fixed. Thanks.
