### ISSUE TITLE
White (light grey) strip at the bottom of the video

### ISSUE THREAD

**Issue by bob-art** [xylosper/bomi#324]
@xylosper.
Hi! I'm accidentally ran into this problem: light gray strip at the bottom of a 2-pixel, when viewing video, which corresponds to the actual resolution is 1280x718 (on tracker: "WEB-DLRip (720p)", link: http://kinozal.tv/details.php?id=1256451)
All options to change the aspect ratio to no avail, as well as all other manipulations with the settings - "Crop video window size", etc.

For comparison: smplayer this artifact does not suffer - there can be programmatically added a thin black strip to compensate non-standard resolution, maybe the problem is solved in some other way, but this white strip is absent.
Is it possible to somehow solve this problem and in bomi?

My current version bomi is 0.9.6-1
Thanks.

**Comment by xylosper** [comment]
I cannot find download link. Maybe translation sucks.
Can you post download link directly here?

**Comment by bob-art** [comment]
I'm sorry, ...but link does not work without registration. 
But I can send to the you email a link to tracker with passkey - arrange it?

**Comment by xylosper** [comment]
In that case, please first try latest version.
If it still has problem, please post the comparision screenshot.
If I cannot reproduce your problem, then I'll ask you to send me an e-mail.

**Comment by bob-art** [comment]
Ok.

**Comment by bob-art** [comment]
bomi, latest version, screenshot: http://itmages.ru/image/view/2485310/b17b8d69 - light gray bar at the bottom of the frame.

New version - new surprises: video freezes at middle click (action Play-Pause) and as well as being when you click on the Play-button on the media-panel - while bomi completely ceases to respond to any mouse clicks on the screen or any buttons on the panel. But keyboard is works - that is, the player responds to keyboard actions.
Successful update =)

**Comment by xylosper** [comment]
Action id for toggle play/pause changed from 'play/pause' to 'play/play-pause'.
This change broke previous default mouse action for middle click at 0.9.7 for upgrade users.
Please see release note for 0.9.7: https://github.com/xylosper/bomi/releases/tag/v0.9.7

**Comment by xylosper** [comment]
I've test that resolution with arbitary video clip but I couldn't reproduce it.
Please send me the torrent file by darklin20@gmail.com

**Comment by bob-art** [comment]
xylosper, thanks, but yet to make a pause: I'll check bomi.qml - perhaps freezing is related to changes in the "actions" in the .qml-file - If I'm right, I'm going to freeze problem solve on their own - if not, I will inform you.
I launched a new version bomi to clean profile - white band is not observed ...
I will report the results of their research.

**Comment by xylosper** [comment]
Quick solution: try default skin.

**Comment by bob-art** [comment]
Yes, I checked on the default - all working fine and so will check my qml-file.

**Comment by bob-art** [comment]
Hi!
So, the situation is as follows: white bar does not appear at all the files with a resolution 1280x718 and I can not catch this any regularity, in other words, it appears not everywhere - in all these cases Hardware Acceleration "On".
Next: white strip is absent when "hardware acceleration" in preferences is turned off.

However, this is minor in comparison to that using hardware acceleration (Hardware Acceleration: Activated [vdpau] provides a CPU load over 30% (~ 15% for each core)
In previous versions, these figures do not exceed 6-8% (3-4% per core) - and that's was normally.

**Comment by xylosper** [comment]
I'm not sure I understood whay you said.
Are you saying that white lines are visible only if hwacc is turned off?

High CPU usage has been fixed.

**Comment by bob-art** [comment]
>> Are you saying that white lines are visible only if hwacc is turned off?
No, I'm was trying to say, that if hwacc is "off" - white stripe is absent. 
If hwacc is "on" - white streaks appear randomly: e.g., s04e01 - have a white stripe, but s04e16 - have not white stripe. 
And i can't understand the pattern of this phenomenon.

>> High CPU usage has been fixed.
Thank you!

**Comment by xylosper** [comment]
Does this problem occur totally randomly? Or, is it confined to specifc file?
Do you happen to use AMD GPU?

**Comment by bob-art** [comment]
— Does this problem occur totally randomly? Or, is it confined to specifc file?
The i'm saw it only on those media files, links to which (and .torrent) i'm gave you. Then, i'm drew attention to the specific resolution: 1280x718 - and lack of these 2 vertical pixels i'm explained the appearance of stripes. 

— Do you happen to use AMD GPU?
No, my gpu - Nvidia GeForce GT 610 (hwacc supported on this chip)

**Comment by xylosper** [comment]
Fixed. Thank you!

**Comment by xylosper** [comment]
For your skin, please send me your file. I'll check it.
