### ISSUE TITLE
After the last update is not working system locale

### ISSUE THREAD

**Issue by ForumLiker** [xylosper/bomi#325]
Hi! In bomi 0.9.8 dont work system locale (russian)
Everything worked before the upgrade (bomi 0.9.7)
<<screen>>
http://joxi.ru/MAjl15yhGe9Yme

**Comment by xylosper** [comment]
Russian translation dropped for too low completion rate.
If you're interesting in Russian translation, you can translate here: https://www.transifex.com/projects/p/bomi/

**Comment by ForumLiker** [comment]
I will try to help with translation
