### ISSUE TITLE
0.9.9.9 업데이트 이후 qtquick 버전 문제..

### ISSUE THREAD

**Issue by xenima** [xylosper/bomi#329]
업데이트 이후 시작시에 
file:///usr/share/bomi/skins/GaN/bomi.qml:6:1: Type B.AppWithFloating unavailable
file:///usr/share/bomi/imports/bomi/AppWithFloating.qml:9:5: Type Player unavailable
file:///usr/share/bomi/imports/bomi/Player.qml:16:29: Type BarVisualizer unavailable
file:///usr/share/bomi/imports/bomi/BarVisualizer.qml:1:1: module "QtQuick" version 2.4 is not installed
라고 오류가 발생하고 제대로 실행이 안됩니다. 무언가를 더 설치해야 하는듯하나 잘 모르겠네요..
리눅스 민트 17.1 시나몬 사용중입니다.

**Comment by xylosper** [comment]
민트는 어떤패키지를 쓰는지모르겠습니다.
현재올라간 패키지중에 vivid용은 Qt 5.4가 필요합니다.

**Comment by xenima** [comment]
민트도 기본적으로 우분투 저장소를 사용하기에 우분투와 동일한 패키지일겁니다. 이전버전까지는 잘 되는거로 봐서 qt에 문제가 있지는 않아보이는데 잘 모르겠습니다.

**Comment by xylosper** [comment]
그게 아니라 버전 호환성을 말씀드린 것입니다.
vivid부터는 Qt버전도 같이 5.4로 올라갔기 때문에 vivid에서는 5.4를 요구해도 문제가 되지 않습니다.
민트에서 우분투 패키지를 끌어 쓰시는 경우에는 호환이 보장된 버전을 사용하셔야 합니다.

**Comment by xylosper** [comment]
일단 요구 버전을 5.2로 다시 내렸으니 해당 에러는 없어지긴 하겠지만, 앞에서 말씀드린대로 호환이 되는 우분투 버전을 확인하시고 해당 버전용 패키지를 사용하시는걸 추천합니다.
하위버전에서 링크된걸 상위버전에서 실행할때는 보통 호환성이 보장되지만 상위 버전에서 링크된걸 하위버전에서 실행하는건 호환성을 보장하지 않습니다.

**Comment by xenima** [comment]
네 감사합니다. 일요일 오전부터 고생하셨습니다.^^
