### ISSUE TITLE
Temporary freeze when seeking back

### ISSUE THREAD

**Issue by Krysisx** [xylosper/bomi#330]
Hi,

I have linux mint x64 and a MSI radeon HD 6870 Hawk.
I have just installed bomi 0.9.9 from ppa.
When seeking back with keyboard or mouse the video freezes for an unspecified time and I noticed that a way to get it back is toggling fullscreen on/off.
I have "quality preset" set to "highest quality" but same result if I change it.
I have also tried to change "deintarlacing" auto/off but still no luck.

Any help please?

Thanks

**Comment by xylosper** [comment]
First try without hwacc, if it's turned on.
If you still have same problem, please post the log with `bomi --debug`.

**Comment by Krysisx** [comment]
Actually I think it's disable because I cannot change the hwacc option. I don't know why I'm not able to change it.

**Comment by xylosper** [comment]
>  I don't know why I'm not able to change it.
That's because your hardware doesn't support it or you don't have proper driver.

Anyway, what does the logs say?
