### ISSUE TITLE
.mod Support

### ISSUE THREAD

**Issue by maxmitti** [xylosper/bomi#332]
It would be nice to have better support for .mod-files.
Actually bomi can play .mod-files.
But I can only add them to playlist when I manually set the file filter in the open dialog to "*.mod".
Also, it seems that bomi thinks .mod-files are videos, because it pauses them when minimizing bomi, although i enabled the option to only pause videos.
Last but not least, using the meta tags stored in the .mod-files would be great.
For example Dragon Player does that, or even mpd.

**Comment by xylosper** [comment]
> But I can only add them to playlist when I manually set the file filter in the open dialog to "*.mod".
Also, it seems that bomi thinks .mod-files are videos, because it pauses them when minimizing bomi, 

Fixed.

> Last but not least, using the meta tags stored in the .mod-files would be great.

What do you mean 'using the meta tags'?
I'm not familiar with that format. What should I do?
Is there any special purpose for meta tags in mod files?

**Comment by maxmitti** [comment]
When I say meta tags, i think about information like song title or artist.
I dont know the format exactly but i know there is some information like that from the other players.
If you want to try one yourself you can download free mod files from http://modarchive.org .

**Comment by maxmitti** [comment]
Btw, when I look at the commit, where you added .mod extension to audio files, that list looks a bit incomplete. Maybe you should search for a list of supported extensions from mpv and use that.

**Comment by xylosper** [comment]
> When I say meta tags, i think about information like song title or artist.

What should I do with song title or artist?
I don't have any other idea to use those information.

> Btw, when I look at the commit, where you added .mod extension to audio files, that list looks a bit incomplete.

I don't think it's good idea to add all almost useless extensions but I don't have so much knowledge to judge the majority by myself.
For instance, there was an extension .h264 for video file but who the hell name the file with such extension?
Just let me know what is missing, if you think they're important ones.

**Comment by maxmitti** [comment]
According to the meta tags, e.g. you could display the song title instead of the file name. I thought you do already do this with other formats, but I may misrember. Its not important anyway.

And according to extensions, the only useful audio extension I can think of is .ape.
And maybe .xm and .it, but I dont know if mpv supports them. Must try them later.

**Comment by maxmitti** [comment]
I tested .ape, .xm and .it and they seem to work.

**Comment by maxmitti** [comment]
Back to the meta tags, it looks like bomi doesnt read them itself, but the first line in "Playback Information" shows the title from mp3-Files or Youtube Vidoes, I think. But never mind my wish to show .mod-metadata, it's very unimportant.

**Comment by xylosper** [comment]
> According to the meta tags, e.g. you could display the song title instead of the file name. I thought you do already do this with other formats, but I may misrember. Its not important anyway.

Yes, that's already what bomi's doing. I just don't have any **other** idea to utilize those information.

> I tested .ape, .xm and .it and they seem to work.

Added. Thanks.

**Comment by xylosper** [comment]
If you don't mind tag information implementation, please close this.
