### ISSUE TITLE
Publish the source code of the web for translations

### ISSUE THREAD

**Issue by Nekmo** [xylosper/bomi#334]
I love Bomi and would like to translate the website into my language. I think more people would do the same!

**Comment by xylosper** [comment]
There's no hidden source code. All documents are plain html which you can checkout from https://github.com/bomi-player/bomi-player.github.io.
However, it's not easy to provide certain  translation for website because I don't want the pages to show different contents for different language when updated.
This is not problem for application because it will display texts in english when no translation exists but this cannot be applied to website.

**Comment by Nekmo** [comment]
Thanks. I needed a repository to "pull request". If you agree, I will make a fork with a translatable static version usign Jinja2. :)

**Comment by xylosper** [comment]
I cannot tell before see the result because I don't want the page structure to be too rigid by templates to change/add content freely.

**Comment by Nekmo** [comment]
My idea is to use the i18n extension of Jinja2.

http://jinja.pocoo.org/docs/dev/extensions/#newstyle-gettext


Un cordial saludo:
-- Nekmo.

Sitio web: http://nekmo.com
Dirección de contacto: contacto@nekmo.com
XMPP/Jabber: contacto@nekmo.com
Google+: Nekmo Com

2015-04-27 3:02 GMT+02:00 Lee, Byoung-young <notifications@github.com>:

**Comment by xylosper** [comment]
Those method are proper for some static text for instance, button text or page title.

For paragraphs, how will you apply it?
Can it handle free form text? That is, multiple continous white spaces including line breaks will be only counted once in html.

**Comment by Nekmo** [comment]
You can use a block {% trans%}. I've never tried it but Jinja should be
compatible with Django and Django have this feature.

http://stackoverflow.com/questions/8471455/how-to-enable-trans-tag-for-jinja-templates
http://mikhail.io/2012/07/26/enable-jinja2-and-i18n-translations-on-google-appengine/
https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#trans-template-tag


Un cordial saludo:
-- Nekmo.

Sitio web: http://nekmo.com
Dirección de contacto: contacto@nekmo.com
XMPP/Jabber: contacto@nekmo.com
Google+: Nekmo Com

2015-04-27 3:18 GMT+02:00 Lee, Byoung-young <notifications@github.com>:

**Comment by xylosper** [comment]
{% blocktrans trimmed %}

It seems this would do the trick.

**Comment by Nekmo** [comment]
We can use Django templates to compile the web. It's possible. But Django is big and would be preferable to something like Jinja2. I'll try to find a solution using Jinja2 first.
