### ISSUE TITLE
PPA Repository 404 error

### ISSUE THREAD

**Issue by 1kko** [xylosper/bomi#335]
Hello, 
I tried to install bomi from your ppa, but it seems to broken.
adding ppa was fine but, "apt update" says provided ppa link is broken.

I'm currently using Ubuntu 14.04.
```
$ uname -a
Linux ikkopas 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Here's what I did:

```
$ apt-add-repository ppa:darklin20/bomi
bomi is a multimedia player formerly known as CMPlayer.
For more informations, please visit http://bomi-player.github.io
.....
OK
$ sudo apt-get update
...
W: Failed to fetch https://launchpad.net/~darklin20/+archive/ubuntu/bomi/dists/trusty/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://launchpad.net/~darklin20/+archive/ubuntu/bomi/dists/trusty/main/binary-i386/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.
$ 
```

**Comment by xylosper** [comment]
Well, there's really nothing I can do for server error.
The server itself is maintained by launchpad, and I cannot control anything.
If you have problem with connection, you'd better contact with launchpad.net.

Anyway, it may be an temporary connection disorder in server or your internet provider.
If it's not recovered, you can try to download pacakge from website directly and install it by yourself.
https://launchpad.net/~darklin20/+archive/ubuntu/bomi/+packages
Click 'bomi - 0.9.9ppa2~trusty1' and choose 'bomi_0.9.9ppa2~trusty1_amd64.deb' for 64bit or 'bomi_0.9.9ppa2~trusty1_i386.deb' for 32bit in 'Package files'.
