### ISSUE TITLE
playlist

### ISSUE THREAD

**Issue by yueunseon** [xylosper/bomi#337]
플레이리스트 파일을 pls m3u m3u8을 지원하는 건가요? xspf는 잘 안 쓰이나요?
Ctrl F 파일열기에서는 비디오나 오디오 이미지 파일만 열 수 있더군요.
플레이리스트 파일을 열려면 도구 - 재생목록 - 열기를 통하거나
혹은 드래그 앤 드롭을 써야하던데
기본 파일 열기에서도 바로 할 수 있었으면 좋겠어요.
그리고 지원하는 플레이리스트 파일 확장자가 무엇무엇인지 확인할 수도 있었으면 좋겠어요.
근데 보통 많이 쓰이고 플랫폼 공유에 가장 무리 없는 플레이리스트 확장자가 pls 인지 궁금합니다.

**Comment by xylosper** [comment]
말씀하신대로 pls m3u m3u8 이렇게 3개 지원중이고, 현재 cue sheet를 추가하는 작업중입니다.
전 따로 플레이리스트를 만들어서 쓰지 않아서 xspf가 잘 쓰이는지 안쓰이는지는 모르겠습니다.

딱히 공유하기에 뭐가 좋다는 건 없고, 사용하는 프로그램이 지원하면 됩니다.
저라면 텍스트 인코딩을 UTF-8로 정하고 있어서 인코딩을 헷갈릴일이 없는 m3u8을 쓸거 같습니다.

**Comment by xylosper** [comment]
> 기본 파일 열기에서도 바로 할 수 있었으면 좋겠어요.

추가하였습니다.

> 지원하는 플레이리스트 파일 확장자가 무엇무엇인지 확인할 수도 있었으면 좋겠어요.

어디서 확인하기를 원하시나요?
