### ISSUE TITLE
Incorrect program name in setup wizard

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#339]
Run the bomi-setup.exe on Windows 8.1 (zh-CN).
I see the incorrect program name, it uses `<DisplayName xml:lang="ko">보미</DisplayName>` instead of `<DisplayName>bomi</DisplayName>` as a fallback.

Screenshots:
http://i.imgur.com/s2vtgbG.png
http://i.imgur.com/bvTlCvo.png

**Comment by xylosper** [comment]
I've updated installer. Can you re-download and try again?

**Comment by yfdyh000** [comment]
Looks fixed, thank you.

The patch is not in this repo?

**Comment by xylosper** [comment]
it's fixed in installer framework.
