### ISSUE TITLE
Feature request: add the ability to change the size of the preview frame.

### ISSUE THREAD

**Issue by bob-art** [xylosper/bomi#341]
A very interesting feature - a preview of the frame, thanks!
But in some cases, a preview look too large - this occurs when a large window size and fullscreen (e.g. monitors > 22" ) 
I'm understand, that the size of the preview is tied to the size of the window - you can give a change the size of the preview just as it can be done in the case of (e.g.) subtitles? 
For example: 5% from window size (hight of the window, or whatever you want), 10% from... - or something like that?

**Comment by xylosper** [comment]
Done. Thank you.

**Comment by bob-art** [comment]
How fast! Thank you! 

PS.  "10 % of height" - exactly what i needed! =)
