### ISSUE TITLE
`% of height` need a placeholder for i18n

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#343]
To make it easier international, it requires a variable placeholders instead of string concatenation, so that the percentage can be placed in translation tail.

https://github.com/xylosper/bomi/blob/e580c4876aeb7c6c63c127994ee5f4d03dc84b11/src/bomi/ui/osdthemewidget.ui#L120

**Comment by xylosper** [comment]
Well, it's not possible unless reimplement spinbox.
In my case(Korean), I'm translating it to '%(화면높이기준)' which means '%(畵面高基準)'(I hope you can understand these characters because I remember you're the chinese translator).

**Comment by yfdyh000** [comment]
okay, I understand now.
