### ISSUE TITLE
` (struct ao_device_desc){"auto", "Autoselect device"});` should can be l10n

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#344]
https://github.com/xylosper/bomi/blob/68f87f235364cfa3d67ec89f7ab6a0221f29bece/src/mpv/audio/out/ao.c#L523

**Comment by xylosper** [comment]
I think 'auto' as a name of device such as alsa or jack and I'll make 'Autoselect device' only translatable.
Do you agree? Or, do you think "auto" should be translatable, too?

**Comment by yfdyh000** [comment]
I don't oppose this point, the description have enough to explain it.
And the 'auto' may be used in certain places (such as command-line arguments).
Thanks.

**Comment by yfdyh000** [comment]
I don't see it.

**Comment by xylosper** [comment]
Fixed. It seems that lupdate failed to parse the source code in certain corner case. Thanks.
