### ISSUE TITLE
typo for "Sharpness"

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#345]
Sharp**e**ness -> Sharpness by Google.

It totals 15 in https://github.com/xylosper/bomi/blob/584803de65259e161d9d58d7ec0b1ef147572d7d/src/bomi/video/interpolatorparams.cpp.

**Comment by xylosper** [comment]
Fixed. Thank you.

**Comment by yfdyh000** [comment]
For https://github.com/xylosper/bomi/commit/3cbeaa8fe40c23eecb9cefb1fc4f6790e71c77a6, it is no changes the internal name, although it is not presented to users. Just a reminder / opinion.
