### ISSUE TITLE
i18n for context menu of All text fields

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#346]
Like the QLabel, QSpinBox, QDoubleSpinBox, etc fields.

Maybe it is an upstream bug?

**Comment by xylosper** [comment]
I'm not sure which part you're talking about.
There's no label/spinbox or any controls in context menu.

**Comment by yfdyh000** [comment]
Right-click a can fill box in the Preferences or subtitle viewer, these items label of context menu is always in English, at least for me in Windows 8.1 (zh-CN).

**Comment by xylosper** [comment]
Those strings are in Qt and the translation file for Qt for zh-CN was never distributed with bomi for Windows. In next version, it will be included.
