### ISSUE TITLE
"Click to display" cannot be l10n

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#348]
https://github.com/xylosper/bomi/blob/9e7a86d81f9cfcc1ccfa7294823b188ae9680426/src/bomi/imports/bomi/AutoDisplayZone.qml#L29

I don't see it being translatable.

And the https://github.com/xylosper/bomi/blob/1961754aecb7287e89db28e293a507fbe182d15e/src/bomi/imports/bomi/HistoryView.qml#L64.

**Comment by yfdyh000** [comment]
And the https://github.com/xylosper/bomi/blob/1961754aecb7287e89db28e293a507fbe182d15e/src/bomi/imports/bomi/HistoryView.qml#L98.

**Comment by xylosper** [comment]
Fixed. Thanks.
