### ISSUE TITLE
Channel description need to be translatable

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#350]
https://github.com/xylosper/bomi/blob/3738315cc2ad2524ae6c597b0b9ee448cddce508/src/bomi/audio/channellayoutmap.cpp#L13

**Comment by xylosper** [comment]
It's intentional because once 'Front Left' translated to non-english language, it's hard to notice FL denotes 'Front Left'.

**Comment by yfdyh000** [comment]
I want to translate the descriptions instead of names, like the "Low Frequency Effects" is incomprehensible for non-English users.

**Comment by xylosper** [comment]
Done.
