### ISSUE TITLE
Questions: What is "Crop" and "Soft"?

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#351]
* I don't understand the "[Crop](https://github.com/xylosper/bomi/blob/master/src/bomi/player/rootmenu.cpp#L388)", any difference with "Aspect Ratio"? I don't see any effect with it.
* In addition, any popular definition for "[Soft](https://github.com/xylosper/bomi/blob/master/src/bomi/audio/audioequalizer.cpp#L51)" in AudioEqualizer?

**Comment by xylosper** [comment]
> I don't understand the "Crop", any difference with "Aspect Ratio"? I don't see any effect with it.

'Video > Crop' was broken. It's fixed now.
'Video > Crop' will crop the video to fit given ratio, if the window does not match with given ratio.
If the window can show full video frame, 'Video > Crop' does nothing.
Set crop ratio and try adjust window size, then you'll notice something.

'Video > Aspect Ratio' adjust aspect ratio of video frame to fit given ratio.
It will distort video frame if aspect ratio doesn't match.

> In addition, any popular definition for "Soft" in AudioEqualizer?

I have no knowledge for equalier. The name of preset is copied from VLC which is copied from xmms, again.
