### ISSUE TITLE
"Start" button label of encoder window cannot be l10n

### ISSUE THREAD

**Issue by yfdyh000** [xylosper/bomi#352]
I see it in .ts file, but the button label is not show as translation using Release as .qm file.

I seen the line number seem is wrong (line 105, actually is 108), it may be not relevant, I once modify it and Release as .qm file, but the not works for the button label l10n.

https://github.com/xylosper/bomi/blob/fab2efcdfc7877cab7cd6bc516a6cbcf715d75a5/src/bomi/dialog/encoderdialog.cpp#L108

**Comment by xylosper** [comment]
I've tried your translation and I can see it's translated.
Line number is just hint for Linguist to display code line.
It does have no effect for translation.

**Comment by yfdyh000** [comment]
Looks works fine in 0.9.10.
