### ISSUE TITLE
Preview fail with youtube video.

### ISSUE THREAD

**Issue by mac1202** [xylosper/bomi#355]
Hi when you enable the choose quality option for youtube video and select separate video and audio track like [this](http://i.imgur.com/Bs8rp5X.png) preview doesn't work and i got this error in log :
    
    (E)[mpv/preview/cache] Cache keeps not responding.

I got no problem when choosing video+audio muxed together like [this](http://i.imgur.com/l9o5viL.png).

**Comment by xylosper** [comment]
I don't think this is relavant with DASH format(audio/video separated ones).
In fact, I don't have any problem to display preview with DASH.
Does this problem occur always all DASH formats?

Well, there's still a possibility your log says the whole point.
Normal format requires one connection(+one for preview) but DASH format requires two connections(+one for preview), so maybe your network is stuck.
Just in case, can you let me know the URL you tested?

**Comment by mac1202** [comment]
I use this video for testing https://youtube.com/watch?v=Y9b1gBTztCI but i got the same result with other video. After more testing i found that the problem occurs with DASH video in mp4 format. If i select the webm one (same resolution and fps) the preview work properly.

**Comment by xylosper** [comment]
That makes my guess that your network stuck more plausible because generally, webm/vp is better for streaming than mp4/h264, unless your internet connection is good enough.

**Comment by xylosper** [comment]
I have an idea.
The preview does not require high resolution, it would be better to choose low quality source.
Before applying that, I want to know which factor impacts more for performance between container and resolution.
I know webm is better than mp4 when the resolution is high from your comment.
Now I want to know this is still true for low resolution.
Can you check if the preview work for you when you select low resolution (240p or 360p) with mp4 and webm respectively?

**Comment by mac1202** [comment]
I do more testing, in fact the preview work but it take more than 10sec for the window preview appear for the first time in mp4 format and with any resolution (from 1920x1080 to 256x144). After that the preview work properly. With webm the preview window appear instantly with any resolution.

**Comment by xylosper** [comment]
Fixed.

FYI, the dialog to ask video quality removed.
Now you can configure default video quality in preference and you can change format through 'Play > Streaming Format' menu while playing.
