### ISSUE TITLE
cann't display  ssa/ass subtitle (windows)

### ISSUE THREAD

**Issue by yg-yu** [xylosper/bomi#362]
cann't display  ssa/ass subtitle in win7(x64), bomi download from bomi-player.github.io, srt subtitle and osd work well. mpv binary download  from http://mpv.srsfckn.biz/ and bomi linux edition both not have this problem（same subtitles file）。

# Some Log
(I)[Charset] Trying encoding autodetection: E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass
(I)[Charset] Encoding detected: UTF-8 (confidence: 0.99)
(I)[Subtitle] Trying (parser: SAMI, encoding: UTF-8, file: E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass): false
(I)[Subtitle] Trying (parser: SubRip, encoding: UTF-8, file: E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass): false
(I)[Subtitle] Trying (parser: MicroDVD, encoding: UTF-8, file: E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass): false
(I)[Subtitle] Trying (parser: TMPlayer, encoding: UTF-8, file: E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass): false
(I)[Subtitle] Load E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass with UTF-8: failed
(D)[mpv/cplayer] Set property string: options/subcp='UTF-8'
(D)[mpv/cplayer] Run command: sub_add, flags=0, args=[E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass, auto, , ]
(D)[mpv/file] Opened: E:/Users/user/Desktop/The Movie(2014) 720p HDRip XviD AC3 RDLinks-eng.ass
(D)[mpv/demux] Trying demuxer: disc (force-level: normal)
(D)[mpv/demux] Trying demuxer: edl (force-level: normal)
(D)[mpv/demux] Trying demuxer: cue (force-level: normal)
(D)[mpv/demux] Trying demuxer: rawaudio (force-level: normal)
(D)[mpv/demux] Trying demuxer: rawvideo (force-level: normal)
(D)[mpv/demux] Trying demuxer: libass (force-level: normal)
(D)[mpv/demux] Detected file format: ASS/SSA subtitles (libass)
(D)[mpv/cplayer] Set property: sub-pos=100
(D)[mpv/cplayer] Set property: ass-force-margins=false
(D)[mpv/cplayer] Set property: sub-scale=1.200000
(D)[mpv/cplayer] Set property: sid=1
(D)[mpv/sub] Subtitle filter chain: ass (ass)
(D)[mpv/global] config path: 'subfont.ttf' -> '(NULL)'
(D)[mpv/global] config path: 'fonts.conf' -> '(NULL)'
(D)[mpv/libass] Setting up fonts...
(I)[mpv/libass] No usable fontconfig configuration file found, using fallback.
(D)[mpv/libass] Done.
(D)[mpv/libass] EOF reached.
(D)[mpv/cplayer] Set property: sub-pos=100
(D)[mpv/cplayer] Set property: ass-force-margins=false
(D)[mpv/cplayer] Set property: sub-scale=1.000000
(I)[mpv/libass] Neither PlayResX nor PlayResY defined. Assuming 384x288
(D)[mpv/cplayer] Set property: pause=true
(D)[mpv/cplayer] Set property: pause=false
(D)[mpv/cplayer] Set property string: ass-style-override='yes'
(D)[mpv/cplayer] Set property string: ass-style-override='force'
(D)[mpv/cplayer] Run command: seek, flags=0, args=[2222.760000, relative, unused]
(D)[mpv/cplayer] Run command: seek, flags=0, args=[3383.378000, relative, unused]
(D)[mpv/cplayer] Run command: seek, flags=0, args=[4318.907000, relative, unused]
(D)[mpv/cplayer] Set property: pause=true

**Comment by xylosper** [comment]
Can you provide the ass file?

**Comment by yg-yu** [comment]
not a special ass subtitle  file，all of external ass subtitles can't display.
below are two  ass subtitle in opensubtitles.org. both can display in mpv, but not in bomi, I have tested.
http://dl.opensubtitles.org/en/download/sub/3566617
http://dl.opensubtitles.org/en/download/sub/6073446

**Comment by xylosper** [comment]
Please test one thing for me.
Copy `mpv` folder and `fonts` folder in downloaded mpv 7z archive into where bomi installed and check if you can see subtitles.

**Comment by yg-yu** [comment]
Yes, copy  mpv's font (Noto san CJK  Font) and fonts.conf to bomi intalled path, bomi can display subtitles. And bomi will not search  fonts.conf in  \Path To Bomi\mpv\ . must copy fonts.conf  to \Path to Bomi\fonts\, Bomi can find fontconfig configuration and display subtitle well. Beside，The Noto san font In \fonts\ is necessary, Becase bomi can't find any font  which have installed in windows.
 (I)[mpv/libass] fontconfig: cannot find font 'Arial', falling back to 'Noto Sans'.

**Comment by yg-yu** [comment]
Yes, copy  mpv's font (Noto san CJK  Font) and fonts.conf to bomi intalled path, bomi can display subtitles. And bomi will not search  fonts.conf in  \Path To Bomi\mpv\ . must copy fonts.conf  to \Path to Bomi\fonts\, Bomi can find fontconfig configuration and display subtitle well. Beside，The Noto san font In \fonts\ is necessary, Becase bomi can't find any font  which have installed in windows.
 (I)[mpv/libass] fontconfig: cannot find font 'Arial', falling back to 'Noto Sans'.

**Comment by yg-yu** [comment]
Yes, copy  mpv's font (Noto san CJK  Font) and fonts.conf to bomi intalled path, bomi can display subtitles. And bomi will not search  fonts.conf in  \Path To Bomi\mpv\ . must copy fonts.conf  to \Path to Bomi\fonts\, Bomi can find fontconfig configuration and display subtitle well. Beside，The Noto san font In \fonts\ is necessary, Becase bomi can't find any font  which have installed in windows.
 (I)[mpv/libass] fontconfig: cannot find font 'Arial', falling back to 'Noto Sans'.

**Comment by xylosper** [comment]
Yeah, that's because libass which is used for rendering ASS subs utilizes fontconfig to find font and fontconfig is not really supposed to be used other than Linux. To be precise, fontconfig can be used only if the font system is already integrated with fontconfig so that the fontconfig cache is reliable.
I'm trying to replace fontconfig in libass with some kind of native API but for now, no successful result yet.
Anyway, I'll include font related files into windows binary archives. Thank you for testing!

**Comment by yg-yu** [comment]
Thank you develop bomi a powerful and easy-to-use multimedia player.

**Comment by xylosper** [comment]
Here's a test build: http://sourceforge.net/projects/bomi/files/windows/test/bomi-x86_64-20150520105225.7z/download
Please check if it works for you.

**Comment by yg-yu** [comment]
work well

**Comment by xylosper** [comment]
Thank you for testing. Next version will work for you then.
