### ISSUE TITLE
Deadlock on stream seeking

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/bomi#363]
Bomi deadlocks thread and consumes 100% CPU on stream seeking.

1) Open any youtube video
2) Seek it

Expected result:
Video continues to play from seek position

Actual result:
Video is not played and bomi consumes 100% cpu.

**Comment by xylosper** [comment]
Have you tried non DASH format in Play > Streaming Format?

**Comment by ValdikSS** [comment]
Yes, I never tried DASH. I use mp4 720.

**Comment by xylosper** [comment]
I can't reproduce your problem.
However, I've just updated mpv source tree and it contains a fix for a high CPU usage situation.
Can you test with latest source?
And, if you still have problem, can you post any URL to reproduce your problem?

**Comment by ValdikSS** [comment]
The issue is still here somehow. If I seek youtube stream, sometimes both video and audio are stuck or video only (audio plays fine). Bomi still consumes 100% CPU on seeking.
I believe this could be of not very high speed internet.

Please check "update mpv" commit, there is something with the audio volume.

**Comment by xylosper** [comment]
> Please check "update mpv" commit, there is something with the audio volume.

What is something?

**Comment by ValdikSS** [comment]
It's very low.

**Comment by xylosper** [comment]
I can't see any problem. Have you checked volume/amp in bomi and system volume?

**Comment by ValdikSS** [comment]
Strangely enough, it works fine now. I've checked volume and amp levels 3 times when I wrote this, and now the volume level is the same across versions. Sorry about that.

**Comment by ValdikSS** [comment]
Oh wait, it seems like with the mpv update, bomi now reads mpv config file. I have softvol-max 100 in it, and it clearly alter bomi volume level.

**Comment by xylosper** [comment]
> bomi now reads mpv config file.

Fixed.

**Comment by xylosper** [comment]
I found a situation using 100% during seeking in low bandwidth and reported to mpv dev.
It's fixed in upstream and I backported the fix, so please check if it works for you.

**Comment by ValdikSS** [comment]
Just tested it. Don't see any deadlocks, and the CPU consumption is fixed. Thank you a lot!
