### ISSUE TITLE
Exponential volume control

### ISSUE THREAD

**Issue by forinti** [xylosper/bomi#364]
Hello, when I am changing the volume with the volume slider, the perceived change is not very linear, so I guess that the slider is linear and its value just multiplies the actual volume.  I think that it would be much more pleasant if it has an exponential characteristic and therefore it would compensate the human perception, which is logarithmic. Many programs has this feature. Thank you.

More about this: http://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by xylosper** [comment]
Done. Default dynamic range 60dB as your link suggested and it's configurable. Thank you!

**Comment by forinti** [comment]
Amazing! Thank you very much.
