### ISSUE TITLE
Subtitles ignore \n \N for new line

### ISSUE THREAD

**Issue by DoTheEvo** [xylosper/bomi#365]
Its used pretty widely
tested both linux/windows

Example of subtitles
http://subscene.com/subtitles/the-pianist-2002/english/779314

**Comment by xylosper** [comment]
I cannot find reference for \n but \N. Do you have any .srt using \n intentionally for line breaking?

**Comment by DoTheEvo** [comment]
Dunno why I said both, I just assumed I guess, I encountered \N as far as I remember

**Comment by xylosper** [comment]
Okay, then it's fixed. Thank you.
