### ISSUE TITLE
Crash: on youtube pause -> play

### ISSUE THREAD

**Issue by famo** [xylosper/bomi#369]
Hey,
if you pause a yt video long enough bomi crashes on resume.

How to reproduce:
1. Open an arbitrary yt-URL (e.g. https://www.youtube.com/watch?v=EFwAAjutC_0) and start playback
2. Hit pause and wait a couple of minutes (didn't test exactly, maybe 2 minutes or more)
3. Hit play
-> bomi crashes

Notice:  I think its because the URL of the video is no longer available. Which is OK, so bomi should just be blank, put an error, etc, but NOT crash...

ty

**Comment by xylosper** [comment]
maybe same bug which is already fixed by 783f989. Can you test it?

**Comment by famo** [comment]
Tested in 0.9.10. and it crashes.

**Comment by xylosper** [comment]
783f989 is not in 0.9.10.

**Comment by famo** [comment]
Sorry, I cannot test it then. However I will test it as soon as my distro ships it and report back to you.

Does this come with the next release?

**Comment by xylosper** [comment]
Yes, it will.

**Comment by xylosper** [comment]
New version updated. Can you test it?
