### ISSUE TITLE
Audio not muted when volume is 0

### ISSUE THREAD

**Issue by forinti** [xylosper/bomi#376]
Hello, after the audio dynamic range change in 54ba8b74da2f1c38a05263eed875b174418503c4, I am still able to hear the sound when the volume is 0. If my calculations are correct then, when dynamic range is 60 and volume is 0, then x will be equal to 1e-3 and therefore it will not be fulfil the condition 
else if(x<1e-8) x = 0;

Maybe something like this could work?
if (volumeScale > 0 && x > 0) {
...

Thank you

**Comment by xylosper** [comment]
Fixed. Thank you!
