### ISSUE TITLE
Rewind Forward, Back,Frame by Frame

### ISSUE THREAD

**Issue by nosscireb** [xylosper/bomi#378]
Hi! How about make shorter time jump to about 5 seconds when pressed left/right arrow key? Or even make it adjustable.Why is it so important for me?I watch a lot of movies, also in English which is not my native language.So very often while I watch movie I can not understand or miss  a word or a phrase, so I want to go back for a let's say 5 seconds, but instead I jump back for 20 seconds and that's way to much and very inconvenient!
 Another feature that isn't in Bomi - playback frame by frame.You put movie on pause, and then by pressing key( let's say "F" key) you go forward frame by frame.Should I explain why would it be very convenient feature? 
There is a player with such features but it's for Windows and I don't want to run it in Wine.
Regarding jumps of 5-10 seconds,maybe I can fix it by simple changing some variable in your source code.Could you tell me what variable I should look for? Thanks.

**Comment by kehugter** [comment]
>>Or even make it adjustable

It is :). Preferences -> Control step.

The "frame by frame" reproduction can be archived by slowing the speed (`-`) or, fine tuned, with `Alt`+`right` and `Alt`+`left`.

**Comment by xylosper** [comment]
> So very often while I watch movie I can not understand or miss a word or a phrase, so I want to go back for a let's say 5 seconds, but instead I jump back for 20 seconds and that's way to much and very inconvenient!

Default value for seeking byleft/right arrow is 5 sec. If you observe 20 sec seeking when you hit left/right arrow, that's because your video provide sparse keyframe. If you want to enforce exact seeking, check Preferences > Play > Use precise seeking regardless of key frame.

For other questions, I think kehugter's answer is enough.

**Comment by nosscireb** [comment]
Thanks a lot guys! You helped me very much! Pleased your quick and exact response.
