### ISSUE TITLE
Scrolling on timeline broken?

### ISSUE THREAD

**Issue by famo** [xylosper/bomi#379]
IIRC it was possible in bomi to mouse-wheel-scroll on the timeline, in order to seek forward/backward.

This doesn't work here anymore.

Or if I'm mistaken and it wasn't please implement such feature as it is very useful and present in other players.

**Comment by xylosper** [comment]
It's disabled explicitly for both of volume slider and time slider on purpose because I thought noone needed that.
Now at least you needs it, so I've enabled wheel event for time slider.

**Comment by famo** [comment]
Oh, I didn't noticed it was disabled for volume as well.
Please enable it there as well.

IMHO using the mouse wheel on a slider is just a commen GUI thing, also it is so common in other media players...

Thanks!
