### ISSUE TITLE
Show Video Size instead of Window Size

### ISSUE THREAD

**Issue by famo** [xylosper/bomi#382]
On rescaling the window bomi shows in the upper left corner the size of the window.
However I think it would be better to show the actual size of the video.

The size of the window you can also get (/shown) from your window manager.
If you go fullscreen it just shows you (always) the size of your desktop resolution.
I think size of video is just more of interest...

**Comment by xylosper** [comment]
Done. Thank you.

**Comment by famo** [comment]
Thank you too!
Also a quick thought, maybe it would be even of interest to indicate the scaling of the video, e.g.
1920 x 1080 - 100%,
960 x 540 - 50%  etc...
(for a 1920 x 1080 video).

However I'm not so sure about it...
