### ISSUE TITLE
hardware acceleration is not enabled and cannot be enabled

### ISSUE THREAD

**Issue by dissu** [xylosper/bomi#383]
Hello, I build bomi player from source code cloned from https://github.com/xylosper/bomi.git and build was ran well, but when I run bomi player it shows the below error messages and video playing was lagging.

~/BOMI/bin$ ./bomi 
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
(E)[VAAPI] Error: unknown libva error(0xffffffffffffffff) Cannot initialize VA-API.
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
(E)[VDPAU] Error: Unknown error code(0x1) Cannot intialize VDPAU device
(I)[X11] No available hardware acceleration API.
QCommandLineParser: option not defined: "__dummy__"
QCommandLineParser: option not defined: "__dummy__"
QCommandLineParser: option not defined: "__dummy__"
QCommandLineParser: option not defined: "__dummy__"

So I checked Tool >> Preference >> Hardware Acceleration and I saw hardware acceleration is not supported in the Bomi player I built.
if you know some solution or advice on this problem, could you tell me some?

![screenshot from 2015-05-31 10 44 29](https://cloud.githubusercontent.com/assets/5896370/7900168/082c30f8-0782-11e5-9fb5-a62751eeaef6.png)

**Comment by xylosper** [comment]
What is your GPU/distro and did you install driver for hardware acceleration?

**Comment by dissu** [comment]
My GPU is GeForce GTX 750, Linux distro is Ubuntu 15.04 and I installed GPU driver.

![screenshot from 2015-05-31 16 15 57](https://cloud.githubusercontent.com/assets/5896370/7901040/5ebc5546-07b0-11e5-8f90-c2258a9fa9aa.png)


When I run the build script, I could see many 'no' and 'not found' and 'disabled'. 
Could them be the problem? 

'clean' finished successfully (0.014s)
'distclean' finished successfully (0.003s)
Setting top to                           : /home/csjeong/bomi/src/mpv 
Setting out to                           : /home/csjeong/bomi/src/mpv/build 
Checking for waf version in 1.8.4-1.9.0  : ok 
Checking for program 'cc'                : /usr/bin/gcc 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for program 'ar'                : /usr/bin/ar 
Checking for program 'perl'              : /usr/bin/perl 
Checking for program 'rst2man'           : not found 
Checking for program 'rst2pdf'           : not found 
Checking for program 'windres'           : not found 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Detected target OS:                      : os-linux 
Checking for compiler flags -Werror=implicit-function-declaration : yes 
Checking for compiler flags -Wno-error=deprecated-declarations    : yes 
Checking for compiler flags -Wno-error=unused-function            : yes 
Checking for compiler flags -Wempty-body                          : yes 
Checking for compiler flags -Wdisabled-optimization               : yes 
Checking for compiler flags -Wstrict-prototypes                   : yes 
Checking for compiler flags -Wno-format-zero-length               : yes 
Checking for compiler flags -Werror=format-security               : yes 
Checking for compiler flags -Wno-redundant-decls                  : yes 
Checking for mpv CLI player                                       : disabled 
Checking for shared library                                       : disabled 
Checking for static library                                       : yes 
Checking for static build                                         : disabled 
Checking for whether to include binary compile time               : yes 
Checking for whether to optimize                                  : yes 
Checking for whether to compile-in debugging information          : yes 
Checking for manpage generation                                   : disabled 
Checking for pdf manual generation                                : disabled 
Checking for dynamic loader                                       : yes 
Checking for dlopen                                               : yes 
Checking for compilation of default filters for vf_dlopen         : disabled 
Checking for zsh completion                                       : disabled 
Checking for inline assembly (currently without effect)           : yes 
Checking for test suite (using cmocka)                            : disabled 
Checking for generate a clang compilation database                : disabled 
Checking for compiler support for noexecstack                     : yes 
Checking for linker support for --nxcompat --no-seh --dynamicbase : no 
Checking for -lm                                                  : yes 
Checking for MinGW                                                : os-win32 not found 
Checking for POSIX environment                                    : yes 
Checking for development environment                              : yes 
Checking for win32                                                : not found any of os-win32, os-cygwin 
Checking for internal pthread wrapper for win32 (Vista+)          : disabled 
Checking for POSIX threads                                        : yes 
Checking for stdatomic.h                                          : yes 
Checking for compiler support for __atomic built-ins              : stdatomic found 
Checking for compiler support for __sync built-ins                : stdatomic found 
Checking for compiler support for usable thread synchronization built-ins : yes 
Checking for linking with -lrt                                            : yes 
Checking for iconv                                                        : yes 
Checking for w32/dos paths                                                : not found any of os-win32, os-cygwin 
Checking for libwaio for win32                                            : mingw, os-win32 not found 
Checking for termios                                                      : disabled 
Checking for shm                                                          : disabled 
Checking for nanosleep                                                    : yes 
Checking for POSIX spawnp()/kill()                                        : yes 
Checking for posix_spawnp() or MinGW                                      : yes 
Checking for glob()                                                       : yes 
Checking for glob() win32 replacement                                     : not found any of os-win32, os-cygwin 
Checking for fchmod()                                                     : yes 
Checking for vt.h                                                         : yes 
Checking for GLIBC API for setting thread name                            : yes 
Checking for OSX API for setting thread name                              : glibc-thread-name found 
Checking for BSD API for setting thread name                              : glibc-thread-name found 
Checking for NetBSD API for setting thread name                           : glibc-thread-name found 
Checking for BSD's fstatfs()                                              : no 
Checking for Linux's fstatfs()                                            : yes 
Checking for libguess support                                             : disabled 
Checking for Samba support                                                : yes 
Checking for Lua                                                          : disabled 
Checking for SSA/ASS support                                              : yes 
Checking for libass OSD support                                           : yes 
Checking for dummy OSD support                                            : libass-osd found 
Checking for zlib                                                         : yes 
Checking for Encoding                                                     : yes 
Checking for Bluray support                                               : yes 
Checking for dvdread support                                              : yes 
Checking for dvdnav support                                               : yes 
Checking for cdda support (libcdio)                                       : yes 
Checking for ENCA support                                                 : disabled 
Checking for LADSPA plugin support                                        : disabled 
Checking for librubberband support                                        : disabled 
Checking for libbs2b audio filter support                                 : disabled 
Checking for LCMS2 support                                                : disabled 
Checking for VapourSynth filter bridge (core)                             : no ('vapoursynth >= 24' not found) 
Checking for VapourSynth filter bridge (Python)                           : disabled 
Checking for VapourSynth filter bridge (Lazy Lua)                         : disabled 
Checking for SDL2                                                         : disabled 
Checking for SDL (1.x)                                                    : disabled 
Checking for OSS (implementation from opensound.com)                      : no 
Checking for OSS (platform-specific OSS implementation)                   : yes 
Checking for OSS (emulation on top of SunAudio)                           : oss-audio-native found 
Checking for OSS audio output                                             : yes 
Checking for RSound audio output                                          : disabled 
Checking for sndio audio input/output                                     : disabled 
Checking for PulseAudio audio output                                      : yes 
Checking for JACK audio output                                            : yes 
Checking for OpenAL audio output                                          : disabled 
Checking for ALSA audio output                                            : yes 
Checking for CoreAudio audio output                                       : no 
Checking for DirectSound audio output                                     : no 
Checking for WASAPI audio output                                          : win32 not found 
Checking for Cocoa                                                        : disabled 
Checking for Wayland                                                      : disabled 
Checking for X11                                                          : disabled 
Checking for Xss screensaver extensions                                   : disabled 
Checking for X extensions                                                 : disabled 
Checking for Xv video output                                              : disabled 
Checking for Xinerama                                                     : disabled 
Checking for Xrandr                                                       : disabled 
Checking for OpenGL Cocoa Backend                                         : cocoa not found 
Checking for OpenGL X11 Backend                                           : x11 not found 
Checking for OpenGL X11 EGL Backend                                       : disabled 
Checking for OpenGL Wayland Backend                                       : wayland not found 
Checking for OpenGL Win32 Backend                                         : win32 not found 
Checking for OpenGL Dummy Backend                                         : yes 
Checking for VDPAU acceleration                                           : yes 
Checking for Video Output for VDPAU acceleration                          : disabled 
Checking for VDPAU with OpenGL/X11                                        : yes 
Checking for VAAPI acceleration                                           : yes 
Checking for Video Output for VAAPI acceleration                          : disabled 
Checking for VAAPI VPP                                                    : disabled 
Checking for VAAPI GLX                                                    : yes 
Checking for CACA                                                         : disabled 
Checking for DRM                                                          : disabled 
Checking for JPEG support                                                 : disabled 
Checking for Direct3D support                                             : disabled 
Checking for Raspberry Pi support                                         : no 
Checking for GLES on Raspberry Pi                                         : rpi not found 
Checking for OpenGL video outputs                                         : yes 
Checking for libav/ffmpeg                                                 : yes 
Checking for libswresample                                                : yes 
Checking for libavresample                                                : disabled 
Checking for usable resampler found                                       : yes 
Checking for libavfilter                                                  : disabled 
Checking for libavdevice                                                  : disabled 
Checking for libavcodec avcodec_enum_to_chroma_pos API                    : yes 
Checking for libavutil AVFrame metadata                                   : yes 
Checking for libavutil AVFrame skip samples metadata                      : yes 
Checking for libavutil AV_PIX_FMT_MMAL                                    : no 
Checking for libavcodec VAAPI hwaccel                                     : yes 
Checking for libavcodec VDA hwaccel                                       : no 
Checking for libavcodec VDA hwaccel (configurable AVVDAContext)           : vda-hwaccel not found 
Checking for VDA with OpenGL                                              : disabled 
Checking for libavcodec VDPAU hwaccel                                     : yes 
Checking for libavcodec DXVA2 hwaccel                                     : not found any of os-win32, os-cygwin 
Checking for TV interface                                                 : disabled 
Checking for videoio.h                                                    : no 
Checking for videodev2.h                                                  : yes 
Checking for Video4Linux2 TV interface                                    : disabled 
Checking for libv4l2 support                                              : disabled 
Checking for Video4Linux2 MPEG PVR interface                              : disabled 
Checking for audio input support                                          : disabled 
Checking for DVB input module                                             : disabled 
Checking for w32 executable                                               : not found any of os-win32, os-cygwin 
Checking for Apple Remote support                                         : cocoa not found 
Writing configuration header:                                             : config.h 
Writing header:                                                           : version.h

**Comment by xylosper** [comment]
You should never care those messages. What you should care is the result of ./configure script.
Graphics driver is not hardware acceleration driver.
Also, in Ubuntu, you have to install separated libvdpau-dev pacakge if you want to build with vdpau support.

**Comment by dissu** [comment]
the below is ./configure script argument and the result of the script.
vdpau checking has been passed

$ ./configure --qtsdk=/home/dissu/Qt5.4.1/5.4/gcc_64/ --release 
configure for Linux...
Checking for ffmpeg >= 2.4 ... yes
Checking for libass >= 0.12.1 ... yes
Checking for dvdread ... yes
Checking for dvdnav ... yes
Checking for libbluray ... yes
Checking for chardet ... yes
Checking for glib ... yes
Checking for xcb ... yes
Checking for alsa ... yes
Checking for jack ... yes
Checking for libpulse ... yes
Checking for libcdio_paranoia libcdio libcdio_cdda ... yes
Checking for smbclient ... yes
Checking for libsystemd ... yes
Checking for vdpau ... yes
Checking for libva libva-glx libva-x11 ... yes
checking for cc ... gcc
checking for qmake ... /home/csjeong/Qt5.4.1/5.4/gcc_64//bin/qmake
checking for lrelease ... /home/csjeong/Qt5.4.1/5.4/gcc_64//bin/lrelease
checking for mkspec ... linux-g++


![screenshot from 2015-05-31 17 04 41](https://cloud.githubusercontent.com/assets/5896370/7901197/2e08b028-07b7-11e5-89a1-ba22297d80af.png)
and I think I have installed all 'vdpau' related packages.

**Comment by xylosper** [comment]
What's the result of `$ find /usr/lib -name 'libvdpau_nvidia.so*'?

**Comment by dissu** [comment]
As you mentioned, It was a problem on graphics driver.(libvdpau-dev pacakge was installed)
I've reinstalled the graphics driver and now I can use the h/w acceleration functionality of bomi player.
Sorry, I saw your comment after I reinstalled the driver, so I cannot give the result of 'find /usr/lib -name 'libvdpau_nvidia.so*' when I have the problem.

Now the result of find /usr/lib -name 'libvdpau_nvidia.so* seems correct.

$ find /usr/lib -name 'libvdpau_nvidia.so*'
/usr/lib/nvidia-346/vdpau/libvdpau_nvidia.so.1
/usr/lib/nvidia-346/vdpau/libvdpau_nvidia.so
/usr/lib/nvidia-346/vdpau/libvdpau_nvidia.so.346.59
/usr/lib/vdpau/libvdpau_nvidia.so.1
/usr/lib/libvdpau_nvidia.so

Thank you for your comment again.
