### ISSUE TITLE
Bug on Win 7 and XP Sp3 32 bit

### ISSUE THREAD

**Issue by Amynzo** [xylosper/bomi#384]
Hello, I found your excellent video player  by chance, it really powerful and very light and useful, it works very well under win 8 64 bits but not under win 7 32bit and Win Xp Sp3 attached an explanatory picture , Good luck for this wonderful video player ....; o))

Sorry For my bad english I use google traduction from french to english.

![bomi player win7 32 bits problem](https://cloud.githubusercontent.com/assets/12681784/7901592/d2ca3210-0787-11e5-8726-e0c15c898ad3.jpg)
![bomi player win7 32 bits-problem](https://cloud.githubusercontent.com/assets/12681784/7901594/dd7f8962-0787-11e5-9ded-78bf2a069e38.jpg)

![xp sp3](https://cloud.githubusercontent.com/assets/12681784/7901598/e8c76e66-0787-11e5-8153-e63d63613c12.jpg)

**Comment by Amynzo** [comment]
Hi  ......any answer  !!!!!!

**Comment by xylosper** [comment]
Sorry for late answer.

First of all, I don't expect that bomi works in XP. It's too outdated.

For windows 7 32bit, can you tell me what is your graphics card and driver?
Also, which screenshot corresponds to Windows 7?

**Comment by Amynzo** [comment]
Thanks ...Thanks .....Thanks a lot  it works   ;o) on Win 7 32 bits after updating  the graphics card driver....

Good luck....for the  developing of this wonderful video player.

![sans titre11111](https://cloud.githubusercontent.com/assets/12681784/8086038/4878cd04-0f8b-11e5-9a0f-ff9e6b2bfa64.jpg)

**Comment by xylosper** [comment]
Thank you!
