### ISSUE TITLE
[reminder] Arch Linux begins migration to Git based AUR 4.0

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/bomi#389]
@xylosper : this is just a reminder to update your packages.

"Starting from 2015-06-08, the Arch User Repository is being migrated to a Git-based platform. Any changes to the AUR, including package submissions, comments and votes, made after 2015-06-08 will be lost! Please use aur4.archlinux.org instead (which will be activated on June 8th). More information on AUR 4 can be found in the Arch wiki. "
https://wiki.archlinux.org/index.php/Arch_User_Repository#AUR_4

https://lists.archlinux.org/pipermail/aur-general/2015-June/030724.html

**Comment by xylosper** [comment]
I've already received notification by E-mail.
