### ISSUE TITLE
livestream in bomi

### ISSUE THREAD

**Issue by ForumLiker** [xylosper/bomi#440]
Hi. I am trying to see the broadcast using the bomi, but I getting an error.

http://storage9.static.itmages.ru/i/15/1031/h_1446317011_8782260_c6d9c9c2d2.png

**Comment by ahjolinna** [comment]
I don't think livestream is supported, but twitch does work on bomi (with youtube-dl) but livestreams are bad (for now) because of ffmpeg bug...I think it's the HLS demuxer one, but archives should work just fine.

maybe twitch livestream will get better when the HTML5 switch has happened.

**Comment by ForumLiker** [comment]
twitch work on flashplayer

**Comment by ahjolinna** [comment]
yes... twitch uses flashplayer now. But they have already started to convert the chat and the player controls to HTML5, but the videoplayback will happen sometime in 2016 (Q1 I think).

**Comment by ForumLiker** [comment]
wait a long time. I will look in the browser then. thanks for the answer.

**Comment by ahjolinna** [comment]
@ForumLiker : I notice that using: 'livestreamer -p bomi twitch.tv/name_of_channel best --player-continuous-http' worked for me...aka u need livestreamer app also https://github.com/chrippa/livestreamer

**Comment by ForumLiker** [comment]
thank. it works!
