### ISSUE TITLE
broken packages on Elementary OS 0.3.2

### ISSUE THREAD

**Issue by rasulian** [xylosper/bomi#456]
Hi.
When i want to install bomi with PPA on elementary OS 0.3.2 Freya, it says i have broken packages.

The following packages have unmet dependencies:
 bomi : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Kabouik** [comment]
See (this)[https://github.com/xylosper/bomi/issues/450], even though it might just be a temporary and dirty solution.

**Comment by rasulian** [comment]
@Kabouik Thanks!

**Comment by rasulian** [comment]
@Kabouik Thanks
