### ISSUE TITLE
E: Failed to fetch http://ppa.launchpad.net/darklin20/bomi/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

### ISSUE THREAD

**Issue by 243750496** [xylosper/bomi#480]
how to solve this problem 
i am using ubuntu 16.04

`cc@CC:~$ sudo apt-get update
Hit:1 http://cn.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://cn.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Hit:3 http://cn.archive.ubuntu.com/ubuntu xenial-backports InRelease           
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]    
Hit:5 http://ppa.launchpad.net/costales/anoise/ubuntu xenial InRelease
Ign:6 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial InRelease          
Hit:7 http://ppa.launchpad.net/wiznote-team/ppa/ubuntu xenial InRelease
Ign:8 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial Release
Ign:9 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main all Packages 
Ign:12 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main all Packages 
Ign:12 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main DEP-11 64x64 Icons
Err:9 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:10 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 94.5 kB in 34s (2,750 B/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/darklin20/bomi/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/darklin20/bomi/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by shvchk** [comment]
Sadly, that PPA has not been updated for a long long time, so it does not have a package for recent Ubuntu releases, the latest release it has package for is Vivid. You could download deb package and install it manually, but there is no guarantee that will work, and you won't get auto updates this way (well, this project is not being updated for a long time anyway).

Hope xylosper or someone else will maintain the project and update package for recent Ubuntu releases.

**Comment by workman729** [comment]
use ppa:darklin20/bomi, It's not xenial! I't vivid.

**Comment by 243750496** [comment]
sloved
