### ISSUE TITLE
How do I get rid of the yellow text on screen?

### ISSUE THREAD

**Issue by hexag1** [xylosper/bomi#500]
EDIT: it's the TAB key. Thanks DoTheEvo!

Here's my Bomi screen. How do I turn off the info text on screen? I searched the menu, but could not find the option. I don't know how I turned it on in the first place.

![screenshot_2017-04-27_23-30-31](https://cloud.githubusercontent.com/assets/19234035/25515001/070d51fc-2ba7-11e7-92b6-0eb67a956996.png)

**Comment by DoTheEvo** [comment]
tab key

**Comment by hexag1** [comment]
thank you!
