### ISSUE TITLE
Is there anyone can build it to .deb file?

### ISSUE THREAD

**Issue by jay763190097** [xylosper/bomi#535]
I want to install this fantastic soft in debain platform.

**Comment by timkb4cq** [comment]
MX-Linux 19 has Bomi in our Test repository.  MX-Linux is based on Debian stable (Buster).
Libchardet is a dependency of Bomi that's not in the Debian repos, but the rest of the dependencies are. 
http://mxrepo.com/mx/testrepo/pool/test/b/bomi/
http://mxrepo.com/mx/testrepo/pool/test/libc/libchardet/

**Comment by jay763190097** [comment]
@timkb4cq Thank you very much! It works for me.

**Comment by jay763190097** [comment]
![截图录屏_bomi_20200611191109](https://user-images.githubusercontent.com/16317178/84378814-5b0c9d00-ac17-11ea-8b5d-7df2642af35e.png)
Fantastic! If the title bar can hide is better.
