### ISSUE TITLE
0.8.13 주분투 전화면시 패널이 보이는 문제.

### ISSUE THREAD

**Issue by nemonein** [xylosper/bomi#77]
안녕하세요. 오랜만에 또 인사드립니다.

제가 아직 우분투 14.04 는 정식 설치(?)는 못해봤습니다.
노트북에 주분투 14.04 를 설치했는데요. 32bit 환경이고, AMD(Ati) 그래픽 칩을 사용한 제품입니다.

![xubuntu-fullscreen](https://cloud.githubusercontent.com/assets/5688288/2788222/612c159c-cb97-11e3-833c-622953efbb1c.png)

화면에서 처럼 전화면으로 전환 시에, 화면 상단에 위치한 주분투 기본 패널이 가려지지 않고 보여지고 있습니다.
크게 불편한 건 아니지만, 혹시 살펴봐주실 수 있는지 부탁드립니다.

고맙습니다.

**Comment by xylosper** [comment]
다른 프로그램도 동일하게 동작하는 걸로봐서 xfce의 문제로 보여 닫습니다.
